In [1]:
%%capture
!pip install wikipedia-api
!pip install country-converter

In [2]:
import requests
import wikipediaapi
from bs4 import BeautifulSoup
import json
import os
from collections import deque
import time
import random
import pandas as pd
import numpy as np
import matplotlib as plt
from collections import Counter
import country_converter as coco
from tqdm import tqdm

In [3]:
#import wikipediaapi
wiki = wikipediaapi.Wikipedia(
    user_agent='MysterySearchEngine/1.0 (contact: your@email.com)',
    language='en',
    extract_format=wikipediaapi.ExtractFormat.WIKI
)

In [4]:
def filter_dataframe(data_frame, allowed=None, unallowed=None, contains=None):
    """
    Filters the dataframe based on allowed and unallowed values.
    Example params: allowed={'Action': ['Click', 'View']}, unallowed={'Depth': [0]}
    """
    filtered_df = data_frame.copy()

    # Process "Allowed" values (Must be in the list)
    if allowed:
        for column, values in allowed.items():
            if column in filtered_df.columns:
                filtered_df = filtered_df[filtered_df[column].isin(values)]

    # Process "Unallowed" values (Must NOT be in the list)
    if unallowed:
        for column, values in unallowed.items():
            if column in filtered_df.columns:
                filtered_df = filtered_df[~filtered_df[column].isin(values)]

    # Substring Match: Include (Case insensitive)
    if contains:
        for column, substring in contains.items():
            if column in filtered_df.columns:
                # We convert to string in case the column is numeric (like Depth)
                # na=False prevents errors if there are empty cells
                mask = filtered_df[column].astype(str).str.contains(substring, case=False, na=False)
                filtered_df = filtered_df[mask]

    return filtered_df

In [5]:
def save_progress():
    """Saves all data structures to disk."""
    data = {
        "pages_db": pages_db,
        "crawl_errors": crawl_errors,
        "wikipedia_queue": list(wikipedia_queue),
        "external_links_queue": list(external_links_queue),
        "visited_pages": list(visited_pages),
        "overflow":list(overflow),
        "manual_inspection_bucket": list(manual_inspection_bucket),
        "pages_with_tables": list(pages_with_tables),
        "footprint":list(footprint),
        "see_also_links":list(see_also_title)
    }
    with open(f"{SAVEFILE_DIR}crawler_checkpoint.json", "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=4)
    print("--- Progress Saved Successfully ---")

def load_progress():
    """Loads progress if a checkpoint exists."""
    global pages_db, crawl_errors, wikipedia_queue, external_links_queue, visited_pages, manual_inspection_bucket,see_also_title,pages_with_tables,overflow,footprint
    if os.path.exists(f"{SAVEFILE_DIR}crawler_checkpoint.json"):
        with open(f"{SAVEFILE_DIR}crawler_checkpoint.json", "r", encoding="utf-8") as f:
            data = json.load(f)
            pages_db = data.get("pages_db", {})
            crawl_errors = data.get("crawl_errors", {})
            wikipedia_queue = deque(data.get("wikipedia_queue", []))
            external_links_queue = set(data.get("external_links_queue", []))
            visited_pages = set(data.get("visited_pages", []))
            manual_inspection_bucket = set(data.get("manual_inspection_bucket", []))
            see_also_title = set(data.get("see_also_links",[]))
            pages_with_tables = list(data.get("pages_with_tables",[]))
            overflow = set(data.get("overflow",[]))
            footprint = list(data.get("footprint",[]))
        print("--- Progress Loaded from Checkpoint ---")

In [9]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## Experiment

In [ ]:
import requests
import json
from bs4 import BeautifulSoup

def record_page_tables_as_json(title):
    headers = {'User-Agent': 'MysteryBotName (email@example.com)'}
    url = f"https://en.wikipedia.org/wiki/{title.replace(' ', '_')}"
    response = requests.get(url, headers=headers)
    soup = BeautifulSoup(response.content, 'html.parser')

    content = soup.find('div', class_='mw-parser-output')
    if not content: return []

    scraped_tables = []
    current_hierarchy = {2: "Introduction", 3: None, 4: None, 5: None, 6: None}

    for tag in content.find_all(['h2', 'h3', 'h4', 'h5', 'h6', 'table']):
        if tag.name in ['h2', 'h3', 'h4', 'h5', 'h6']:
            level = int(tag.name[1])
            current_hierarchy[level] = tag.get_text(strip=True).replace('[edit]', '')
            for i in range(level + 1, 7): current_hierarchy[i] = None

        elif tag.name == 'table' and 'wikitable' in tag.get('class', []):
            caption_tag = tag.find('caption')
            table_obj = {
                "section_hierarchy": [current_hierarchy[i] for i in range(2, 7) if current_hierarchy[i]],
                "caption": caption_tag.get_text(strip=True) if caption_tag else None,
                "rows": []
            }

            for tr in tag.find_all('tr'):
                row_cells = []
                for cell in tr.find_all(['td', 'th']):
                    row_cells.append({
                        "text": cell.get_text(strip=True),
                        "is_header": cell.name == 'th',
                        "rowspan": int(cell.get('rowspan', 1)),
                        "colspan": int(cell.get('colspan', 1))
                    })
                if row_cells:
                    table_obj["rows"].append(row_cells)

            scraped_tables.append(table_obj)

    return scraped_tables

# Example Usage
data = record_page_tables_as_json("Dole Air Race")
print(json.dumps(data[0], indent=2))

{
  "section_hierarchy": [
    "The Dole prize",
    "Contestants draw positions"
  ],
  "caption": "Official and unofficial entrants[16]and starting draw[17][12]:\u200a183\u2013184",
  "rows": [
    [
      {
        "text": "Entrant",
        "is_header": true,
        "rowspan": 1,
        "colspan": 4
      },
      {
        "text": "Starting Position",
        "is_header": true,
        "rowspan": 1,
        "colspan": 2
      }
    ],
    [
      {
        "text": "Official / Unofficial",
        "is_header": true,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "Pilot",
        "is_header": true,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "Navigator",
        "is_header": true,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "From",
        "is_header": true,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "Drawn",
        "is_header": true,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "Mills/Oakland",
        "is_header": true,
        "rowspan": 1,
        "colspan": 1
      }
    ],
    [
      {
        "text": "O",
        "is_header": true,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "Arthur C. Goebel",
        "is_header": false,
        "rowspan": 1,
        "colspan": 2
      },
      {
        "text": "Santa Monica, CA",
        "is_header": false,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "9",
        "is_header": true,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "M\u00a0(1)",
        "is_header": false,
        "rowspan": 1,
        "colspan": 1
      }
    ],
    [
      {
        "text": "O",
        "is_header": true,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "Maj. Livingston Irving",
        "is_header": false,
        "rowspan": 1,
        "colspan": 2
      },
      {
        "text": "Berkeley, CA",
        "is_header": false,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "7",
        "is_header": true,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "O\u00a0(7)",
        "is_header": false,
        "rowspan": 1,
        "colspan": 1
      }
    ],
    [
      {
        "text": "O",
        "is_header": true,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "John Augie Pedlar(w/ Miss Mildred Doran)",
        "is_header": false,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "Manley R. Lawing",
        "is_header": false,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "Flint, MI",
        "is_header": false,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "4",
        "is_header": true,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "O\u00a0(4)",
        "is_header": false,
        "rowspan": 1,
        "colspan": 1
      }
    ],
    [
      {
        "text": "O",
        "is_header": true,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "Frederick A. Giles",
        "is_header": false,
        "rowspan": 1,
        "colspan": 2
      },
      {
        "text": "Detroit, MI",
        "is_header": false,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "6",
        "is_header": true,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "O\u00a0(6)",
        "is_header": false,
        "rowspan": 1,
        "colspan": 1
      }
    ],
    [
      {
        "text": "O",
        "is_header": true,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "Charles W. Parkhurst",
        "is_header": false,
        "rowspan": 1,
        "colspan": 2
      },
      {
        "text": "Lomax, IL",
        "is_header": false,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "3",
        "is_header": true,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "O\u00a0(3)",
        "is_header": false,
        "rowspan": 1,
        "colspan": 1
      }
    ],
    [
      {
        "text": "O",
        "is_header": true,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "Lt. N. A. Goddard",
        "is_header": false,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "Lt. K. C. Hawkins",
        "is_header": false,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "San Diego, CA",
        "is_header": false,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "2",
        "is_header": true,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "O\u00a0(2)",
        "is_header": false,
        "rowspan": 1,
        "colspan": 1
      }
    ],
    [
      {
        "text": "O",
        "is_header": true,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "Arthur V. Rogers",
        "is_header": false,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "Leland A. Bryant",
        "is_header": false,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "Los Angeles, CA",
        "is_header": false,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "14",
        "is_header": true,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "O\u00a0(11)",
        "is_header": false,
        "rowspan": 1,
        "colspan": 1
      }
    ],
    [
      {
        "text": "O",
        "is_header": true,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "John W. Frost",
        "is_header": false,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "Gordon Scott",
        "is_header": false,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "San Francisco, CA",
        "is_header": false,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "15",
        "is_header": true,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "M\u00a0(2)",
        "is_header": false,
        "rowspan": 1,
        "colspan": 1
      }
    ],
    [
      {
        "text": "O",
        "is_header": true,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "Bennett Griffin",
        "is_header": false,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "Al Henley",
        "is_header": false,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "Bartlesville, OK",
        "is_header": false,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "1",
        "is_header": true,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "O\u00a0(1)",
        "is_header": false,
        "rowspan": 1,
        "colspan": 1
      }
    ],
    [
      {
        "text": "O",
        "is_header": true,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "Robert C. Fowler",
        "is_header": false,
        "rowspan": 1,
        "colspan": 2
      },
      {
        "text": "San Francisco, CA",
        "is_header": false,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "10",
        "is_header": true,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "\u2014",
        "is_header": false,
        "rowspan": 1,
        "colspan": 1
      }
    ],
    [
      {
        "text": "O",
        "is_header": true,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "Capt. J. L. Giffin",
        "is_header": false,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "Theodore Lundgren",
        "is_header": false,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "Long Beach, CA",
        "is_header": false,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "8",
        "is_header": true,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "O\u00a0(8)",
        "is_header": false,
        "rowspan": 1,
        "colspan": 1
      }
    ],
    [
      {
        "text": "O",
        "is_header": true,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "Capt. & Mrs. Wm. P. Erwin",
        "is_header": false,
        "rowspan": 1,
        "colspan": 2
      },
      {
        "text": "Dallas, TX",
        "is_header": false,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "5",
        "is_header": true,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "O\u00a0(5)",
        "is_header": false,
        "rowspan": 1,
        "colspan": 1
      }
    ],
    [
      {
        "text": "O",
        "is_header": true,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "Frank L. Clarke",
        "is_header": false,
        "rowspan": 1,
        "colspan": 2
      },
      {
        "text": "Hollywood, CA",
        "is_header": false,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "12",
        "is_header": true,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "M\u00a0(10)",
        "is_header": false,
        "rowspan": 1,
        "colspan": 1
      }
    ],
    [
      {
        "text": "O",
        "is_header": true,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "George D. Covell",
        "is_header": false,
        "rowspan": 1,
        "colspan": 2
      },
      {
        "text": "San Diego, CA",
        "is_header": false,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "13",
        "is_header": true,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "\u2014",
        "is_header": false,
        "rowspan": 1,
        "colspan": 1
      }
    ],
    [
      {
        "text": "U",
        "is_header": true,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "Martin Jensen",
        "is_header": false,
        "rowspan": 1,
        "colspan": 2
      },
      {
        "text": "Honolulu, HI",
        "is_header": false,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "11",
        "is_header": true,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "\u2014",
        "is_header": false,
        "rowspan": 1,
        "colspan": 1
      }
    ],
    [
      {
        "text": "U",
        "is_header": true,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "Robert Horseley",
        "is_header": false,
        "rowspan": 1,
        "colspan": 2
      },
      {
        "text": "Sarasota, FL",
        "is_header": false,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "\u2014",
        "is_header": true,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "\u2014",
        "is_header": false,
        "rowspan": 1,
        "colspan": 1
      }
    ],
    [
      {
        "text": "U",
        "is_header": true,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "Maj. C. Usborne",
        "is_header": false,
        "rowspan": 1,
        "colspan": 2
      },
      {
        "text": "Vancouver, BC",
        "is_header": false,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "\u2014",
        "is_header": true,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "\u2014",
        "is_header": false,
        "rowspan": 1,
        "colspan": 1
      }
    ],
    [
      {
        "text": "U",
        "is_header": true,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "Clair Vance",
        "is_header": false,
        "rowspan": 1,
        "colspan": 2
      },
      {
        "text": "San Francisco, CA",
        "is_header": false,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "\u2014",
        "is_header": true,
        "rowspan": 1,
        "colspan": 1
      },
      {
        "text": "\u2014",
        "is_header": false,
        "rowspan": 1,
        "colspan": 1
      }
    ]
  ]
}

In [ ]:
record_page_tables_as_json("Python_(programming_language)")

[{'section_hierarchy': ['Hostages'],
  'caption': 'Nationalities and status of the hostages[23][24][3]',
  'rows': [[{'text': 'Country', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'Number', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'Status', 'is_header': True, 'rowspan': 1, 'colspan': 1}],
   [{'text': 'United States', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': '1', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': 'Killed', 'is_header': False, 'rowspan': 1, 'colspan': 1}],
   [{'text': 'Yemen', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': '7', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': '6 rescued, 1 unknown',
     'is_header': False,
     'rowspan': 1,
     'colspan': 1}],
   [{'text': 'Saudi Arabia', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': '1', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': 'Rescued', 'is_header': False, 'rowspan': 1, 'colspan': 1}],
   [{'text': 'Ethiopia', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': '1', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': 'Rescued', 'is_header': False, 'rowspan': 1, 'colspan': 1}],
   [{'text': 'South Africa', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': '1', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': 'Killed', 'is_header': False, 'rowspan': 1, 'colspan': 1}],
   [{'text': 'United Kingdom', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': '1', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': 'Unknown', 'is_header': False, 'rowspan': 1, 'colspan': 1}],
   [{'text': 'Turkey', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': '1', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': 'Unknown', 'is_header': False, 'rowspan': 1, 'colspan': 1}],
   [{'text': 'Total', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': '13', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': '8 rescued, 2 killed, 3 unknown',
     'is_header': False,
     'rowspan': 1,
     'colspan': 1}]]}]

In [ ]:
record_page_tables_as_json("2014_hostage_rescue_operations_in_Yemen")

In [ ]:
a = record_page_tables_as_json("Dole_Air_Race")
print(len(a))
a

2

[{'section_hierarchy': ['The Dole prize', 'Contestants draw positions'],
  'rows': [[{'text': 'Entrant', 'is_header': True, 'rowspan': 1, 'colspan': 4},
    {'text': 'Starting Position',
     'is_header': True,
     'rowspan': 1,
     'colspan': 2}],
   [{'text': 'Official / Unofficial',
     'is_header': True,
     'rowspan': 1,
     'colspan': 1},
    {'text': 'Pilot', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'Navigator', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'From', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'Drawn', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'Mills/Oakland', 'is_header': True, 'rowspan': 1, 'colspan': 1}],
   [{'text': 'O', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'Arthur C. Goebel',
     'is_header': False,
     'rowspan': 1,
     'colspan': 2},
    {'text': 'Santa Monica, CA',
     'is_header': False,
     'rowspan': 1,
     'colspan': 1},
    {'text': '9', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'M\xa0(1)', 'is_header': False, 'rowspan': 1, 'colspan': 1}],
   [{'text': 'O', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'Maj. Livingston Irving',
     'is_header': False,
     'rowspan': 1,
     'colspan': 2},
    {'text': 'Berkeley, CA', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': '7', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'O\xa0(7)', 'is_header': False, 'rowspan': 1, 'colspan': 1}],
   [{'text': 'O', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'John Augie Pedlar(w/ Miss Mildred Doran)',
     'is_header': False,
     'rowspan': 1,
     'colspan': 1},
    {'text': 'Manley R. Lawing',
     'is_header': False,
     'rowspan': 1,
     'colspan': 1},
    {'text': 'Flint, MI', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': '4', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'O\xa0(4)', 'is_header': False, 'rowspan': 1, 'colspan': 1}],
   [{'text': 'O', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'Frederick A. Giles',
     'is_header': False,
     'rowspan': 1,
     'colspan': 2},
    {'text': 'Detroit, MI', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': '6', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'O\xa0(6)', 'is_header': False, 'rowspan': 1, 'colspan': 1}],
   [{'text': 'O', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'Charles W. Parkhurst',
     'is_header': False,
     'rowspan': 1,
     'colspan': 2},
    {'text': 'Lomax, IL', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': '3', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'O\xa0(3)', 'is_header': False, 'rowspan': 1, 'colspan': 1}],
   [{'text': 'O', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'Lt. N. A. Goddard',
     'is_header': False,
     'rowspan': 1,
     'colspan': 1},
    {'text': 'Lt. K. C. Hawkins',
     'is_header': False,
     'rowspan': 1,
     'colspan': 1},
    {'text': 'San Diego, CA', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': '2', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'O\xa0(2)', 'is_header': False, 'rowspan': 1, 'colspan': 1}],
   [{'text': 'O', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'Arthur V. Rogers',
     'is_header': False,
     'rowspan': 1,
     'colspan': 1},
    {'text': 'Leland A. Bryant',
     'is_header': False,
     'rowspan': 1,
     'colspan': 1},
    {'text': 'Los Angeles, CA',
     'is_header': False,
     'rowspan': 1,
     'colspan': 1},
    {'text': '14', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'O\xa0(11)', 'is_header': False, 'rowspan': 1, 'colspan': 1}],
   [{'text': 'O', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'John W. Frost', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': 'Gordon Scott', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': 'San Francisco, CA',
     'is_header': False,
     'rowspan': 1,
     'colspan': 1},
    {'text': '15', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'M\xa0(2)', 'is_header': False, 'rowspan': 1, 'colspan': 1}],
   [{'text': 'O', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'Bennett Griffin',
     'is_header': False,
     'rowspan': 1,
     'colspan': 1},
    {'text': 'Al Henley', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': 'Bartlesville, OK',
     'is_header': False,
     'rowspan': 1,
     'colspan': 1},
    {'text': '1', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'O\xa0(1)', 'is_header': False, 'rowspan': 1, 'colspan': 1}],
   [{'text': 'O', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'Robert C. Fowler',
     'is_header': False,
     'rowspan': 1,
     'colspan': 2},
    {'text': 'San Francisco, CA',
     'is_header': False,
     'rowspan': 1,
     'colspan': 1},
    {'text': '10', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': '—', 'is_header': False, 'rowspan': 1, 'colspan': 1}],
   [{'text': 'O', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'Capt. J. L. Giffin',
     'is_header': False,
     'rowspan': 1,
     'colspan': 1},
    {'text': 'Theodore Lundgren',
     'is_header': False,
     'rowspan': 1,
     'colspan': 1},
    {'text': 'Long Beach, CA', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': '8', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'O\xa0(8)', 'is_header': False, 'rowspan': 1, 'colspan': 1}],
   [{'text': 'O', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'Capt. & Mrs. Wm. P. Erwin',
     'is_header': False,
     'rowspan': 1,
     'colspan': 2},
    {'text': 'Dallas, TX', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': '5', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'O\xa0(5)', 'is_header': False, 'rowspan': 1, 'colspan': 1}],
   [{'text': 'O', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'Frank L. Clarke',
     'is_header': False,
     'rowspan': 1,
     'colspan': 2},
    {'text': 'Hollywood, CA', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': '12', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'M\xa0(10)', 'is_header': False, 'rowspan': 1, 'colspan': 1}],
   [{'text': 'O', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'George D. Covell',
     'is_header': False,
     'rowspan': 1,
     'colspan': 2},
    {'text': 'San Diego, CA', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': '13', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': '—', 'is_header': False, 'rowspan': 1, 'colspan': 1}],
   [{'text': 'U', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'Martin Jensen', 'is_header': False, 'rowspan': 1, 'colspan': 2},
    {'text': 'Honolulu, HI', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': '11', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': '—', 'is_header': False, 'rowspan': 1, 'colspan': 1}],
   [{'text': 'U', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'Robert Horseley',
     'is_header': False,
     'rowspan': 1,
     'colspan': 2},
    {'text': 'Sarasota, FL', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': '—', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': '—', 'is_header': False, 'rowspan': 1, 'colspan': 1}],
   [{'text': 'U', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'Maj. C. Usborne',
     'is_header': False,
     'rowspan': 1,
     'colspan': 2},
    {'text': 'Vancouver, BC', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': '—', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': '—', 'is_header': False, 'rowspan': 1, 'colspan': 1}],
   [{'text': 'U', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'Clair Vance', 'is_header': False, 'rowspan': 1, 'colspan': 2},
    {'text': 'San Francisco, CA',
     'is_header': False,
     'rowspan': 1,
     'colspan': 1},
    {'text': '—', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': '—', 'is_header': False, 'rowspan': 1, 'colspan': 1}]]},
 {'section_hierarchy': ['Race summary'],
  'rows': [[{'text': 'Notes:PN-9refers to the unsuccessful 1925 Navy attemptBird of Paradiseis the successful June 1927 Maitland/Hegenberger flightCity of Oaklandis misspelled asSpiritand refers to the July 1927 Smith/Bronte flight and crash landingMiss Doranis misspelled asDorian',
     'is_header': False,
     'rowspan': 1,
     'colspan': 12}],
   [{'text': 'Aircraft', 'is_header': True, 'rowspan': 1, 'colspan': 4},
    {'text': 'Start', 'is_header': True, 'rowspan': 1, 'colspan': 2},
    {'text': 'Pilot', 'is_header': True, 'rowspan': 2, 'colspan': 1},
    {'text': 'Navigator', 'is_header': True, 'rowspan': 2, 'colspan': 1},
    {'text': 'Livery', 'is_header': True, 'rowspan': 2, 'colspan': 1},
    {'text': 'Finish', 'is_header': True, 'rowspan': 2, 'colspan': 1},
    {'text': 'Notes', 'is_header': True, 'rowspan': 2, 'colspan': 1},
    {'text': 'Ref.', 'is_header': True, 'rowspan': 2, 'colspan': 1}],
   [{'text': 'Make & Model', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'Name', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'Registration', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'Image', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'Draw', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'Launch', 'is_header': True, 'rowspan': 1, 'colspan': 1}],
   [{'text': 'Travel Air 5000', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'Oklahoma', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'NX911', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': '', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': '1', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': '1', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': 'Bennett Griffin',
     'is_header': False,
     'rowspan': 1,
     'colspan': 1},
    {'text': 'Al Henley', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': 'Blue with yellow wings',
     'is_header': False,
     'rowspan': 1,
     'colspan': 1},
    {'text': 'DNS', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': 'Forced to return after 30 minutes with fuselage issues.',
     'is_header': False,
     'rowspan': 1,
     'colspan': 1},
    {'text': '[82][83]', 'is_header': False, 'rowspan': 1, 'colspan': 1}],
   [{'text': 'Goddard Special', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'El Encanto', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'NX5074', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': '', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': '2', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': '2', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': 'Norman A. Goddard',
     'is_header': False,
     'rowspan': 1,
     'colspan': 1},
    {'text': 'Kenneth C. Hawkins',
     'is_header': False,
     'rowspan': 1,
     'colspan': 1},
    {'text': 'Silver', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': 'DNS', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': 'Wrecked on takeoff.',
     'is_header': False,
     'rowspan': 1,
     'colspan': 1},
    {'text': '[82][83][84][85]',
     'is_header': False,
     'rowspan': 1,
     'colspan': 1}],
   [{'text': 'Breese-Wilde Model 5',
     'is_header': True,
     'rowspan': 1,
     'colspan': 1},
    {'text': 'Pabco Pacific Flyer',
     'is_header': True,
     'rowspan': 1,
     'colspan': 1},
    {'text': 'NX646', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': '', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': '7', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': '3', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': 'Livingston Gilson Irving',
     'is_header': False,
     'rowspan': 1,
     'colspan': 2},
    {'text': 'Orange and black',
     'is_header': False,
     'rowspan': 1,
     'colspan': 1},
    {'text': 'DNS', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': 'Wrecked after two attempts to take off.',
     'is_header': False,
     'rowspan': 1,
     'colspan': 1},
    {'text': '[83]', 'is_header': False, 'rowspan': 1, 'colspan': 1}],
   [{'text': 'Lockheed Vega', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'Golden Eagle', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'NX913', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': '', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': '15', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': '4', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': 'Jack Frost', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': 'Gordon Scott', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': 'Gold with blue landing gear.',
     'is_header': False,
     'rowspan': 1,
     'colspan': 1},
    {'text': 'DNF', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': 'Sponsored byGeorge Randolph Hearst, publisher of theSan Francisco Examiner. Lost at sea.',
     'is_header': False,
     'rowspan': 1,
     'colspan': 1},
    {'text': '[2][83][86][87]',
     'is_header': False,
     'rowspan': 1,
     'colspan': 1}],
   [{'text': 'Buhl Airsedan', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'Miss Doran', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'NX2915', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': '', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': '4', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': '5', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': 'Auggie Pedlar', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': 'Lt. V. R. Knope',
     'is_header': False,
     'rowspan': 1,
     'colspan': 1},
    {'text': 'Red wings, white fuselage, blue tail',
     'is_header': False,
     'rowspan': 1,
     'colspan': 1},
    {'text': 'DNF', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': 'Mildred Doran, namesake, was a passenger. Turned back after 14 minutes due to engine backfire; successfully took off on second attempt. Lost at sea.',
     'is_header': False,
     'rowspan': 1,
     'colspan': 1},
    {'text': '[83][86][88]', 'is_header': False, 'rowspan': 1, 'colspan': 1}],
   [{'text': 'Breese-Wilde Model 5',
     'is_header': True,
     'rowspan': 1,
     'colspan': 1},
    {'text': 'Aloha', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'NX914', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': '', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': '11', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': '6', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': 'Martin Jensen', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': 'Paul Schluter', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': 'Lemon yellow with pink lei',
     'is_header': False,
     'rowspan': 1,
     'colspan': 1},
    {'text': '2', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': '', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': '[5][83][88]', 'is_header': False, 'rowspan': 1, 'colspan': 1}],
   [{'text': 'Travel Air 5000', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'Woolaroc', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'NX869', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': '', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': '9', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': '7', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': 'Arthur Goebel', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': 'William V. Davis',
     'is_header': False,
     'rowspan': 1,
     'colspan': 1},
    {'text': 'Yellow and blue',
     'is_header': False,
     'rowspan': 1,
     'colspan': 1},
    {'text': '1', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': 'Finished with1+1⁄2US pints (0.71\xa0L) of gas. Name originated from the "woods, lakes, and rocks" on the lands of the corporate sponsor, Phillips Petroleum.',
     'is_header': False,
     'rowspan': 1,
     'colspan': 1},
    {'text': '[2][83][88]', 'is_header': False, 'rowspan': 1, 'colspan': 1}],
   [{'text': 'Swallow Monoplane',
     'is_header': True,
     'rowspan': 1,
     'colspan': 1},
    {'text': 'Dallas Spirit', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'NX941', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': '', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': '5', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': '8', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': 'William Portwood Erwin',
     'is_header': False,
     'rowspan': 1,
     'colspan': 1},
    {'text': 'Alvin Eichwaldt',
     'is_header': False,
     'rowspan': 1,
     'colspan': 1},
    {'text': 'Green', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': 'DNS', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': "Originally to be navigated by Erwin's wife, Constance. Forced to return with engine trouble. Lost at sea while searching for missingMiss DoranandGolden Eagle.",
     'is_header': False,
     'rowspan': 1,
     'colspan': 1},
    {'text': '[2][83]', 'is_header': False, 'rowspan': 1, 'colspan': 1}],
   [{'text': 'Entrants that withdrew, crashed, or disqualified prior to race start',
     'is_header': True,
     'rowspan': 1,
     'colspan': 12}],
   [{'text': 'Aircraft', 'is_header': True, 'rowspan': 1, 'colspan': 4},
    {'text': 'Start', 'is_header': True, 'rowspan': 1, 'colspan': 2},
    {'text': 'Pilot', 'is_header': True, 'rowspan': 2, 'colspan': 1},
    {'text': 'Navigator', 'is_header': True, 'rowspan': 2, 'colspan': 1},
    {'text': 'Livery', 'is_header': True, 'rowspan': 2, 'colspan': 1},
    {'text': 'Finish', 'is_header': True, 'rowspan': 2, 'colspan': 1},
    {'text': 'Notes', 'is_header': True, 'rowspan': 2, 'colspan': 1},
    {'text': 'Ref.', 'is_header': True, 'rowspan': 2, 'colspan': 1}],
   [{'text': 'Make & Model', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'Name', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'Registration', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'Image', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'Draw', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'Launch', 'is_header': True, 'rowspan': 1, 'colspan': 1}],
   [{'text': 'Air King biplane',
     'is_header': True,
     'rowspan': 1,
     'colspan': 1},
    {'text': 'City of Peoria', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': 'NX3070', 'is_header': True, 'rowspan': 1, 'colspan': 1},
    {'text': '', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': '3', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': '—', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': 'Charles Parkhurst',
     'is_header': False,
     'rowspan': 1,
     'colspan': 1},
    {'text': 'Ralph Lowes', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': 'Silver', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': 'DQ', 'is_header': False, 'rowspan': 1, 'colspan': 1},
    {'text': 'Disqualified for inadequate fuel capacity. Alternate pilots Dick Grace or Ernest Smith; Smith was the first civilian to fly nonstop to Hawaii, crashing on Molokai inCity of Oakland.',
     'is_header': False,
     'rowspan': 1,
     'colspan': 1},
    {'text': '[83][88]', 'is_header': False, 'rowspan': 1, 'colspan': 1}],

In [ ]:
import requests
from bs4 import BeautifulSoup

def get_img(title):
    results = [] # Stores: {"url": ..., "caption": ...}
    errors = []
    seen_urls = set()

    headers = {
        'User-Agent': 'MysteryBot/1.0 (myemail@example.com)',
        'Referer': 'https://www.google.com/'
    }

    try:
        # 1. Fetch the page
        formatted_title = title.replace(' ', '_')
        url = f"https://en.wikipedia.org/wiki/{formatted_title}"
        response = requests.get(url, headers=headers)

        if response.status_code in [403, 429]:
            raise PermissionError(f"Banned: Status {response.status_code}")

        soup = BeautifulSoup(response.content, 'html.parser')

        # 2. Focus only on article content to keep order and avoid UI icons
        content = soup.find(id="mw-content-text")
        if not content:
            return [], []

        # 3. Find all potential image "wrappers" in document order
        # Wikipedia uses:
        # - .infobox (Main top image)
        # - .thumb (Standard floating images)
        # - .figure (Modern HTML5 image tags)
        # - .gallerybox (Images inside a gallery section)
        wrappers = content.find_all(['table', 'div', 'figure', 'li'],
                                   class_=['infobox', 'thumb', 'thumbinner', 'gallerybox', 'mw-default-size'])

        for wrapper in wrappers:
            img_tag = wrapper.find('img')
            if not img_tag:
                continue

            # Skip small icons/pencils
            width = img_tag.get('width', '0')
            if not (width.isdigit() and int(width) > 50):
                continue

            # Construct URL
            src = img_tag.get('src')
            if not src: continue
            full_url = "https:" + src if src.startswith("//") else src

            # Deduplicate (some wrappers are nested)
            if full_url in seen_urls:
                continue

            # 4. Extract Caption based on container type
            caption = ""

            # Type A: Infobox (Caption is usually in the next <div> or a <tr>)
            if 'infobox' in wrapper.get('class', []):
                # Look for a caption div specifically inside the infobox
                cap_div = wrapper.find(class_='infobox-caption')
                if cap_div:
                    caption = cap_div.get_text(strip=True)
                else:
                    # Fallback: check if the next sibling cell has text
                    parent_td = img_tag.find_parent('td')
                    if parent_td:
                        next_div = parent_td.find('div')
                        if next_div and next_div != img_tag:
                            caption = next_div.get_text(strip=True)

            # Type B: Standard Thumbnail or Gallery
            elif any(cls in wrapper.get('class', []) for cls in ['thumb', 'thumbinner', 'gallerybox']):
                cap_div = wrapper.find(class_=['thumbcaption', 'gallerytext'])
                if cap_div:
                    # Remove the "magnify" icon text often found in thumbcaptions
                    for magnify in cap_div.find_all(class_='magnify'):
                        magnify.decompose()
                    caption = cap_div.get_text(strip=True)

            # Type C: HTML5 Figure
            elif wrapper.name == 'figure':
                cap_tag = wrapper.find('figcaption')
                if cap_tag:
                    caption = cap_tag.get_text(strip=True)

            results.append({
                "url": full_url,
                "caption": caption
            })
            seen_urls.add(full_url)

    except PermissionError:
        raise
    except Exception as e:
        errors.append({"type": "scraping_error", "msg": str(e)})

    return results, errors

In [ ]:
get_img("Python_(programming_language)")

([{'url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/250px-Python-logo-notext.svg.png',
   'caption': ''},
  {'url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Python_3.13_Standrd_Type_Hierarchy-en.svg/250px-Python_3.13_Standrd_Type_Hierarchy-en.svg.png',
   'caption': 'The standard type hierarchy in Python\xa03'}],
 [])

In [ ]:
get_img("Dole_Air_Race")

([{'url': 'https://upload.wikimedia.org/wikipedia/commons/a/a1/DoleAirR1927.gif',
   'caption': 'Dole Air Race movie reel (Prelinger Archives)'},
  {'url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/James_Drummond_Dole.jpg/250px-James_Drummond_Dole.jpg',
   'caption': 'James D Dole'},
  {'url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Travel_Air_5000_City_of_Oakland_after_running_out_of_fuel_over_Hawaii.jpg/250px-Travel_Air_5000_City_of_Oakland_after_running_out_of_fuel_over_Hawaii.jpg',
   'caption': 'City of Oaklandafter crash landing onMolokai'},
  {'url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Matson_Building_%26_Annex_%28San_Francisco%29.jpg/250px-Matson_Building_%26_Annex_%28San_Francisco%29.jpg',
   'caption': 'The draw started at theMatson Building.'},
  {'url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Dole_Air_Race_Buhl_CA-5_Air_Sedan_NX2915_Miss_Doran.jpg/250px-Dole_Air_Race_Buhl_CA-5_Air_Sedan_NX2915_Miss_Doran.jpg',
   'caption': 'Mildred Doranand theMiss Doran'},
  {'url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Dole_Air_Race_Tremaine_Humming_Bird_-_Waggener_%26_Covell_%282%29.jpg/250px-Dole_Air_Race_Tremaine_Humming_Bird_-_Waggener_%26_Covell_%282%29.jpg',
   'caption': 'Covell & Waggener,Spirit of John Rodgers'},
  {'url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Dole_Air_Race_-_8091692321.jpg/500px-Dole_Air_Race_-_8091692321.jpg',
   'caption': 'Entrants lined up to take off from Oakland on August 16, 1927.Oklahomais at the start of the runway. From left to right the others are:Aloha,Dallas Spirit,Miss Doran,Woolaroc,El Encanto,Golden Eagle,City of Peoria, andPabco Pacific Flyer'},
  {'url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Dole_Air_Race_NX5074_%22El_Encanto%22_Goddard_Special_%283%29.jpg/250px-Dole_Air_Race_NX5074_%22El_Encanto%22_Goddard_Special_%283%29.jpg',
   'caption': 'El Encanto(NX5074) after takeoff and crash'},
  {'url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Dole_Air_Race_-_Goebel%2C_Dole%2C_Jensen.jpg/250px-Dole_Air_Race_-_Goebel%2C_Dole%2C_Jensen.jpg',
   'caption': 'Dole (center) awards prizes to Goebel (L) and Jensen (R)'},
  {'url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Dole_Air_Race_NX913_%22Golden_Eagle%22_Lockheed_Vega%2C_Frost_%26_Scott.jpg/250px-Dole_Air_Race_NX913_%22Golden_Eagle%22_Lockheed_Vega%2C_Frost_%26_Scott.jpg',
   'caption': 'Golden Eagle: Frost (L) & Scott (R)'}],
 [])

In [ ]:
get_img("2014_hostage_rescue_operations_in_Yemen")

([{'url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Hagel_Press_Conference_December_6_2014.jpg/330px-Hagel_Press_Conference_December_6_2014.jpg',
   'caption': ''},
  {'url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Yemen_relief_location_map.jpg/250px-Yemen_relief_location_map.jpg',
   'caption': 'Location of Dafaar inYemen.'}],
 [])

In [ ]:
get_img("Disappearance_of_Luke_Durbin")

([{'url': 'https://upload.wikimedia.org/wikipedia/en/thumb/f/fb/Luke_Durbin.jpg/250px-Luke_Durbin.jpg',
   'caption': 'Photograph of Luke widely circulated in the wake of his disappearance and used for his missing poster by the charityMissing People.'},
  {'url': 'https://maps.wikimedia.org/img/osm-intl,16,52.055423,1.1549127,400x300.png?lang=en',
   'caption': '104:00 Zebra crossing to bus station, Dogs Head Street location of last confirmed sighting of Durbin'},
  {'url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Bus_Station_-_geograph.org.uk_-_2849286.jpg/250px-Bus_Station_-_geograph.org.uk_-_2849286.jpg',
   'caption': 'Zebra crossing to bus station, location of last confirmed sighting of Durbin'}],
 [])

In [ ]:
get_img("Jack_the_Ripper")[0]

[{'url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/JacktheRipper1888.jpg/250px-JacktheRipper1888.jpg',
  'caption': '"With the Vigilance Committee in the East End: A Suspicious Character" fromThe Illustrated London News,13 October1888'},
 {'url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/JacktheRipperWhitechapelcirca1890.jpg/250px-JacktheRipperWhitechapelcirca1890.jpg',
  'caption': 'Women and children congregate in front of one of the Whitechapelcommon lodging-housesclose to where Jack the Ripper murdered two of his victims.[1]'},
 {'url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Whitechapel_Spitalfields_7_murders.JPG/250px-Whitechapel_Spitalfields_7_murders.JPG',
  'caption': "The sites of the first seven Whitechapel murders\xa0–Osborn Street(centre right),George Yard(centre left),Hanbury Street(top),Buck's Row(far right),Berner Street(bottom right),Mitre Square(bottom left), andDorset Street(middle left)"},
 {'url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/29_Hanbury_Street%2C_1888.jpg/250px-29_Hanbury_Street%2C_1888.jpg',
  'caption': '29Hanbury Street. The door through whichAnnie Chapmanand her murderer walked to the yard where her body was discovered is beneath the numerals of the property sign.'},
 {'url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/CatherineEddowesJacktheRipperCanomicleVictimFourMitreSq.30091888a.jpg/250px-CatherineEddowesJacktheRipperCanomicleVictimFourMitreSq.30091888a.jpg',
  'caption': 'Contemporaneous police drawing of the body ofCatherine Eddowes, as discovered inMitre Square'},
 {'url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/MaryJaneKelly_Ripper.jpg/250px-MaryJaneKelly_Ripper.jpg',
  'caption': "Police photograph of the body ofMary Jane Kellyas discovered in 13 Miller's Court,Spitalfields, 9 November 1888"},
 {'url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Frances_Coles_1891.jpg/250px-Frances_Coles_1891.jpg',
  'caption': 'Frances Coles was found with her throat cut under a railway arch in Whitechapel on 13 February 1891.[94]'},
 {'url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Whitehall_murder_school_illustration.jpg/250px-Whitehall_murder_school_illustration.jpg',
  'caption': '"TheWhitehall Mystery" of October 1888'},
 {'url': 'https://upload.wikimedia.org/wikipedia/commons/9/9d/F.G.Abberline.jpg',
  'caption': 'InspectorFrederick Abberline'},
 {'url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Ripper_cartoon_punch.jpg/250px-Ripper_cartoon_punch.jpg',
  'caption': '"Blind man\'s buff":Punchcartoon byJohn Tenniel(22 September1888) criticising the police\'s alleged incompetence. The failure of the police to capture the killer reinforced the attitude held by radicals that the police were inept and mismanaged.[140]'},
 {'url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/JacktheRipperPuck.jpg/250px-JacktheRipperPuck.jpg',
  'caption': 'Speculation as to the identity of Jack the Ripper: cover of the 21 September 1889 issue ofPuckmagazine, by cartoonistTom Merry'},
 {'url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/FromHellLetter.jpg/250px-FromHellLetter.jpg',
  'caption': 'The "From Hell" letter'},
 {'url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/The_Penny_Illustrated_Paper_-_September_8%2C_1888_-_Jack_the_Ripper.jpg/250px-The_Penny_Illustrated_Paper_-_September_8%2C_1888_-_Jack_the_Ripper.jpg',
  'caption': '8 September 1888 edition of thePenny Illustrated Paperdepicting the discovery of the body of the first canonical Ripper victim,Mary Ann Nichols'},
 {'url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Jack-the-Ripper-The-Nemesis-of-Neglect-Punch-London-Charivari-cartoon-poem-1888-09-29.jpg/250px-Jack-the-Ripper-The-Nemesis-of-Neglect-Punch-London-Charivari-cartoon-poem-1888-09-29.jpg',
  'caption': 'The "Nemesis of Neglect": Jack the Ripper depicted as a phantom stalking Whitechapel, and as an embodiment of social neglect, in an 1888Punchcartoon'}]

## Main Wikipedia Crawler

In [ ]:
TEXT_LIMIT = None  # Set to a number (e.g., 500) or None for full text
WAIT_RANGE = (1, 3)
BATCH_SIZE = 4
MAX_DEPTH = 2
SAVEFILE_DIR = "/content/drive/MyDrive/Mystery Search Engine/"

In [ ]:
# Main Databases
pages_db = {}
# Error tracking: stores {title: {"type": "image|metadata|infobox", "error": "msg"}}
crawl_errors = {}

# Queues & Tracking
wikipedia_queue = deque([("Category:Unsolved crimes",0)])
external_links_queue = set()
visited_pages = set()
manual_inspection_bucket = set()
footprint = []
overflow = set()

pages_with_tables = []  # Stores (Title, URL)
see_also_title = set()     # Stores potential new Case Titles

In [ ]:
def record_page_tables(title):
    headers = {'User-Agent': 'MysteryBotName (email@example.com)'}
    url = f"https://en.wikipedia.org/wiki/{title.replace(' ', '_')}"
    response = requests.get(url, headers=headers)
    soup = BeautifulSoup(response.content, 'html.parser')

    scraped_tables = []

    for table in soup.find_all('table', class_='wikitable'):
        # Identify section
        header_tag = table.find_previous(['h2', 'h3', 'h4', 'h5', 'h6'])
        section = header_tag.get_text(strip=True).replace('[edit]', '') if header_tag else "Introduction"

        # Extract Headers
        headers_list = [th.get_text(strip=True) for th in table.find_all('th')]

        # Extract Rows
        rows_data = []
        for tr in table.find_all('tr')[1:]: # Skip header row
            cells = tr.find_all(['td', 'th'])
            if cells:
                rows_data.append([cell.get_text(strip=True) for cell in cells])

        scraped_tables.append({
            "section": section,
            "headers": headers_list,
            "data": rows_data
        })

    return scraped_tables


def get_table_links(title, col_name, allowed_sections=None):
    """
    allowed_sections: list of strings or None to get all tables.
    col_name: the exact name of the column 'X'
    """
    headers = {'User-Agent': 'BotName (email@example.com)'}
    url = f"https://en.wikipedia.org/wiki/{title.replace(' ', '_')}"
    response = requests.get(url, headers=headers)
    soup = BeautifulSoup(response.content, 'html.parser')

    found_links = []

    for table in soup.find_all('table', class_='wikitable'):
        # 1. Check Section Permission
        header_tag = table.find_previous(['h2', 'h3', 'h4', 'h5', 'h6'])
        section = header_tag.get_text(strip=True).replace('[edit]', '') if header_tag else "Introduction"

        if allowed_sections is not None and section not in allowed_sections:
            continue

        # 2. Find Column Index
        ths = [th.get_text(strip=True) for th in table.find_all('th')]
        try:
            col_index = ths.index(col_name)
        except ValueError:
            continue # Column 'X' not in this table

        # 3. Extract Links from that column
        for tr in table.find_all('tr'):
            cells = tr.find_all(['td', 'th'])
            if len(cells) > col_index:
                target_cell = cells[col_index]
                # Find all links in this specific cell
                links = target_cell.find_all('a', href=True)
                for l in links:
                    href = l['href']
                    if href.startswith('/wiki/'):
                        found_links.append(f"https://en.wikipedia.org{href}")
                    elif href.startswith('http'):
                        found_links.append(href)

    return list(set(found_links)) # Return unique links

In [ ]:
def get_advanced_data(title):
    images = []
    infobox_data = {}
    errors = []
    last_updated_text = ""

    # Same headers you used for BeautifulSoup
    headers = {
        'User-Agent': 'MysteryBot/1.0 (myemail@example.com)',
        'Referer': 'https://www.google.com/'
    }

    try:
        url = f"https://en.wikipedia.org/wiki/{title.replace(' ', '_')}"
        response = requests.get(url, headers=headers)

        if response.status_code in [403, 429]:
            raise PermissionError(f"Banned: Status {response.status_code}")

        soup = BeautifulSoup(response.content, 'html.parser')

        # 1. GET INFOBOX DATA
        infobox = soup.find("table", {"class": "infobox"})
        if infobox:
            for row in infobox.find_all("tr"):
                label = row.find("th")
                value = row.find("td")
                if label and value:
                    infobox_data[label.get_text(strip=True)] = value.get_text(strip=True)

        # 2. GET IMAGES FROM HTML (Bypassing the API)
        # We look for images in the infobox or the main content area
        # Filtering out tiny icons (less than 50px)
        img_tags = soup.find_all('img')
        for img in img_tags:
            src = img.get('src')
            if src:
                # Filter out small icons like edit pencils or UI elements
                width = img.get('width', '0')
                if width.isdigit() and int(width) > 50:
                    # Convert //upload... to https://upload...
                    full_url = "https:" + src if src.startswith("//") else src
                    images.append(full_url)

        # 4. Last Modified date
        footer_mod = soup.find("li", {"id": "footer-info-lastmod"})
        last_updated_text = footer_mod.get_text(strip=True) if footer_mod else "Unknown"

    except PermissionError:
        raise # Re-raise to trigger the main loop's "save and stop" logic
        print("permission error!")
    except Exception as e:
        errors.append({"type": "scraping_error", "msg": str(e)})
        print(f"scraping error:{str(e)}")

    return last_updated_text,images, infobox_data, errors

In [ ]:
def get_sections_tree(sections, text_limit=None):
    tree = []
    for s in sections:
        # Truncate text if limit is set
        content_text = s.text if text_limit is None else s.text[:text_limit]

        section_node = {
            "title": s.title,
            "content": [content_text] # List starts with the section's text
        }

        # If there are subsections, recurse and add them to the same content list
        if s.sections:
            section_node["content"].append(get_sections_tree(s.sections, text_limit))

        tree.append(section_node)
    return tree

In [ ]:
def run_crawler(limit=5, force_visit=False):
    try:
        processed = 0
        open_category = 0
        BATCH_CAT = 10
        while wikipedia_queue and processed < limit:
          current_title, depth, origin_title_raw = wikipedia_queue.popleft()
          ordinary = True
          origin_title = origin_title_raw
          if origin_title_raw[0] == "$":
              origin_title = origin_title_raw[1:]
              ordinary = False

          if not force_visit:
            if current_title in visited_pages:
                print(f"already visited {current_title}")
                continue

          if depth > MAX_DEPTH:
              overflow.add(current_title)
              footprint.append([current_title,origin_title,"overflow",depth])
              print(f"overflow {current_title}")
              continue

          page = wiki.page(current_title)
          if not page.exists():
              print(f"page {current_title} don't exist")
              continue

          print(f"Crawling: {page.title}")
          visited_pages.add(page.title)
          footprint.append([current_title,origin_title,"crawl",depth])

          #time.sleep(DELAY_SECONDS)

          # Handle CATEGORY
          if page.ns == wikipediaapi.Namespace.CATEGORY:
              for member in page.categorymembers.values():
                  wikipedia_queue.append((member.title,depth+1,current_title))
                  footprint.append([member.title,current_title,"category",depth+1])
              open_category += 1
              if open_category > BATCH_CAT:
                  time.sleep(random.uniform(*WAIT_RANGE))
                  open_category = 0

          # Handle LIST
          elif ordinary and (page.title.startswith("List of ") or page.title.startswith("Lists of ")):
              open_category = 0
              #check_title = page.title.lower()
              #if ("unsolved" in check_title):
              #    for link_title in page.backlinks.keys():
              #        wikipedia_queue.append((link_title, depth+1,current_title))
              #        footprint.append([link_title,current_title,"list unsolved",depth+1])
              #else:
              manual_inspection_bucket.add(page.title)
              footprint.append([current_title,origin_title,"list_manual_inspect",depth+1])

          # Handle ARTICLE
          else:
              open_category = 0
              # 1. Scrape Advanced Data (Images & Infobox)
              last_updated_text, imgs, infobox, errors = get_advanced_data(page.title)

              #print('passed advance')

              # 2. Log Errors if any
              if errors:
                  crawl_errors[page.title] = errors

              # 3. Store Article Data
              pages_db[page.title] = {
                  "origin_title":origin_title,
                  "url": page.fullurl,
                  "last_update_text":last_updated_text,
                  "summary": page.summary if TEXT_LIMIT is None else page.summary[:TEXT_LIMIT],
                  "infobox": infobox,
                  "sections_tree":  get_sections_tree(page.sections, TEXT_LIMIT),  #{s.title: s.text if TEXT_LIMIT is None else s.text[:TEXT_LIMIT] for s in page.sections }
                  "table":record_page_tables(page.title),
                  "categories": list(page.categories.keys())
              }
              #print('passed page db')

              # 4. Handle "See Also" links
              see_also_sec = [s for s in page.sections if s.title.lower() == "see also"]
              if see_also_sec:
                  # Add links mentioned in the 'See Also' section
                  # We filter page.links to only those appearing in that section's text
                  for link_title in page.links.keys():
                      if link_title in see_also_sec[0].text:
                          #wikipedia_queue.append(link_title)
                          see_also_title.add(link_title)
                          footprint.append([link_title,current_title,"see also",depth+1])
                          #manual_inspection_bucket.add(link_title)
              processed += 1
              if processed % BATCH_SIZE == 0:
                  time.sleep(random.uniform(*WAIT_RANGE))

              if processed >= limit:
                  print("hit limit :)")
                  break
                  #processed += 1
        print("Finished while loop")
    except PermissionError as e:
        print(f"!!! CRITICAL: Stopped because of ban: {e}")
    except Exception as e:
        print(f"!!! Unexpected Error: {e}")
    finally:
        # This ALWAYS runs, ensuring your data is not lost
        save_progress()
        print("Crawler stopped. Progress has been secured.")

In [ ]:
TEXT_LIMIT = None  # Set to a number (e.g., 500) or None for full text
WAIT_RANGE = (1, 3)
BATCH_SIZE = 4
MAX_DEPTH = 3
SAVEFILE_DIR = "/content/drive/MyDrive/Mystery Search Engine/"
# Main Databases
pages_db = {}
crawl_errors = {} # Error tracking: stores {title: {"type": "image|metadata|infobox", "error": "msg"}}

# Queues & Tracking
wikipedia_queue = deque([("Category:Unsolved crimes",0,"seed")])
external_links_queue = set()
visited_pages = set()
manual_inspection_bucket = set()
overflow = set()
footprint = []

pages_with_tables = []  # Stores (Title, URL)
see_also_title = set()     # Stores potential new Case Titles

# --- EXECUTION ---
#wikipedia_queue = deque([("Category:Missing_aircraft",0,"seed"),("Category:Missing_ships",0,"seed")])
wikipedia_queue = deque([("Category:Unexplained_disappearances",0,"seed")])
MAX_DEPTH = 2

In [ ]:
#wikipedia_queue = deque([("Cold case",0,"seed")])
#SAVEFILE_DIR = ""
load_progress() # Resume if possible
wikipedia_queue = deque([("Category:Unexplained_disappearances",0,"seed")])
run_crawler(limit=10000) # Adjust limit as needed
save_progress() # Save results

Crawling: Croye Pithey
Crawling: Arthur Piver
Crawling: Rosendo Porlier y Asteguieta
already visited Walter Powell (MP for Malmesbury)
Crawling: Tyrone Power (Irish actor)
Crawling: John James Powers
already visited Preston (1798 EIC ship)
Crawling: Günther Prien
Crawling: Angus Primrose
Crawling: Cecil Pugh
Crawling: Douglas Pyne
Crawling: Lynne C. Quiggle
already visited 1969 RAF Mildenhall C-130 theft
Crawling: Rafael Villaverde
Crawling: Alfred Raper
Crawling: Henry Hope Reed
Crawling: Alonso de Reinoso
Crawling: Kemal Reis
Crawling: David Thomas Richardson
Crawling: HMS Richmond helicopter crash
Crawling: Ridderschap van Holland (1682)
Crawling: Esmond Romilly
Crawling: Gerard Broadmead Roope
Crawling: Jürgen von Rosenstiel
Crawling: Inigo Ross
already visited Holly Roth
Crawling: Gerry Roufs
Crawling: Michael Rudolph
Crawling: Marc Armand Ruffer
Crawling: Boris Safonov
Crawling: Joseph Samuel
Crawling: Disappearance of ARA San Juan
Crawling: Giuseppe Sartorio
Crawling: Auzella Savage
Crawling: Jean-Jacques Savin
Crawling: Joachim Schepke
Crawling: Johann Schmid
Crawling: Adalbert Schneider
already visited Art Scholl
Crawling: Koos Schouwenaar
Crawling: Karl-Ernst Schroeter
Crawling: Heinz-Otto Schultze
already visited Sea Bird (ship)
already visited 1955 RAF Shackleton aircraft disappearance
Crawling: Trevarton Charles Sholl
Crawling: James Jenkins Simpson
Crawling: Joshua Slocum
Crawling: Archibald Bisset Smith
Crawling: Disappearance of George Smith
Crawling: Scott Smith (musician)
Crawling: William Snodgrass (politician)
Crawling: John Stanwix
Crawling: Henry E. Stebbins
Crawling: Jure Šterk
Crawling: Donald Stott
Crawling: Jean-François de Surville
Crawling: Éric Tabarly
already visited Tai Ching 21
Crawling: Peter Tessem and Paul Knutsen
Crawling: Thomas Blanky
Crawling: Eddie Thompson (Canadian football)
Crawling: Jenkin Thompson
Crawling: Gordon Thorne
Crawling: Bill Tilman
Crawling: Salvatore Toscano
Crawling: Denver V. Truelove
Crawling: Kenji Tsukagoshi
already visited Charles Ulm
Crawling: Urasoe Chōri
Crawling: James Henry Van Alen
already visited Leon Vance
Crawling: Henry Vansittart
Crawling: Vandino and Ugolino Vivaldi
Crawling: Hainan Island incident
Crawling: David Wanklyn
already visited SS Waratah
Crawling: Arthur Warbrick
Crawling: David Kenyon Webster
Crawling: Franz von Werra
Crawling: Peter White (footballer)
already visited Charles W. Whittlesey
Crawling: Lambert Wickes
Crawling: John W. Wilcox Jr.
already visited Hugh Willoughby
Crawling: Slim Wintermute
Crawling: Ralf-Reimar Wolfram
Crawling: Steve Wray
Crawling: Erich Würdemann
Crawling: John Yarnall
Crawling: Yong Yu Sing No. 18
Crawling: John Young (naval officer)
Crawling: Lamont Young
Crawling: Erwin von Zach
Crawling: File:Joe Pichler.jpg
Crawling: File:Katheryne Eggleston.png
Crawling: File:TaraCalico.jpg
Crawling: Nazi gold train
overflow List of kidnappings
overflow List of kidnappings before 1900
overflow List of kidnappings (1930–1939)
overflow List of kidnappings (1900–1929)
overflow List of kidnappings (1940–1949)
overflow List of kidnappings (1950–1959)
overflow List of kidnappings (1970–1979)
overflow List of kidnappings (1960–1969)
overflow List of kidnappings (1980–1989)
overflow List of kidnappings (1990–1999)
overflow List of kidnappings (2000–2009)
overflow List of kidnappings (2010–2019)
overflow List of kidnappings (2020–present)
already visited Malaysia Airlines Flight 370
overflow Malaysia Airlines Flight 370 disappearance theories
overflow Flight MH370: The Mystery
overflow MH370: The Plane That Disappeared
overflow Malaysia Airlines Flight 370 satellite communications
overflow Search for Malaysia Airlines Flight 370
overflow Timeline of Malaysia Airlines Flight 370
overflow Category:Search for Malaysia Airlines Flight 370
already visited Category:Films set in the Bermuda Triangle
already visited Category:Novels set in the Bermuda Triangle
already visited Category:Television episodes set in the Bermuda Triangle
already visited Category:Television shows set in the Bermuda Triangle
already visited Category:Video games set in the Bermuda Triangle
overflow Airport '77
overflow Aladdin (1986 film)
overflow Bermuda: Cave of the Sharks
overflow The Bermuda Depths
overflow Bermuda Tentacles
overflow The Bermuda Triangle (film)
overflow Encounters in the Deep
overflow Gulliver's Travels (2010 film)
overflow The Island (1980 film)
overflow The Land That Time Forgot (2009 film)
overflow Lost Voyage
overflow Monster Island (2004 film)
overflow Percy Jackson: Sea of Monsters
overflow Raging Sharks
overflow Satan's Triangle
overflow Scooby-Doo! Pirates Ahoy!
overflow Triangle (2009 British film)
overflow The Triangle (film)
overflow The Triangle (miniseries)
overflow The Island (Benchley novel)
overflow The Sea of Monsters
overflow Aquaman (TV pilot)
overflow I Play Dodgeball with Cannibals
overflow Triangle (The X-Files)
overflow The Fantastic Journey
overflow Percy Jackson and the Olympians (TV series)
overflow Wonder Woman (TV series)
overflow Bermuda Triangle (video game)
overflow Conduit 2
overflow Dark Void
overflow Death by Degrees
overflow DuckTales 2
overflow Jurassic: The Hunted
overflow Pirates: Duels on the High Seas
already visited Aagtekerke (1724)
already visited Active (1804 ship)
already visited Fortuyn (1722)
overflow Independence (schooner)
already visited HMCS Integrity (1804)
overflow HMS Jumna (1848)
overflow SS Koombana
already visited Loch Bredan (barque)
overflow Madagascar (1837 ship)
overflow Princess Charlotte (1819 brig)
already visited Ridderschap van Holland (1682)
already visited Victorine (ship)
already visited Aagtekerke (1724)
overflow Asgard II
overflow STV Astrid
overflow Atlantic (yacht)
overflow Belle Sheridan (1852)
overflow Bounty (1960 ship)
already visited Carina (yacht)
overflow Concordia (1696 ship)
overflow Concordia (ship)
overflow Eendracht (1615)
overflow Eleanor A. Percy
overflow Endeavour II (barque)
overflow Endymion (yacht)
already visited Fortuyn (1722)
overflow France II
overflow Helena (packet sailboat)
overflow Marques (bark)
overflow Preussen (ship)
already visited Ridderschap van Holland (1682)
overflow Scottish Maid
overflow Thomas W. Lawson (ship)
overflow Wind Song (ship)
overflow Wyoming (schooner)
overflow French submarine Bernoulli
overflow German submarine Bremen
overflow INS Dakar
overflow Flach (submarine)
overflow Italian submarine Guglielmo Marconi (1939)
overflow Category:Missing submarines of World War II
overflow Category:Missing U-boats
overflow Lost comet
overflow 5D/Brorsen
overflow 18D/Perrine–Mrkos
overflow 20D/Westphal
overflow 25D/Neujmin
overflow 34D/Gale
overflow 75D/Kohoutek
overflow 83D/Russell
overflow 85D/Boethin
overflow Biela's Comet
overflow Great Comet of 371 BC
overflow Lexell's Comet
overflow Lick Object of 1921
overflow D/1766 G1 (Helfenzrieder)
overflow D/1895 Q1 (Swift)
overflow D/1978 R1 (Haneda–Campos)
overflow P/2010 H2 (Vales)
overflow X/1106 C1
overflow X/1872 X1 (Pogson)
overflow X/1882 K1 (Tewfik)
overflow Lost minor planet
overflow 1979 XB
overflow 1991 BA
overflow 1998 DK36
overflow 2004 FU162
overflow 2005 ED224
overflow 2007 FT3
overflow 2007 WD5
overflow 2017 DB120
overflow 2017 MZ8
overflow 2017 SG33
overflow Moon of (208996) Achlys
overflow 11P/Tempel–Swift–LINEAR
overflow 18D/Perrine–Mrkos
overflow 26P/Grigg–Skjellerup
overflow 54P/de Vico–Swift–NEAT
overflow 58P/Jackson–Neujmin
overflow 64P/Swift–Gehrels
overflow 69P/Taylor
overflow 76P/West–Kohoutek–Ikemura
overflow 79P/du Toit–Hartley
overflow 80P/Peters–Hartley
overflow 84P/Giclas
overflow 97P/Metcalf–Brewington
overflow 113P/Spitaler
overflow 122P/de Vico
overflow 143P/Kowal–Mrkos
overflow 156P/Russell–LINEAR
overflow 158P/Kowal–LINEAR
overflow 177P/Barnard
overflow 206P/Barnard–Boattini
overflow 226P/Pigott–LINEAR–Kowalski
overflow 271P/van Houten–Lemmon
overflow 273P/Pons–Gambart
overflow 289P/Blanpain
overflow 449P/Leonard
overflow 489P/Denning
overflow Comet Swift–Tuttle
overflow 6344 P-L
overflow 132 Aethra
overflow 330 Adalberta
overflow 452 Hamiltonia
overflow 473 Nolli
overflow 525 Adelaide
overflow 719 Albert
overflow 724 Hapag
overflow 843 Nicolaia
overflow 878 Mildred
overflow 1009 Sirene
overflow 1026 Ingrid
overflow 1179 Mally
overflow 1537 Transylvania
overflow 1862 Apollo
overflow 1916 Boreas
overflow 1922 Zulu
overflow 2101 Adonis
overflow 3494 Purple Mountain
overflow 3789 Zhongguo
overflow 4015 Wilson–Harrington
overflow 7796 Járacimrman
overflow (29075) 1950 DA
overflow 69230 Hermes
overflow (523731) 2014 OK394
overflow S/2002 N 5
overflow S/2003 J 2
overflow S/2003 J 4
overflow S/2003 J 9
overflow S/2003 J 10
overflow S/2003 J 12
overflow S/2003 J 16
overflow S/2003 J 23
overflow S/2004 S 7
overflow S/2004 S 12
overflow S/2004 S 13
overflow S/2006 S 1
overflow S/2006 S 3
overflow S/2007 S 2
overflow S/2007 S 3
overflow Acbas
overflow Castle of Oblivion
overflow Granegg Castle (Niedereschach)
overflow Ichnae (Mesopotamia)
overflow Iselborgh
overflow Jomsborg
overflow Saeftinghe Castle
already visited Hanging Gardens of Babylon
overflow Amytis of Media
overflow Antipater of Sidon
overflow Civilization (video game)
overflow Civilization II
overflow Civilization III
overflow Civilization IV
overflow Civilization V
already visited Civilization VI
overflow Elephants Dream
overflow Jerwan
overflow Robert Koldewey
overflow Hormuzd Rassam
overflow Rhythm Thief & the Emperor's Treasure
already visited Ark of the Covenant
overflow The A.R.K. Report
overflow Aaron's rod
overflow Antiquities of the Jews
overflow Template:Ark of the Covenant
overflow Bezalel
overflow David Before the Ark of the Covenant
overflow Fall of Jericho
overflow Holy of Holies
overflow Kebra Nagast
overflow Mercy seat
overflow Oholiab
overflow Philistine captivity of the Ark
overflow Raiders of the Lost Ark
overflow 1 Samuel 4
overflow 1 Samuel 5
overflow 1 Samuel 6
overflow 1 Samuel 7
overflow 2 Samuel 6
overflow Shittah tree
overflow The Sign and the Seal
overflow Tablets of Stone
overflow Uzzah
overflow Category:Fall of Jericho
overflow Alexander III Commemorative (Fabergé egg)
overflow Cherub with Chariot (Fabergé egg)
overflow Hen with Sapphire Pendant (Fabergé egg)
overflow Mauve (Fabergé egg)
overflow Nécessaire (Fabergé egg)
overflow Royal Danish (Fabergé egg)
overflow Auto-destructive art
overflow Temporary art
overflow Girl with Balloon
overflow Love Is in the Bin
overflow Object to Be Destroyed
overflow A Pound of Flesh for 50p
overflow A Subtlety
overflow Zone de Sensibilité Picturale Immatérielle
overflow Nazi plunder
overflow List of claims for restitution for Nazi-looted art
overflow Nazi looting of artworks by Vincent van Gogh
overflow Nazi storage sites for art during World War II
overflow Reichsleiter Rosenberg Taskforce
overflow Maria Almas-Dietrich
overflow Bernhard Altmann
already visited Amber Room
overflow Otto Anninger
overflow Apple Tree II
overflow Gallery of Archduke Leopold Wilhelm in Brussels (Rothschild)
overflow Art collection of Carl Sachs
overflow Art Looting Investigation Unit
overflow Baron Herzog
overflow Bathers with a Turtle
overflow Kurt von Behr
overflow Leo Bendel
overflow Lea Bondi
overflow Karl Buchholz (art dealer)
overflow Das Bunte Leben
overflow Le Chemin, Paysage à Meudon
overflow Collectarium of Ląd
overflow Concealed Histories: Uncovering the Story of Nazi Looting
overflow The Continence of Scipio (Gerbrand van den Eeckhout)
overflow Customers Conversing in a Tavern
overflow Degenerate art
overflow Degenerate Art exhibition
overflow Hans Deutsch
overflow Dorotheum
overflow The Duchess of Montesquiou-Fezensac
overflow Hermann Eissler
overflow Max Emden
overflow En Canot
overflow Milton Esterow
overflow Evacuation of the Louvre collection during World War II
overflow Max Fischer (art collector)
overflow Theodor Fischer (auctioneer)
already visited Frédéric Chopin Memorial (Paris)
overflow Harry Fuld
overflow Federico Gentili Di Giuseppe
overflow Fritz Goldschmidt
overflow Fritz Grünbaum
overflow Gurlitt Collection
overflow César Mange de Hauke
overflow Hermann Göring Collection
overflow Im Kinsky
overflow International Archives for the Women's Movement
overflow Ismar Littmann Art Collection
overflow Jewess with Oranges
overflow Jewish art collectors in Breslau
overflow Gustav Kirstein
overflow Helga Kreuter-Eggemann
overflow The Last Judgment (Memling)
overflow August Lederer
overflow Serena Lederer
overflow Lempertz
overflow Liro Bank
overflow Madonna of Bruges
overflow Marguerite Fould
overflow Kurt Martin
overflow Wilhelm Mautner
overflow August L. Mayer
overflow Francesco von Mendelssohn
overflow Paul von Mendelssohn-Bartholdy
overflow Menzel v. List
overflow Reich Ministry of Public Enlightenment and Propaganda
overflow Mondex Corporation
overflow Moses and His Ethiopian Wife Zipporah
overflow Munich Central Collecting Point
overflow Musées nationaux récupération
overflow Leonardus Nardus
overflow Fritz Nathan
overflow La Négresse (Manet)
overflow Rosa Oppenheimer
overflow Othello (Corinth)
overflow The Oyster Meal
overflow Portrait of a Lady (Ceruti)
overflow Portrait of a Young Man (Raphael)
overflow Portrait of Adele Bloch-Bauer I
overflow Gustav Rochlitz
overflow Self-Portrait as a Soldier
overflow Shepherdess Bringing in Sheep
overflow Stańczyk (painting)
overflow Swamp Legend
overflow Taganrog Museum of Art
overflow Two Riders on the Beach
overflow Villa R
overflow Hermann Voss (art historian)
overflow Walter Bornheim
overflow Washington Principles on Nazi-Confiscated Art
overflow Water Serpents II
overflow Adolf Weinmüller
overflow Walter Westfeld
overflow Frederic Wolff-Knize
overflow Category:Degenerate Art exhibition
overflow Category:Subjects of Nazi art appropriations
overflow Albinea Madonna
overflow Allegory of Waterloo
overflow The Assassination of Saint Peter Martyr (Titian)
overflow Azuchi Screens
overflow Bathers (Metzinger)
overflow The Battle of Anghiari (Leonardo)
overflow Battle of Cascina (Michelangelo)
overflow Blowing from Guns in British India
overflow Boy Bitten by a Crayfish
overflow Calvary (Amstel)
overflow Image of Camuliana
overflow The Captive King
overflow Casalmaggiore Madonna
overflow A Cavalier
overflow Chez Tortoni
overflow Choir of San Lorenzo
overflow Christ on the Mount of Olives (Caravaggio)
overflow La Circassienne au Bain
overflow The Concert (Vermeer)
overflow The Conversion of Saint Paul (Rubens, Berlin)
overflow Danaë (Annibale Carracci)
overflow Daphne and Chloe
overflow The Death of Saint Francis
overflow Descent into Limbo (Mantegna)
overflow Don Juan and the Commendatore
overflow La Dormeuse de Naples (painting)
overflow The Education of Pan
overflow Eleven Caesars
overflow En Canot
overflow The Enchanted Pose
overflow The Feast of the Gods (van Bijlert)
overflow The Finding of Moses (Veronese, Smith collection)
overflow George III and the Prince of Wales Reviewing Troops
overflow Gorilla in a Pink Mask
overflow Great Daruma
overflow The Harbor
overflow A Harlot's Progress
overflow Heller Altarpiece
overflow Portrait of Henry VIII
overflow Her Majesty Queen Elizabeth II – An 80th Birthday Portrait
overflow Hermit of Tong
overflow History of Snow Hill
overflow The Holy Infants Embracing
overflow In the Sun (Demetrio Cosola)
overflow The Just Judges
overflow The Justice of Trajan and Herkinbald
overflow Klimt University of Vienna Ceiling Paintings
overflow A Lady and Gentleman in Black
overflow Lamentation (Annibale Carracci)
overflow Landscape with Obelisk
overflow The Last Moments of Michel Lepeletier
overflow The Laundress (Chardin)
overflow Leda and the Swan (Leonardo)
overflow Leda and the Swan (Michelangelo)
overflow Madonna and Child with the Infant Saint John the Baptist (Leonardo)
overflow Madonna of Nicolas van Maelbeke
overflow Magdalen in the Desert
overflow Magistrates of Brussels
overflow Man at the Crossroads
overflow Man with a Pipe
overflow Medusa (Leonardo)
overflow Memory (Millais painting)
overflow Miss Nightingale at Scutari, 1854
overflow Sir Thomas More and Family
overflow Murals from the Christian temple at Qocho
overflow Nightmare of 1934
overflow Nu à la cheminée
overflow The Nursery (Gerard Dou)
overflow Our Lady Derzhavnaya
overflow Our Lady of Kazan
overflow Packy mural
overflow The Painter on the Road to Tarascon
overflow Portrait of a Courtesan (Caravaggio)
overflow Portrait of a Young Man (Raphael)
overflow Portrait of Alfonso I d'Este
overflow Portrait of Empress Eugénie
overflow Portrait of George Dyer and Lucian Freud
overflow Lost portrait of George Villiers, 1st Duke of Buckingham
overflow Portrait of Isabella of Portugal (van Eyck)
overflow Portrait of Napoleon III (Winterhalter)
overflow Portrait of Philip the Good (van der Weyden)
overflow Portrait of Winston Churchill (Sutherland)
overflow Prague Altarpiece of Lucas Cranach the Elder
overflow Prometheus Unbound (Carl Bloch)
overflow Psyche (painting)
overflow Pulp Fiction (Banksy)
overflow The Reaper (Miró)
overflow Reception of the American Loyalists by Great Britain in the Year 1783
overflow Saint Dominic in Soriano
overflow Saint Gregory at Prayer
overflow Saint James Led to His Execution
overflow Saint John Fleeing Christ's Arrest
overflow Saint Matthew and the Angel
already visited Saint Sebastian (Ribera, Berlin)
overflow Schloss Immendorf
overflow Schubert at the Piano
overflow Seifuku no Shōjo
overflow Sleeping Lady with Black Vase
overflow Still Life with Candlestick
overflow Still Life: Vase with Oleanders
overflow The Stone Breakers
overflow The Storm on the Sea of Galilee
overflow Strolling Actresses Dressing in a Barn
overflow The Subsiding of the Waters of the Deluge
overflow Supreme Meeting
overflow The Prime of Greece
overflow Thirteen Most Wanted Men
overflow Three Figures near a Canal with Windmill
overflow The Tower of Babel (Bruegel)
overflow The Tower of Blue Horses
overflow The Trench (Dix)
overflow Tulip Hysteria Co-ordinating
overflow Two Laughing Boys with a Mug of Beer
overflow Ugui (portrait)
overflow Valley with Ploughman Seen from Above
overflow View of Auvers-sur-Oise
overflow Virgin and Child with Saints (van der Weyden)
overflow Virgin of Mercy (Filippo Lippi)
overflow A Vision of the Last Judgement
overflow Portrait of Phillis Wheatley
overflow A Wind-Beaten Tree
overflow Woman Bathing (van Eyck)
overflow Wooded landscape with gipsies round a camp fire
overflow The Wounded Table
overflow File:Otto Dix - The Trench (Der Schützengraben) 1923.jpg
overflow Alina, a Girl with a Jug
overflow Allegory of the Earth
overflow Beach at Scheveningen in Stormy Weather
overflow Beach in Pourville
overflow Ben Enwonwu's Daily Mirror sculptures
overflow The Boy in the Red Vest
overflow Byzantine Fresco Chapel
overflow Cartel de Don Juan Tenorio
overflow Les Choristes
overflow La Coiffeuse
overflow Congregation Leaving the Reformed Church in Nuenen
overflow Crown of Empress Eugénie
overflow Descent into Limbo (Mantegna)
overflow Dr. Samuel Mitchel Smith and Sons Memorial Fountain
overflow Dutchy (statue)
overflow El Perú Libre
overflow Ernest Rutherford memorial
overflow Flaming June
overflow Florentine Diamond
overflow The Gardener (Van Gogh)
overflow Gather Ye Rosebuds While Ye May (Waterhouse painting 1909)
overflow Girl with Balloon
overflow The Guitar Player (Vermeer)
overflow Helmet of Coțofenești
overflow Horses in Landscape
overflow Hymen, oh Hyménée!
overflow Impression, Sunrise
overflow Jacqueline (painting)
overflow Jewess with Oranges
overflow Lady Writing a Letter with her Maid
overflow The Last Judgment (Memling)
overflow Los funerales de Atahualpa
overflow Love and Pain (Munch)
overflow Count Lepic and His Daughters
overflow Madonna (Munch)
overflow Matuatonga
overflow Maya with Doll
overflow The Miracle of the Desecrated Host
overflow The Mocking of Christ (Cimabue)
overflow Mojave Memorial Cross
overflow Mona Lisa
overflow A Negress
overflow Our Lady of Porta Vaga
overflow The Parsonage Garden at Nuenen
overflow The Pioneer (Los Angeles)

In [ ]:
len(pages_db)

In [ ]:
footprint

## Cleaning

In [ ]:
load_progress()

--- Progress Loaded from Checkpoint ---

In [ ]:
cleaning_pages_db = pages_db.copy()

In [ ]:
len(pages_db)

2474

In [ ]:
df_footprint = pd.DataFrame(footprint, columns=['Curr Title', 'Origin', 'Action', 'Depth'])

In [ ]:
df_footprint['Action'].unique()

array(['crawl', 'category', 'see also', 'list unsolved',
       'list not unsolved-manual_inspect', 'overflow'], dtype=object)

In [ ]:
df_crawled = df_footprint[df_footprint['Action']=='crawl']

In [ ]:
df_crawled['Origin'].unique()

array(['seed', 'Category:Unsolved crimes',
       'Category:Unsolved crimes by continent',
       'Category:Unsolved crimes by country', 'Category:Unsolved arsons',
       'Category:Unidentified criminals', 'Category:Unsolved murders',
       'Category:Terrorist incidents by unknown perpetrators',
       'Category:Works about unsolved crimes',
       'Category:Missing person cases by continent',
       'Category:Unsolved murders by continent',
       'Category:Unsolved crimes in Europe',
       'Category:Unsolved murders by country',
       'Category:Unsolved crimes in Angola',
       'Category:Unsolved crimes in Australia',
       'Category:Unsolved crimes in Belize',
       'Category:Unsolved crimes in Brazil',
       'Category:Unsolved crimes in Cambodia',
       'Category:Unsolved crimes in Canada',
       'Category:Unsolved crimes in China',
       'Category:Unsolved crimes in Costa Rica',
       'Category:Unsolved crimes in France',
       'Category:Unsolved crimes in Germany',
       'Category:Unsolved crimes in India',
       'Category:Unsolved crimes in Iraq',
       'Category:Unsolved crimes in Ireland',
       'Category:Unsolved crimes in Israel',
       'Category:Unsolved crimes in Italy',
       'Category:Unsolved crimes in Japan',
       'Category:Unsolved crimes in Mexico',
       'Category:Unsolved crimes in the Netherlands',
       'Category:Unsolved crimes in Nicaragua',
       'Category:Unsolved crimes in Nigeria',
       'Category:Unsolved crimes in Pakistan',
       'Category:Unsolved crimes in the Philippines',
       'Category:Unsolved crimes in Portugal',
       'Category:Unsolved crimes in Somalia',
       'Category:Unsolved crimes in South Africa',
       'Category:Unsolved crimes in Spain',
       'Category:Unsolved crimes in Sri Lanka',
       'Category:Unsolved crimes in Thailand',
       'Category:Unsolved crimes in the United Kingdom',
       'Category:Unsolved crimes in the United States',
       'Category:Unidentified criminals by nationality',
       'Category:Unidentified murderers', 'Category:Unidentified rapists',
       'List of unsolved murders (1900–1979)',
       'List of unsolved murders (1980–1999)',
       'List of unsolved murders (2000–present)',
       'List of unsolved murders (before 1900)',
       'Lists of unsolved murders', 'Category:Unsolved mass murders',
       'Category:Unidentified murder victims',
       'Category:Unsolved airliner bombings',
       'Category:2007 Samjhauta Express bombings',
       'Category:Works about unsolved murders in the United States',
       'Category:Unexplained_disappearances',
       'Category:Lists of unexplained disappearances',
       'Category:Aerial disappearances', 'Category:Bermuda Triangle',
       'Category:Mass disappearances', 'Category:Lost objects',
       'Category:Missing people', 'Category:Missing vehicles',
       'Category:Lists of missing people', 'Category:Missing aircraft',
       'Category:Missing aviators',
       'Category:Aerial disappearances of military personnel in action',
       'Category:Missing air passengers',
       'Category:Bermuda Triangle in fiction',
       'Category:Books about the Bermuda Triangle',
       'Category:Mary Celeste', 'Category:Missing ships',
       'Category:Lost astronomical objects',
       'Category:Lost buildings and structures',
       'Category:Lost works of art',
       'Category:Lost and extinct musical instruments',
       'Category:Lost specimens',
       'Category:Missing person cases by location',
       'Category:Missing person cases by nationality',
       'Category:Missing person cases by occupation',
       'Category:Missing person cases by period',
       'Category:Formerly missing people',
       'Category:Missing people activists', 'Category:Search and rescue',
       'Category:Works about missing people', 'Category:Castaways',
       'Category:Missing children',
       'Category:People declared dead in absentia',
       'Category:Enforced disappearances',
       'Category:Missing people identified through genetic genealogy',
       'Category:People lost at sea',
       'Category:Wikipedia images of missing people',
       'Category:Missing trains'], dtype=object)

In [ ]:
len(cleaning_pages_db)

2114

In [ ]:
erased_title = []

In [ ]:
erased_title[-10:]

['Monumento a los Niños Héroes (Guadalajara)',
 'Paine Memorial',
 'The Perils of Penelope',
 'Pig Girl',
 'Runaway Train (Soul Asylum song)',
 'Sabrina (comics)',
 'Something Is Killing the Children',
 'The Vanished (podcast)',
 'Walking With Our Sisters',
 "Zahra's Paradise"]

In [ ]:
banned_cat = ['Category:Works about the Black Dahlia case','Category:Works about Tupac Shakur','Category:Works about unsolved murders in the United States',
              'Category:Non-fiction books about unsolved murders in the United States','Category:2007 Samjhauta Express bombings','Category:Formerly missing people',
              'Category:Formerly missing people by nationality','Category:Deaths in the Titan submersible implosion','Category:Missing people identified through genetic genealogy',
              'Category:Lost specimens','Category:Bermuda Triangle in fiction','Category:Works set in the Bermuda Triangle','Category:Films set in the Bermuda Triangle',
              'Category:Novels set in the Bermuda Triangle', 'Category:Television episodes set in the Bermuda Triangle', 'Category:Television shows set in the Bermuda Triangle',
              'Category:Video games set in the Bermuda Triangle','Category:Books about the Bermuda Triangle','Category:Mary Celeste','Category:Lost astronomical objects',
              'Category:Lost comets','Category:Lost minor planets','Category:Lost moons','Category:Recovered astronomical objects','Category:Works about missing people',
              'Category:Films about missing people','Category:Novels about missing people','Category:Short stories about missing people','Category:Television series about missing people',
              'Category:Video games about missing people','Category:Documentaries about missing people','Category:Search and rescue','Category:Search and rescue helicopters',
              'Category:Search and rescue dogs','Category:Search patterns','Category:Castaways','Category:Fictional castaways','Category:Fiction about castaways',
              'Category:Fictional characters incorrectly presumed dead','Category:Murder convictions without a body'
              ]

In [ ]:
#df_crawled['Origin']
df_works_unsolved_crimes = filter_dataframe(df_footprint, {'Origin':['Category:People lost at sea']})
df_works_unsolved_crimes

,Curr Title,Origin,Action,Depth
12786,List of people who disappeared mysteriously at...,Category:People lost at sea,category,3
12787,1957 Pacific Ocean Boeing C-97 disappearance,Category:People lost at sea,category,3
12788,2008 disappearance of CIA operatives in the So...,Category:People lost at sea,category,3
12789,2019 English Channel Piper PA-46 crash,Category:People lost at sea,category,3
12790,Aagtekerke (1724),Category:People lost at sea,category,3
...,...,...,...,...
19114,John Yarnall,Category:People lost at sea,crawl,3
19116,Yong Yu Sing No. 18,Category:People lost at sea,crawl,3
19119,John Young (naval officer),Category:People lost at sea,crawl,3
19121,Lamont Young,Category:People lost at sea,crawl,3
19123,Erwin von Zach,Category:People lost at sea,crawl,3

In [ ]:
page_banned = list(df_works_unsolved_crimes['Curr Title'].unique())
for title in page_banned:
  if 'Category:' in title:
    print(title)

Category:Fictional characters incorrectly presumed dead
Category:Murder convictions without a body

In [ ]:
page_banned = list(df_works_unsolved_crimes['Curr Title'].unique())
for title in page_banned:
  print(title)
  if 'Category:' in title:
    print("category")
  else:
    _ = cleaning_pages_db.pop(title,None)
    erased_title.append(title)

In [ ]:
TEXT_LIMIT = None  # Set to a number (e.g., 500) or None for full text
WAIT_RANGE = (1, 3)
BATCH_SIZE = 4
MAX_DEPTH = 3
SAVEFILE_DIR = "/content/drive/MyDrive/Mystery Search Engine/"
# Main Databases
pages_db = {}
crawl_errors = {} # Error tracking: stores {title: {"type": "image|metadata|infobox", "error": "msg"}}

# Queues & Tracking
wikipedia_queue = deque([("Category:Unsolved crimes",0,"seed")])
external_links_queue = set()
visited_pages = set()
manual_inspection_bucket = set()
overflow = set()
footprint = []

pages_with_tables = []  # Stores (Title, URL)
see_also_title = set()     # Stores potential new Case Titles

In [ ]:
see_also_title

{'American literature in Spanish',
 'Crime in Georgia (U.S. state)',
 'List of pioneers in computer science',
 '2013 Neo Irakleio Golden Dawn office shooting',
 'Crime in North Carolina',
 'Crime in Western Australia',
 'Kingdom of Galicia–Volhynia',
 'Trial of Yolanda Saldívar',
 'James Randi',
 'Lyle Stevik',
 'Ignacio Ellacuría',
 'Death of David Glenn Lewis',
 'List of American independent films',
 'Abahlali baseMjondolo',
 'Significant acts of violence against LGBT people',
 'Domestic terrorism in the United States',
 'List of people from Massachusetts',
 'Tim Vakoc',
 'Lyre',
 'Pavel Sheremet',
 'Terrorism in the Philippines',
 'Francesca Mambro',
 'Misa Campesina Nicaragüense',
 'Sydney gangland war',
 'Josephus',
 'Frederick Forsyth',
 'Extrajudicial killings and forced disappearances in the Philippines',
 'Prostitution in Germany',
 'Memoir',
 'Ciudad Juárez',
 'Sri Lanka',
 'Yvan Leyvraz',
 'List of suffragists and suffragettes',
 'List of missing aircraft',
 'St.Phillip Neri church bombing',
 'Soccer mom',
 'Women in Pakistan',
 'Glossary of nautical terms (M-Z)',
 'Polly Klaas Foundation',
 'Strategy of tension',
 'Seebrücke',
 'Cold War',
 'List of opponents of slavery',
 'Playboy Playmate',
 'Art in Nazi Germany',
 'Corky Row Historic District',
 'Pol Pot',
 'Robert Nairac',
 'List of unsolved murders in Australia',
 'List of suicides (N–Z)',
 'Indians in the New York City metropolitan area',
 'Las Vegas Metropolitan Police Department',
 'Lynching in the United States',
 'Marium Mukhtiar',
 'Backpacker murders',
 'Pasteur - AMIA (Buenos Aires Underground)',
 'Death of Lim Shiow Rong',
 'Oak Island Money Pit',
 'Earl Kitchener',
 'Argentina',
 'Disappearance of Tara Grinstead',
 'Jamshid Sharmahd',
 'Kitchener, Ontario',
 'List of people who disappeared mysteriously',
 'Censorship in the United States',
 'Iraq',
 'Union of Lublin',
 'Boeing 727',
 'Sea-Eye',
 'Terrorism in New Zealand',
 'Alexander Shchetinin',
 'Charlotte de Berry',
 'Killing of Henryk Siwiak',
 'Saffron terror',
 'Johal',
 'Alfred Joseph Richards',
 'Ernest E. Debs',
 'Disappearance of Peter Wilson',
 'Murder of Amy Mihaljevic',
 'Media of Myanmar',
 'List of terrorist incidents, 2009',
 'Killing of Chantel Moore',
 'Missing and Murdered Indigenous Women',
 'Casualties of the September 11 attacks',
 'Dublin',
 'Arklow',
 'Massachusetts',
 'Aviation Survival Technician',
 'Death of Winnifred Teo',
 'Crime in Melbourne',
 'The Holocaust',
 'List of fugitives from justice who disappeared',
 'List of Major League Baseball batting champions',
 'List of Medal of Honor recipients for World War II',
 'Misconduct in the Las Vegas Metropolitan Police Department',
 'Nurin Jazlin',
 'Widji Thukul',
 'List of Unsolved Mysteries episodes',
 'Missouri',
 'List of deaths on eight-thousanders',
 'Vladislav Listyev',
 'Axe',
 'Garud Commando Force',
 'Podcast',
 'Ishi',
 'Iraqi Kurdistan',
 'Cihu Mausoleum',
 'List of massacres in Mexico',
 'Alas Chiricanas Flight 901',
 'Guesthouses of Chiang Kai-shek',
 'Dresden Green Vault burglary',
 'Crime in Canada',
 'Terrorism',
 'Antisemitism in Germany',
 'Trespasser',
 'Assassination of Anna Politkovskaya',
 'LIAT Flight 319',
 'Timeline of the Mexican drug war',
 'Submarine escape training facility',
 'Ebbe Carlsson affair',
 '2016 Atatürk Airport attack',
 'Jorge Eliecer Gaitán',
 'List of riots',
 'Filiberto Ojeda Rios',
 'Sri Lanka and state terrorism',
 'List of death row inmates in the United States',
 'Murder of Emma Grace Cole',
 'Homeless',
 'List of terrorist incidents in 2015',
 'Little Lord Fauntleroy (murder victim)',
 'Hatton Garden safe deposit burglary',
 'Alexander Selkirk',
 'Siberian Ice Maiden',
 'List of people assassinated in Africa',
 'Łapanka',
 'Baqubah',
 'Crime in Oklahoma',
 '2007 Samjhauta Express bombings',
 'Amber Room',
 'Rubens Paiva',
 'List of aviation accidents and incidents with a sole survivor',
 'Grandmothers of Plaza de Mayo',
 'List of heists in the United Kingdom',
 '2015 Chapel Hill shooting',
 'On the Waterfront',
 'List of solved missing person cases (2020s)',
 'Bermuda Triangle',
 'List of aircraft hijackings',
 'Gerrit van der Waals',
 'Dendera light',
 'Indonesian mass killings of 1965–66',
 'London',
 'List of Antarctic exploration ships from the Heroic Age, 1897–1922',
 'Nazi Party',
 'Juan Pablo Mohr Prieto',
 'Media feeding frenzy',
 'Humaira Asghar',
 'Naxal',
 '2010 in literature',
 'Clarisse Crémer',
 'Missing and murdered Indigenous women',
 'Death Row Records',
 'Roman Catholicism in Yemen',
 'Lake Bodom (film)',
 'Great Britain in the Seven Years War',
 'Vorbunker',
 "Independent Commission for the Location of Victims' Remains",
 'Whites in South Africa',
 'Silk–Miller police murders',
 'Brazil',
 'John Cannan',
 'Washington, D.C.',
 'James Randi Educational Foundation',
 'Jouhikko',
 'Palmer Raids',
 'Anglo-Egyptian conquest of Sudan',
 'Personal locator beacon',
 'International Life Saving Federation',
 'Halabja massacre',
 'Politics of Chechnya',
 'Snow coach',
 'Engenheiro Rubens Paiva Station',
 'Murders of Antonio Maso and Mariarosa Tessari',
 'Lubang Island',
 'Murder of Ashley Ann Olsen',
 'Uxoricide',
 '1998 Wandhama massacre',
 'China',
 'Police diving',
 'Baroda dynamite case',
 'Dogfights (TV series)',
 'Mocímboa da Praia offensive',
 'Dembei',
 'Oklahoma',
 'Sandinista',
 'Petra Procházková',
 '2017 Sydney Seaplanes DHC-2 crash',
 'Female guards in Nazi concentration camps',
 'List of terrorist incidents in 1975',
 'Disappearance of Rebecca Coriam',
 'James Reeb',
 "Kitchener's Army",
 'US Marine',
 'Yazidis',
 'Ketron Island',
 'List of unusual deaths in the 21st century',
 'Napoleón Macías',
 'MV Tyrronall',
 'The War on Democracy',
 'Kadyrovites',
 'Jewish-American organized crime',
 'Death of Chow Tsz-lok',
 'List of assassinated persons',
 'San Telmo (ship)',
 'Deaths due to the Chernobyl disaster',
 'Sicilian Mafia',
 'Modernisme',
 '1937 in China',
 'Wall Street bombing',
 'Ig Nobel',
 'Organized crime',
 'Billy the Axeman',
 'List of American football players who died during their careers',
 'Origin of the harp in Europe',
 'Union Navy',
 'The Story of Troy',
 'List of United States crime-related lists',
 'Piast dynasty',
 'List of peace activists',
 'List of solved missing person cases: 1950–1999',
 'Digital preservation',
 'List of Victorian Football League players who died on active service',
 'Guatemalan Civil War',
 'Pool of Siloam',
 'Philadelphia crime family',
 'List of Medal of Honor recipients for World War I',
 'Zodiac Killer',
 'Jane Goodall',
 'Spanish Navy',
 'Incidents at Walt Disney World',
 'List of incidents of political violence in Washington, D.C.',
 'Aum Shinrikyo',
 'Richard Rich, 1st Baron Rich',
 'Alfonso Navarro',
 'History of Kentucky',
 'White Terror (Spain)',
 'Poisoning of Sergei and Yulia Skripal',
 'King',
 'Pirate television',
 'Music of Ireland',
 'Murder of Marie Wilks',
 'History of the internal combustion engine',
 'List of heads of state and government who were assassinated or executed',
 'Highway of Tears murders',
 'Olivier de Kersauson',
 'Zachistka',
 'List of kidnappings (1900–1949)',
 'Alcàsser Girls',
 'Human rights',
 'New Zealand',
 'Hinterkaifeck murders',
 'Mexico',
 'List of rail accidents (1900–1909)',
 'List of satirists and satires',
 'Unit 5101',
 'List of artists who reached number one in the United States',
 'Gilgo Beach serial killings',
 'Death',
 'On the Art of the Cinema',
 'List of terrorist incidents',
 'Cleveland Torso Murderer',
 'Appalachian Spring',
 'Emmett Till',
 'Leaderless resistance',
 'Timeline of violent incidents at the United States Capitol',
 'Disappearance of Michele Anne Harris',
 'List of stolen paintings',
 'Matías Pérez (balloonist)',
 'Eight Immortals Restaurant murders',
 'List of American Football League players',
 'Philadelphia Experiment',
 'Deerfield Academy',
 'POW/MIA',
 'Cairo',
 'Ambassadors of the United States',
 'Maryknoll',
 'Karl Maria Wiligut',
 'Politics of Indonesia',
 'Frankfurt',
 'Lucia de Berk',
 'Disappearance of Ben McDaniel',
 'Alexander I of Russia',
 'History of chemical warfare',
 'Grigory Shelikhov',
 'Gwynns Falls/Leakin Park',
 'Operation Exodus (WWII operation)',
 'List of journalists killed in the United States',
 'Colombian Liberal Party',
 'Killings of Nick Spanos and Stephen Melrose',
 'Tanaka Shōsuke',
 'Residences of North Korean leaders',
 'Canada',
 'Wembley Point Woman',
 'Democracy in India',
 'Unit 669',
 '2018 United States mail bombing attempts',
 'Death of Tamla Horsford',
 'Prasun Mukherjee',
 'Capital punishment in California',
 'Štěchovice treasure',
 'Nazi crimes against the Polish nation',
 'Sennichi Department Store Building fire',
 'List of homicides in Michigan',
 'Arthur Allan Thomas',
 'Kyllikki Saari',
 'Chiang Kai-shek Memorial Song',
 'List of terrorist incidents, 2010',
 'Ben Linder',
 'Right-wing terrorism',
 'Frances Wilson Grayson',
 'Human rights in Kazakhstan',
 'Animal-borne bomb attacks',
 'Death of Elisa Lam',
 'Western Australia',
 'List of terrorist incidents involving railway systems',
 'List of accidents and incidents involving the Douglas DC-4',
 'Khairlanji massacre',
 'Ski patrol',
 'List of ocean liners',
 'List of assassinated American politicians',
 'Húsafell Stone',
 'List of plates (Latter Day Saint movement)',
 'Kampfretter',
 'Cambodia',
 'Civil defense in Russia',
 'Crime in Washington, D.C.',
 'Black September',
 'Upali Newspapers',
 'Cold case',
 'Dubai',
 'Río de Oro',
 'List of massacres during the Syrian civil war',
 'Maurice and Maralyn Bailey',
 'Reda Helal',
 'Brussels',
 'Strait of Magellan',
 'Cypress of Kashmar',
 'Homelessness among LGBT youth in the United States',
 'Lists of victims of the September 11 attacks',
 'Baker Street robbery',
 'List of victims of the Sicilian Mafia',
 'Dynasty',
 'Para-SAR',
 'Prostitution in Australia',
 'Crime in Los Angeles',
 'Pollinator decline',
 'Daily News (Perth, Western Australia)',
 'Al-Kazimiyya Mosque',
 'List of serial killers before 1900',
 'List of harmonica blues musicians',
 'Houtman Abrolhos',
 'History of religious Jewish music',
 'Violence against women in Mexico',
 'Disappearance of Mary Boyle',
 'Skirmish at Waters Creek',
 '1951 Atlantic C-124 disappearance',
 'Braemar Hill murders',
 'Japanese in Chicago',
 'Crime in Colorado',
 'Political assassinations in post-apartheid South Africa',
 'South Africa',
 'History of the Jews in Argentina',
 'Reformed Egyptian',
 'Melbourne',
 '1966 theft of the Jules Rimet Trophy',
 'First Indochina War',
 'Centre for Integrative Bee Research',
 'Decennial Air Cruise',
 'Snowcat',
 'List of artifacts in biblical archaeology',
 'Thomas Cletcher',
 'Air-sea rescue',
 'Crash boats of World War 2',
 'Terrorism in Kashmir',
 'Puerto Rico',
 'List of World War II flying aces',
 'Kenya',
 "Causey's Mill",
 'Surjit Athwal',
 'Psaltery',
 'Jacobo Timerman',
 'Human rights in Sri Lanka',
 'United States Lifesaving Association',
 'Murders of Jacqueline Ansell-Lamb and Barbara Mayo',
 'Visa requirements for Sri Lankan citizens',
 'Murder of Thomas Oliver',
 'Simon Dutton (drug dealer)',
 'Unsolved Mysteries',
 'Role of music in World War II',
 'List of people killed by and disappeared during the Brazilian military dictatorship',
 'Code Adam',
 'Modernist poetry',
 'List of diamonds',
 'List of ships captured in the 18th century',
 'President of the Republic of China',
 'Dupont de Ligonnès murders and disappearance',
 'Clavering baronets',
 '2003 ricin letters',
 'List of aviation awards',
 'Spitsbergen Airship Museum',
 'Overland Park Jewish Community Center shooting',
 'Shannon Richardson',
 'Pidyon Shvuyim',
 'Commission of Inquiry into the 2024 Chikangawa (Nthungwa) aircraft accident',
 'Georgiy Gongadze',
 'Ostracism',
 'Rescue',
 'Murder of Holly Bobo',
 'Rich family',
 'List of drowning victims',
 'List of massacres in Timor-Leste',
 'Gus Courts',
 'Police misconduct',
 'Haiti',
 'Japan Rugby Football Union',
 'Ottoman Navy',
 '2026 attack on Israeli consulate in Turkey',
 'List of bank robbers and robberies',
 'Murders of Pamela Buckley and James Freund',
 'Bass Strait Triangle',
 'South Street Seaport',
 'Papua conflict',
 'Christians',
 'Slavery in Syria',
 'Cluster ballooning',
 'Familicide',
 'Lillehammer affair',
 'Ray Gricar',
 'Frontex',
 'Joseph Newton Chandler III',
 'Rio de Janeiro',
 'List of destroyed libraries',
 'Murder of Carolyn Eaton',
 'Moriyama Einosuke',
 '1984 Rajneeshee bioterror attack',
 'List of U.S. Navy losses in World War II',
 'Nokuthula Mabaso',
 'Anne Pressly',
 'Chile under Pinochet',
 'Shirley Brifman',
 'Murder of Daniel Morcombe',
 'David Frankfurter',
 '2011 Imbaba Church Attacks',
 'Age of Discovery',
 'List of people who disappeared at sea',
 'Texas',
 'Richard Raymond Willis',
 '2011 Minsk Metro bombing',
 'List of attacks against Israeli embassies and diplomats',
 'History of East Timor',
 'Georgia Tech Yellow Jackets football',
 'List of hoards in Romania',
 '2016 Al-Kazimiyya Mosque bombing',
 'List of German inventors and discoverers',
 'Southern Tagalog 10',
 'Istanbul',
 'Berlitz International',
 'Lyres of Ur',
 'LGBT in Islam',
 'List of Medal of Honor recipients during peacetime',
 'Donroe Doctrine',
 'List of ongoing armed conflicts',
 'Mannan family terrorist cell',
 'French Air Force',
 'Lithuania',
 'Chilean transition to democracy',
 'The Tuskegee Airmen',
 'List of UFO sightings',
 'Operation Charly',
 'Ichi Orihara',
 'Staro Gracko massacre',
 "National Missing Children's Day",
 'Anti-Canadian sentiment',
 "Mattie's Call",
 'Mariticide',
 'Pan Am Flight 103',
 'Murder of Carol Cole',
 'Samvidhaan Hatya Diwas',
 'St Nazaire raid',
 'Nathaniel Rich (soldier)',
 'Taghi Rastegar Moghadam',
 'Babbar Khalsa',
 'List of unsolved murders (2000–present)',
 'Ibrahim Metwaly',
 'Coronation of the Bulgarian monarch',
 'Cleopatra',
 'List of submarine incidents since 2000',
 'Capital punishment in South Dakota',
 'Cambodian genocide denial',
 'Deaths in September 2012',
 'List of Medal of Honor recipients',
 'Princess Elisabeth of Hesse and by Rhine',
 'Tourism in Canada',
 'List of fatalities from aviation accidents',
 'William Kenealy',
 'Smart grid',
 'Luftwaffe',
 'Mean world syndrome',
 'List of unsolved murders in Canada',
 'Yuba County Five',
 'Copts',
 'List of Medal of Honor recipients (Veracruz)',
 'Personal standard of Adolf Hitler',
 'Sanemon',
 'Springfield Three',
 'History of ancient Israel and Judah',
 'Occupation of Czechoslovakia (1938–1945)',
 '1956 Atlantic R6D-1 disappearance',
 'Crime in San Francisco',
 'Hofstadter Committee',
 'Bombardier Dash 8',
 'Vladimir Herzog',
 'Life of Pi',
 'Lizzie Borden',
 'List of homicides in Nevada',
 'Murder of Sheila Anderson',
 'International Search and Rescue Competition',
 'Japan',
 'Antwerp diamond heist',
 'Spanish–American War',
 'Freeman family murders',
 'Pilgrim Fathers',
 'Paul Vanden Boeynants',
 'South Korea',
 'List of people on the postage stamps of Ireland',
 'List of members of the American Legion',
 'Manureva',
 'List of solved missing person cases: post–2000',
 'Chemical attack on Behbahan battalion',
 'Femicide in Latin America',
 'Index of Bermuda-related articles',
 'List of unrecovered flight recorders',
 'Individuals and groups assisting Jews during the Holocaust',
 'Wilhelm Herget',
 'Alexei Navalny',
 'Timeline of the colonization of North America',
 'Pukekawa',
 'Titouan Lamazou',
 'History of Beijing',
 'Forced religious conversion',
 'List of Deerfield Academy alumni',
 'Cospas-Sarsat',
 'Kabul',
 'Panorama',
 'God complex',
 'Human rights in Brazil',
 'Duma',
 'List of female explorers and travelers',
 '2010 Times Square car bomb attempt',
 'Rawalpindi',
 'Crime in Utah',
 'Terrorist incidents in Iraq in 2010',
 'Casualties of the Syrian civil war',
 'Ardenwald axe murders',
 'List of executions in Japan',
 'Lake Bodom',
 'California',
 'Censorship in Myanmar',
 'Nicky Verstappen',
 'List of wars involving Mozambique',
 'Turkification',
 'Assassination of Liaquat Ali Khan',
 '2014 Kafr Zita chemical attack',
 'Crime in Japan',
 'Kim Hyon-hui',
 'Waseda University',
 'Missing and murdered indigenous women',
 'Murder of Jaidyn Leskie',
 'Libyan Desert',
 "1982 Spanish coup d'état attempt",
 'Reefer ship',
 "I Was Lord Kitchener's Valet",
 'Green Resistance',
 'Jacob DeShazer',
 'Constitution of Mexico',
 'Alaska',
 'Peter Bergmann case',
 'Shimazu Nariakira',
 'Sombath Somphone',
 'Wisconsin',
 'Murder of Carolanne Jackson',
 'Algeria',
 'List of attacks on legislatures',
 'Japanese people in Russia',
 'Beothuk',
 'Nikolai Rezanov',
 'Residential school denialism',
 'List of kidnappings (1980–1989)',
 'List of serial killers in South Africa',
 'List of cases of police brutality in Belize',
 'Slavery in Saudi Arabia',
 'Oven homicide',
 'SS Baychimo',
 'Crime in Indonesia',
 'Cameroon',
 'Chewbacca defense',
 'Executive Order 9981',
 'Lost artworks',
 'Christine Keeler',
 'Air Vietnam Flight 706',
 'Peshawar',
 'Military history of African Americans',
 'List of World War I flying aces from the United States',
 'List of Medal of Honor recipients for the Spanish–American War',
 'Assassination',
 'History of Italian Americans in Philadelphia',
 'List of authors in war',
 'Deaths in July 2013',
 'Kriegsmarine',
 'List of unsolved murders in the United Kingdom',
 'Prostitution',
 'Hitler: The Last Ten Days',
 'Mass graves in Chechnya',
 'Ankara',
 'Death of Cleopatra',
 'Harvard University',
 'South African Air Force',
 'List of kidnappings (2020–present)',
 'Murder of Melanie Hall',
 "Augusto Pinochet's arrest and trial",
 "People's Revolutionary Army (Argentina)",
 'Ukshin Hoti',
 'Minister for Justice Equality and Law Reform v Bailey',
 'Red and Anarchist Skinheads',
 'List of terrorist incidents in Jammu and Kashmir',
 'Harry Pidgeon',
 'William Lewis Moore',
 'Savoia-Marchetti S.55',
 'Sergei Magnitsky',
 '1966 Palomares incident',
 'Monroe Doctrine',
 'Suzanne Sevakis',
 'The Tempest',
 'Lawnchair Larry flight',
 'Confederate gold',
 'Orville Lynn Majors',
 'Malaysia Airlines Flight 370',
 'Douma chemical attack',
 'Baron Rich',
 'Rudolf-Diesel-Medaille',
 'Medal of Honor',
 'Murder of Linda Cook',
 'Republic of Ireland',
 'List of monuments and memorials removed during the George Floyd protests',
 'University of Toronto',
 'LibriVox',
 'Bowraville Murders',
 'List of massacres in India',
 'Clàrsach',
 'Saint Anne',
 'Urengoy–Pomary–Uzhhorod pipeline',
 'Death of William DaShawn Hamilton',
 'List of short-story authors',
 'Declared death in absentia',
 'Gnjilane killings',
 'Southern Cross (aircraft)',
 'Islamic terrorism',
 'Islam in Yemen',
 'Adolf Hitler',
 'List of Bulgarians',
 'List of terrorist incidents in 1972',
 'Lonely hearts killer',
 'Freedom of religion in Yemen',
 "Human rights in Ba'athist Syria",
 'List of best-selling music artists',
 'Murder of Jean McConville',
 'List of American Civil War generals (Confederate)',
 'Death of Linda Chua',
 'Reus',
 'List of accidents and incidents involving commercial aircraft',
 'Domestic violence',
 'Kopasgat',
 'Dougal Robertson',
 'Dr. No (serial killer)',
 'List of ballooning accidents by death toll',
 'North Korea',
 'Tiompan',
 '2018 Horizon Air Q400 incident',
 'The Gentleman of Heligoland',
 'Crime in Singapore',
 'Underwater search and recovery',
 '1980 Paris synagogue bombing',
 'Murder of Marcia Trimble',
 'Chiang Kai-shek statues',
 'Southern Television broadcast interruption',
 'Ayanda Ngila',
 'Boat Race',
 'Boko Haram',
 '2002 Qasim Nagar massacre',
 'List of transgender people',
 "Poor People's Campaign",
 'Joseph Heco',
 'Simon Magus',
 'List of terrorist incidents in June 2018',
 'Heritage conservation in Canada',
 'Political repression in post-apartheid South Africa',
 'Keita Dynasty',
 'Disappearance of Sneha Anne Philip',
 'Assassination of Ismail Haniyeh',
 'Crime in New Zealand',
 'List of unsolved deaths',
 'Yorkshire',
 'Killing of Elza Kungayeva',
 'Coast guard',

In [ ]:
df_banned = filter_dataframe(df_footprint, {'Origin':banned_cat})
banned_titles = df_banned['Curr Title'].unique()

In [ ]:
cleaned_manual_inspection_bucket = [item for item in manual_inspection_bucket if item not in banned_titles]
cleaned_overflow = [item for item in overflow if item not in banned_titles]
cleaned_see_also_title = [item for item in see_also_title if item not in banned_titles]
cleaned_pages_with_tables = [item for item in pages_with_tables if item[0] not in banned_titles]

In [ ]:
for t in banned_titles:
  k = cleaning_pages_db.pop(t,None)
  if not k is None:
    print(k)

{'origin_title': 'Category:Unexplained_disappearances', 'url': 'https://en.wikipedia.org/wiki/Mary_Celeste', 'last_update_text': 'This page was last edited on 18 May 2026, at 05:04(UTC).', 'summary': 'Mary Celeste (, often erroneously referred to as Marie Celeste,) was a Canadian-built, American-registered, merchant brigantine that was discovered adrift and deserted in the Atlantic Ocean off the Azores on December 4, 1872. \nThe Canadian brigantine Dei Gratia found her in a dishevelled but seaworthy condition under partial sail and with her lifeboat missing. The last entry in her log was dated 10 days earlier. She had left New York City for Genoa on November 7 and was still amply provisioned when found. Her cargo of alcohol was intact, and the captain\'s and crew\'s personal belongings were undisturbed. None of those who had been on board were ever seen or heard from again.\nMary Celeste was built in Spencer\'s Island, Nova Scotia, and launched under British registration as Amazon in 1861. She was transferred to American ownership and registration in 1868, when she acquired her new name. Thereafter, she sailed uneventfully until her 1872 voyage. At the salvage hearings in Gibraltar following her recovery, the court\'s officers considered various possibilities of foul play, including mutiny by Mary Celeste\'s crew, piracy by the Dei Gratia crew or others, and conspiracy to carry out insurance or salvage fraud. No convincing evidence supported these theories, but unresolved suspicions led to a relatively low salvage award.\nThe inconclusive nature of the hearings fostered continued speculation as to what had happened to the ship\'s occupants, and the story has repeatedly been complicated by false detail and fantasy. Hypotheses that have been advanced include the effects on the crew of alcohol fumes rising from the cargo, submarine earthquakes, waterspouts, attack by a giant squid, and paranormal intervention.\nAfter the Gibraltar hearings, Mary Celeste continued in service under new owners. In 1885, her captain deliberately wrecked her off the coast of Haiti as part of an attempted insurance fraud. The story of her 1872 abandonment has been recounted and dramatized many times in documentaries, novels, plays, and films, and the name of the ship has become a byword for unexplained desertion. In 1884, Arthur Conan Doyle wrote "J. Habakuk Jephson\'s Statement", a short story based on the mystery. The story\'s popularity led to the spelling becoming more common than the original in everyday use.', 'infobox': {'Name': 'Amazon(1861–1868)Mary Celeste(1869–1885)', 'Port of registry': 'Principally New York or Boston', 'Builder': 'Rebuilt 1872, New York (yard not named)', 'Launched': 'May 18, 1861', 'Fate': 'Deliberately wrecked off the coast of Haiti, 1885', 'Tonnage': '198.42 gross tons as built 1861282.28 gross tons after rebuild 1872', 'Length': '99.3\xa0ft (30.3\xa0m) as built, 103\xa0ft (31\xa0m) after rebuild', 'Beam': '22.5\xa0ft (6.9\xa0m) as built, 25.7\xa0ft (7.8\xa0m) after rebuild', 'Depth': '11.7\xa0ft (3.6\xa0m) as built, 16.2\xa0ft (4.9\xa0m) after rebuild', 'Decks': '1, as built, 2 after rebuild', 'Sail plan': 'Brigantine'}, 'sections_tree': [{'title': 'Early history', 'content': ['The keel of the future Mary Celeste was laid in late 1860 at the shipyard of Joshua Dewis in the village of Spencer\'s Island, on the shores of the Bay of Fundy in Nova Scotia. The ship was constructed of locally felled timber, with two masts, and was rigged as a brigantine; she was carvel-built, the hull planking flush rather than overlapping. She was launched on May 18, 1861, given the name Amazon, and registered at nearby Parrsboro on June 10, 1861. Her registration documents described her as 99.3 feet (30.3 m) in length, 25.5 feet (7.8 m) broad, 11.7 feet (3.6 m) in depth, and of 198.42 gross tonnage. She was owned by a local consortium of nine people, headed by Dewis; among the co-owners was Robert McLellan, the ship\'s first captain.\nFor her maiden voyage in June 1861, Amazon sailed to Five Islands, Nova Scotia, to take on a cargo of timber for passage across the Atlantic to London. After supervising the ship\'s loading, Captain McLellan fell ill; his condition worsened. The Amazon returned to Spencer\'s Island, where McLellan died on June 19. John Nutting Parker took over as captain and resumed the voyage to London, in the course of which Amazon encountered further misadventures. She collided with fishing equipment in the narrows off Eastport, Maine, and after leaving London, ran into and sank a brig in the English Channel.\nParker remained in command for two years, during which Amazon worked mainly in the West Indies trade. She crossed the Atlantic to France in November 1861, and in Marseille was the subject of a painting, possibly by Honoré de Pellegrin, a well-known maritime artist of the Marseilles School. In 1863, Parker was succeeded by William Thompson, who remained in command until 1867. These were quiet years; Amazon\'s mate later recalled, "We went to the West Indies, England, and the Mediterranean—what we call the foreign trade. Not a thing unusual happened." In October 1867, at Cape Breton Island, Amazon was driven ashore in a storm and was so badly damaged that her owners abandoned her as a wreck. On October 15, she was acquired as a derelict by Alexander McBean, of Glace Bay, Nova Scotia.', [{'title': 'Ownership reassignment and name change', 'content': ["Within a month, McBean sold the wreck to a local businessman, who in November 1868 sold it to Richard W. Haines, an American mariner from New York. Haines paid US$1,750 for the wreck and then spent $8,825 restoring it. He made himself her captain, and in December 1868, registered her with the Collector of the Port of New York as an American vessel, under a new name, Mary Celeste.\nIn October 1869, the ship was seized by Haines' creditors and sold to a New York consortium headed by James H. Winchester. During the next three years, the composition of this consortium changed several times, although Winchester retained at least a half-share throughout. No record of Mary Celeste's trading activities during this period have been found. Early in 1872, the ship underwent a major refitting, costing $10,000, which enlarged her considerably. Her length was increased to 103 feet (31 m), her breadth to 25.7 feet (7.8 m) and her depth to 16.2 feet (4.9 m). Among the structural changes, a second deck was added; an inspector's report refers to extensions to the poop deck, new transoms, and the replacement of many timbers. The work increased the ship's displacement to 282.28 tonnes. On October 29, 1872, the consortium was made up of Winchester with six shares and two minor investors with one share apiece; the remaining four of twelve shares were held by the ship's new captain, Benjamin Spooner Briggs."]}, {'title': 'Captain Briggs and crew', 'content': ['Benjamin Briggs was born in Wareham, Massachusetts, on April 24, 1835, one of five sons of sea captain Nathan Briggs. All but one of the sons went to sea, two becoming captains. Benjamin was an observant Christian who read the Bible regularly and often bore witness to his faith at prayer meetings. In 1862, he married his cousin Sarah Elizabeth Cobb, and enjoyed a Mediterranean honeymoon on board his schooner Forest King. Two children were born: Arthur in September 1865 and Sophia Matilda in October 1870.\nBy the time of Sophia\'s birth, Briggs had achieved a high standing within his profession. He considered retiring from the sea to go into business with his seafaring brother Oliver, who had also grown tired of the wandering life. They did not proceed with this project, but each invested his savings in a share of a ship: Oliver invested in Julia A. Hallock and Benjamin in Mary Celeste. In October 1872, Benjamin took command of Mary Celeste for her first voyage following her extensive New York refitting, which was to take her to Genoa in Italy. He arranged for his wife and infant daughter to accompany him, while his school-aged son was left at home in the care of his grandmother.\nBriggs chose the crew for this voyage with care. First mate Albert G. Richardson was married to a niece of Winchester\'s and had sailed under Briggs before. Second mate Andrew Gilling, aged about 25, was born in New York, and was of Danish extraction. The steward, newly married Edward William Head, was signed on with a personal recommendation from Winchester. The four general seamen were Germans from the Frisian Islands (brothers Volkert and Boz Lorenzen), Arian Martens, and Gottlieb Goudschaal. A later testimonial described them as "peaceable and first-class sailors." In a letter to his mother shortly before the voyage, Briggs declared himself eminently satisfied with ship and crew. Sarah Briggs informed her mother that the crew appeared to be quietly capable "... if they continue as they have begun."']}]]}, {'title': 'Abandonment', 'content': ['', [{'title': 'New York', 'content': ['On October 20, 1872, Briggs arrived at Pier 50 on the East River in New York City to supervise the loading of the ship\'s cargo of 1,701 barrels of alcohol; his wife and infant daughter joined him a week later. On Sunday, November 3, Briggs wrote to his mother to say that he intended to leave on Tuesday, adding, "our vessel is in beautiful trim and I hope we shall have a fine passage."\nOn the morning of Tuesday, November 5, Mary Celeste left Pier 50 with Briggs, his wife and daughter, and seven crew members, and moved into New York Harbor. The weather was uncertain, and Briggs decided to wait for better conditions. He anchored the ship just off Staten Island, where Sarah used the delay to send a final letter to her mother-in-law. "Tell Arthur," she wrote, "I make great dependence on the letters I shall get from him, and will try to remember anything that happens on the voyage which he would be pleased to hear." The weather eased two days later, and Mary Celeste left the harbor and entered the Atlantic.\nWhile Mary Celeste prepared to sail, the Canadian brigantine Dei Gratia lay nearby in Hoboken, New Jersey, awaiting a cargo of petroleum destined for Genoa via Gibraltar. Captain David Morehouse and first mate Oliver Deveau were Nova Scotians, both highly experienced and respected seamen. Captains Briggs and Morehouse shared common interests, and some writers think they likely knew each other, if only casually. Some accounts assert that they were close friends who dined together on the evening before Mary Celeste\'s departure, but the evidence for this is limited to a recollection by Morehouse\'s widow 50 years after the event. Dei Gratia departed for Gibraltar on November 15, following the same general route eight days after Mary Celeste.']}, {'title': 'Derelict', 'content': ['Dei Gratia reached a position of 38°20′N 17°15′W, midway between the Azores and the coast of Portugal about 1 pm on Wednesday, December 4, 1872, land time (Thursday, December 5, sea time). Captain Morehouse came on deck, and the helmsman reported a vessel heading unsteadily towards Dei Gratia at a distance around six miles (9.7 km). The ship\'s erratic movements and the odd set of her sails led Morehouse to suspect something was wrong. As the vessel drew close, he could see nobody on deck and received no reply to his signals, so he sent Deveau and second mate John Wright in a ship\'s boat to investigate. The pair established that this was the Mary Celeste by the name on her stern; they then climbed aboard and found the ship deserted. The sails were partly set and in poor condition, some missing altogether, and much of the rigging was damaged, with ropes hanging loosely over the sides. The main hatch cover was secure, but the fore and lazarette hatches were open, their covers beside them on the deck. The ship\'s single lifeboat was a small yawl that had apparently been stowed across the main hatch, but it was missing, while the binnacle housing the ship\'s compass had shifted from its place and its glass cover was broken. About three and a half feet (1.1 m) of water were in the hold, a significant but not alarming amount for a ship of this size. A makeshift sounding rod (a device for measuring the amount of water in the hold) was found abandoned on the deck.\nThey found the ship\'s daily log in the mate\'s cabin, and its final entry was dated at 8 am on November 25, nine days earlier. It recorded Mary Celeste\'s position then as 37°1′N 25°1′W off Santa Maria Island in the Azores, nearly 400 nautical miles (740 km) from the point where Dei Gratia encountered her. Deveau saw that the cabin interiors were wet and untidy from water that entered through doorways and skylights, but were otherwise in reasonable order. He found personal items scattered about Briggs\' cabin, including a sheathed sword under the bed, but most of the ship\'s papers were missing, along with the captain\'s navigational instruments. No signs of fire or violence were obvious; the evidence indicated an orderly departure from the ship by means of the missing lifeboat.\nDeveau returned to report these findings to Morehouse, who decided to bring the derelict into Gibraltar 600 nautical miles (1,100 km) away. Under maritime law, a salvor could expect a substantial share of the combined value of rescued vessel and cargo, the exact award depending on the degree of danger inherent in the salvaging. Morehouse divided Dei Gratia\'s crew of eight between the two vessels, sending Deveau and two experienced seamen to Mary Celeste, while four others and he remained on Dei Gratia. The weather was relatively calm for most of the way to Gibraltar, but each ship was seriously undermanned and progress was slow. Dei Gratia reached Gibraltar on December 12; Mary Celeste had encountered fog and arrived on the following morning. She was immediately impounded by the vice admiralty court to prepare for salvage hearings. Deveau wrote to his wife that the ordeal of bringing the ship in was such that "I can hardly tell what I am made of, but I do not care so long as I got in safe. I shall be well paid for the Mary Celeste."']}]]}, {'title': 'Gibraltar salvage hearings', 'content': ['The salvage court hearings began in Gibraltar on December 17, 1872, under Sir James Cochrane, the chief justice of Gibraltar. The hearing was conducted by Frederick Solly-Flood, Attorney General of Gibraltar, who was also Advocate-General and Proctor for the Queen in Her Office of Admiralty. Flood was described by a historian of the Mary Celeste affair as a man "whose arrogance and pomposity were inversely proportional to his IQ", and as "... the sort of man who, once he had made up his mind about something, couldn\'t be shifted". The testimonies of Deveau and Wright convinced Flood unalterably that a crime had been committed, a belief picked up by the New York Shipping and Commercial List on December 21: "The inference is that there has been foul play somewhere, and that alcohol is at the bottom of it."\nOn December 23, Flood ordered an examination of Mary Celeste, which was carried out by John Austin, Surveyor of Shipping, with the assistance of a diver, Ricardo Portunato. Austin noted cuts on each side of the bow, caused, he thought, by a sharp instrument, and found possible traces of blood on the captain\'s sword. His report emphasized that the ship did not appear to have been struck by heavy weather, citing a vial of sewing machine oil found upright in its place. Austin did not acknowledge that the vial might have been replaced since the abandonment, nor did the court raise this point. Portunato\'s report on the hull concluded that the ship had not been involved in a collision or run aground. \nA further inspection by a group of Royal Naval captains endorsed Austin\'s opinion that the cuts on the bow had been caused deliberately. They also discovered stains on one of the ship\'s rails that might have been blood, together with a deep mark possibly caused by an axe. These findings strengthened Flood\'s suspicions that human wrongdoing rather than natural disaster lay behind the mystery. On January 22, 1873, he sent the reports to the Board of Trade in London, adding his own conclusion that the crew had gotten at the alcohol and murdered the Briggs family and the ship\'s officers in a drunken frenzy. They had cut the bows to simulate a collision, then fled in the yawl to suffer an unknown fate. Flood thought that Morehouse and his men were hiding something, specifically that Mary Celeste had been abandoned in a more easterly location, and that the log had been doctored. He could not accept that Mary Celeste could have traveled so far while uncrewed.\nJames Winchester arrived in Gibraltar on January 15, to enquire when Mary Celeste might be released to deliver her cargo. Flood demanded a surety of $15,000, money Winchester did not have. Winchester became aware that Flood thought Winchester might have deliberately engaged a crew that would kill Briggs and his officers as part of some conspiracy. On January 29, during a series of sharp exchanges with Flood, Winchester testified to Briggs\' high character, and insisted that Briggs would not have abandoned the ship except in extremity. Flood\'s theories of mutiny and murder received significant setbacks when scientific analysis of the stains found on the sword and elsewhere on the ship showed that they were not blood. A second blow to Flood followed in a report commissioned by Horatio Sprague, the American consul in Gibraltar, from Captain Shufeldt of the US Navy. In Shufeldt\'s view, the marks on the bow were not man-made, but came from the natural actions of the sea on the ship\'s timbers.\nWith nothing concrete to support his suspicions, Flood reluctantly released Mary Celeste from the court\'s jurisdiction on February 25. Two weeks later, with a locally raised crew headed by Captain George Blatchford from Massachusetts, she left Gibraltar for Genoa. The question of the salvage payment was decided on April 8, when Cochrane announced the award: £1,700, or about one-fifth of the total value of ship and cargo. This was far lower than the general expectation; one authority thought that the award should have been twice or even three times that amount, given the level of hazard in bringing the derelict into port. Cochrane\'s final words were harshly critical of Morehouse for his decision, earlier in the hearing, to send Dei Gratia under Deveau to deliver her cargo of petroleum, although Morehouse had remained in Gibraltar at the disposal of the court. In his 2005 book, Ghost Ship: The Mysterious True Story of the Mary Celeste and Her Missing Crew, writer Brian Hicks said Cochrane\'s tone carried an implication of wrongdoing, which ensured that Morehouse and his crew "...would be under suspicion in the court of public opinion forever."']}, {'title': 'Proposed explanations', 'content': ['', [{'title': 'Foul play', 'content': ['The evidence in Gibraltar failed to support Flood\'s theories of murder and conspiracy, yet suspicion of foul play lingered. Flood, and some newspaper reports, briefly suspected insurance fraud by Winchester on the basis that Mary Celeste was heavily overinsured. Winchester refuted these allegations, and no inquiry was instituted by the insurers that issued the policies. In 1931, an article in the Quarterly Review suggested that Morehouse could have lain in wait for Mary Celeste, then lured Briggs and his crew aboard Dei Gratia and killed them there. Paul Begg argues that this theory ignores the fact that Dei Gratia was the slower ship; she left New York eight days after Mary Celeste departed and would not have caught Mary Celeste before she reached Gibraltar.\nAnother theory posits that Briggs and Morehouse were partners in a conspiracy to share the salvage proceeds, although no evidence exists of a friendship between the two captains. Hicks comments, "[I]f Morehouse and Briggs had been planning such a scam, the

In [ ]:
len(cleaned_overflow)

2058

In [ ]:
len(overflow)

3335

In [ ]:
data = {
    "pages_db": cleaning_pages_db,
    "crawl_errors": crawl_errors,
    "wikipedia_queue": list(wikipedia_queue),
    "external_links_queue": list(external_links_queue),
    "visited_pages": list(visited_pages),
    "overflow":list(cleaned_overflow),
    "manual_inspection_bucket": list(cleaned_manual_inspection_bucket),
    "pages_with_tables": list(cleaned_pages_with_tables),
    "footprint":list(footprint),
    "see_also_links":list(cleaned_see_also_title)
}
with open(f"{SAVEFILE_DIR}crawl2_cleaned.json", "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=4)
print("--- Cleaning Saved Successfully ---")

--- Cleaning Saved Successfully ---

## Inspection

In [ ]:
load_progress()

In [ ]:
erasing_manualinsp = ['List of Whaling Walls','List of solved missing person cases (1970s)','List of lists of lists','Lists of murders','Lists of assassinations',
                      'List of people who disappeared mysteriously (pre-1910)','List of previously missing aircraft','Lists of people who disappeared']
presented_as_page = ['List of missing treasures','List of Bermuda Triangle incidents','List of destroyed heritage','List of missing aircraft']

In [ ]:
inspected_manual_inspection_bucket = [item for item in manual_inspection_bucket if item not in erasing_manualinsp]
inspected_manual_inspection_bucket = [item for item in inspected_manual_inspection_bucket if item not in presented_as_page]

In [ ]:
inspected_manual_inspection_bucket

['List of people who disappeared mysteriously (1980s)',
 'List of people who disappeared mysteriously (2000–present)',
 'List of people who disappeared mysteriously at sea',
 'List of missing ships',
 'List of people who disappeared mysteriously (1970s)',
 'List of people who disappeared mysteriously (1990s)',
 'List of fugitives from justice who disappeared',
 'List of people who disappeared mysteriously (1910–1970)']

In [ ]:
direct_links_in_table = [
    ['List of missing ships','Ship'],
    ['List of people who disappeared mysteriously (1980s)','Person(s)'],
    ['List of people who disappeared mysteriously (2000–present)','Person(s)'],
    ['List of people who disappeared mysteriously (1970s)','Person(s)'],
    ['List of people who disappeared mysteriously (1990s)','Person(s)'],

]
direct_links_in_table_restrict = [
    ['List_of_fugitives_from_justice_who_disappeared',{"Allowed":['1950s','1960s','1970s','1980s','1990s','2000s','2010s','2020s']},'Person(s)'],
    ['List of people who disappeared mysteriously at sea',{"Allowed":['1970–present']},'Person(s)'],

]

In [ ]:
df_footprint = pd.DataFrame(footprint, columns=['Curr Title', 'Origin', 'Action', 'Depth'])

In [ ]:
df_overflow = df_footprint[df_footprint['Curr Title'].isin(overflow)]
df_overflow = df_overflow[df_overflow['Action']=='overflow']

In [ ]:
len(df_overflow)

2271

In [ ]:
len(overflow)

2058

In [ ]:
df_overflow

,Curr Title,Origin,Action,Depth
9718,Vasco de Ataíde,Category:Missing person cases in Africa,overflow,4
9719,Jay Emmanuel Banda,Category:Missing person cases in Africa,overflow,4
9720,Clint Castleberry,Category:Missing person cases in Africa,overflow,4
9721,Zaida Catalán,Category:Missing person cases in Africa,overflow,4
9724,Douglas Clavering,Category:Missing person cases in Africa,overflow,4
...,...,...,...,...
21556,Category:Enforced disappearances in the Philip...,Category:Enforced disappearances by country,overflow,4
21557,Category:Enforced disappearances in the Soviet...,Category:Enforced disappearances by country,overflow,4
21558,Category:Enforced disappearances in Sri Lanka,Category:Enforced disappearances by country,overflow,4
21559,Category:Enforced disappearances in Thailand,Category:Enforced disappearances by country,overflow,4
21560,Category:Enforced disappearances in Venezuela,Category:Enforced disappearances by country,overflow,4

In [ ]:
df_overflow['Origin'].unique()

array(['Category:Missing person cases in Africa',
       'Category:Missing person cases in Asia',
       'Category:Missing person cases in Europe',
       'Category:Missing person cases in North America',
       'Category:Missing person cases in Oceania',
       'Category:Missing person cases in South America',
       'Category:Unsolved murders in Africa',
       'Category:Unsolved murders in Asia',
       'Category:Unsolved murders in North America',
       'Category:Unsolved murders in South America',
       'Category:Unidentified murderers by nationality',
       'Category:Unsolved murders in Afghanistan',
       'Category:Unsolved murders in Angola',
       'Category:Unsolved murders in Argentina',
       'Category:Unsolved murders in Australia',
       'Category:Unsolved murders in Austria',
       'Category:Unsolved murders in the Bahamas',
       'Category:Unsolved murders in Bangladesh',
       'Category:Unsolved murders in Belgium',
       'Category:Unsolved murders in Belize',
       'Category:Unsolved murders in Bosnia and Herzegovina',
       'Category:Unsolved murders in Botswana',
       'Category:Unsolved murders in Brazil',
       'Category:Unsolved murders in Bulgaria',
       'Category:Unsolved murders in Canada',
       'Category:Unsolved murders in Chile',
       'Category:Unsolved murders in China',
       'Category:Unsolved murders in Croatia',
       'Category:Unsolved murders in Cyprus',
       'Category:Unsolved murders in Ecuador',
       'Category:Unsolved murders in Egypt',
       'Category:Unsolved murders in Finland',
       'Category:Unsolved murders in France',
       'Category:Unsolved murders in Germany',
       'Category:Unsolved murders in Greece',
       'Category:Unsolved murders in Hungary',
       'Category:Unsolved murders in Indonesia',
       'Category:Unsolved murders in Iran',
       'Category:Unsolved murders in Iraq',
       'Category:Unsolved murders in Ireland',
       'Category:Unsolved murders in Italy',
       'Category:Unsolved murders in Japan',
       'Category:Unsolved murders in Libya',
       'Category:Unsolved murders in Malta',
       'Category:Unsolved murders in Mexico',
       'Category:Unsolved murders in Myanmar',
       'Category:Unsolved murders in Namibia',
       'Category:Unsolved murders in the Netherlands',
       'Category:Unsolved murders in New Zealand',
       'Category:Unsolved murders in Nigeria',
       'Category:Unsolved murders in Norway',
       'Category:Unsolved murders in Pakistan',
       'Category:Unsolved murders in Palau',
       'Category:Unsolved murders in the Philippines',
       'Category:Unsolved murders in Poland',
       'Category:Unsolved murders in Portugal',
       'Category:Unsolved murders in Romania',
       'Category:Unsolved murders in Russia',
       'Category:Unsolved murders in Rwanda',
       'Category:Unsolved murders in Singapore',
       'Category:Unsolved murders in Serbia',
       'Category:Unsolved murders in South Africa',
       'Category:Unsolved murders in the Soviet Union',
       'Category:Unsolved murders in Spain',
       'Category:Unsolved murders in Sri Lanka',
       'Category:Unsolved murders in Sweden',
       'Category:Unsolved murders in Turkey',
       'Category:Unsolved murders in Ukraine',
       'Category:Unsolved murders in the United Kingdom',
       'Category:Unsolved murders in the United States',
       'Category:Disappearance of Madeleine McCann',
       'Category:Unsolved crimes in England',
       'Category:Unsolved crimes in Scotland',
       'Category:Unidentified American criminals',
       'Category:Unidentified Brazilian criminals',
       'Category:Unidentified British criminals',
       'Category:Unidentified Canadian criminals',
       'Category:Unidentified serial killers',
       'Category:Unidentified American rapists',
       'Category:Unidentified British rapists',
       'List of unsolved murders (1901-1979)',
       'List of unsolved murders (20th century)',
       'List of unsolved murders (1900-1979)',
       'List of unsolved murders (1980-2000)',
       'List of unsolved murders (1980–2000)',
       'List of unsolved murders (1980-1999)',
       'List of unsolved murders (21st century)',
       'List of unsolved murders (after 2000)',
       'List of unsolved murders (2000-present)',
       'List of unsolved murders (before the 20th century)',
       'List of unsolved murders (before 20th Century)',
       'List of unsolved deaths', 'List of unsolved murders in Australia',
       'List of unsolved murders', 'List of unidentified murders',
       'List of unidentified murder',
       'List of unsolved murders in Belize',
       'Category:Unsolved mass murders in France',
       'Category:Unsolved mass murders in the United Kingdom',
       'Category:Unsolved mass murders in the United States',
       'Category:Unidentified murder victims in the United Kingdom',
       'Category:Unidentified murder victims in the United States',
       'Category:Unsolved airliner bombings in the United States',
       'Category:Lists of kidnappings',
       'Category:Malaysia Airlines Flight 370',
       'Category:Missing ships of Australia',
       'Category:Lost sailing vessels', 'Category:Missing submarines',
       'Category:Lost castles', 'Category:Hanging Gardens of Babylon',
       'Category:Ark of the Covenant', 'Category:Lost Fabergé eggs',
       'Category:Intentionally destroyed artworks',
       'Category:Nazi-looted art', 'Category:Lost paintings',
       'Category:Recovered works of art', 'Category:Lost sculptures',
       'Category:Reconstructed musical instruments',
       'Category:Stolen and missing Moon rocks',
       'Category:Taxa with lost type specimens',
       'Category:Missing person cases by country of disappearance',
       'Category:Missing children by nationality',
       'Category:Missing Afghan people',
       'Category:Missing American people',
       'Category:Missing Argentine people',
       'Category:Missing Australian people',
       'Category:Missing Austrian people',
       'Category:Missing Bangladeshi people',
       'Category:Missing Belgian people',
       'Category:Missing Brazilian people',
       'Category:Missing British people',
       'Category:Missing Canadian people',
       'Category:Missing Chinese people',
       'Category:Missing Colombian people',
       'Category:Missing Czech people', 'Category:Missing Finnish people',
       'Category:Missing French people', 'Category:Missing German people',
       'Category:Missing Greek people', 'Category:Missing Indian people',
       'Category:Missing Indonesian people',
       'Category:Missing Iranian people', 'Category:Missing Irish people',
       'Category:Missing Israeli people',
       'Category:Missing Italian people',
       'Category:Missing Japanese people',
       'Category:Missing Malaysian people',
       'Category:Missing Mexican people',
       'Category:Missing New Zealand people',
       'Category:Missing Nigerian people',
       'Category:Missing Norwegian people',
       'Category:Missing Pakistani people',
       'Category:Missing Palestinian people',
       'Category:Missing Russian people',
       'Category:Missing South African people',
       'Category:Missing South Korean people',
       'Category:Missing Sri Lankan people',
       'Category:Missing Swedish people', 'Category:Missing Swiss people',
       'Category:Missing Syrian people',
       'Category:Missing Ugandan people',
       'Category:Missing Ukrainian people', 'Category:Missing criminals',
       'Category:Lost explorers', 'Category:Disappeared journalists',
       'Category:Military personnel missing in action',
       'Category:Disappeared princes',
       'Category:Missing person cases by century',
       'Category:Missing person cases by decade',
       'Category:Missing people organizations',
       'Category:Grandmothers of the Plaza de Mayo',
       'Category:Mexican missing people activists',
       'Category:Missing and Murdered Indigenous Women and Girls activists',
       'Category:Mothers of the Plaza de Mayo',
       'Category:Vietnam War POW/MIA activists',
       'Category:Enforced disappearances by country'], dtype=object)

In [ ]:
origin_okay_overflow = []
for i, row in df_overflow.iterrows():
  if 'unsolved' in row['Origin'].lower() or 'unidentified' in row['Origin'].lower():
    origin_okay_overflow.append(row['Curr Title'])
print(len(origin_okay_overflow))

933

In [ ]:
remaining_overflow = df_overflow[~df_overflow['Curr Title'].isin(origin_okay_overflow)]

In [ ]:
eraising_origin = ['Category:Disappearance of Madeleine McCann','Category:Lists of kidnappings','Category:Intentionally destroyed artworks',
           'Category:Taxa with lost type specimens','Category:Grandmothers of the Plaza de Mayo','Category:Stolen and missing Moon rocks',
           'Category:Nazi-looted art', 'Category:Lost paintings','Category:Reconstructed musical instruments','Category:Lost sculptures',
           'Category:Recovered works of art', 'Category:Mothers of the Plaza de Mayo','Category:Vietnam War POW/MIA activists',
            'Category:Missing people organizations','Category:Hanging Gardens of Babylon','Category:Ark of the Covenant','Category:Lost Fabergé eggs',
            'Category:Lost castles','Category:Disappeared princes'
]
add = ['Disappearance_of_Madeleine_McCann','Malaysia_Airlines_Flight_370']
maybe_add = ['Hanging_Gardens_of_Babylon','Ark of the Covenant']

In [ ]:
remaining_overflow = remaining_overflow[~remaining_overflow['Origin'].isin(eraising_origin)]

In [ ]:
remaining_overflow['Origin'].unique()

array(['Category:Missing person cases in Africa',
       'Category:Missing person cases in Asia',
       'Category:Missing person cases in Europe',
       'Category:Missing person cases in North America',
       'Category:Missing person cases in Oceania',
       'Category:Missing person cases in South America',
       'Category:Malaysia Airlines Flight 370',
       'Category:Missing ships of Australia',
       'Category:Lost sailing vessels', 'Category:Missing submarines',
       'Category:Missing person cases by country of disappearance',
       'Category:Missing children by nationality',
       'Category:Missing Afghan people',
       'Category:Missing American people',
       'Category:Missing Argentine people',
       'Category:Missing Australian people',
       'Category:Missing Austrian people',
       'Category:Missing Bangladeshi people',
       'Category:Missing Belgian people',
       'Category:Missing Brazilian people',
       'Category:Missing British people',
       'Category:Missing Canadian people',
       'Category:Missing Chinese people',
       'Category:Missing Colombian people',
       'Category:Missing Czech people', 'Category:Missing Finnish people',
       'Category:Missing French people', 'Category:Missing German people',
       'Category:Missing Greek people', 'Category:Missing Indian people',
       'Category:Missing Indonesian people',
       'Category:Missing Iranian people', 'Category:Missing Irish people',
       'Category:Missing Israeli people',
       'Category:Missing Italian people',
       'Category:Missing Japanese people',
       'Category:Missing Malaysian people',
       'Category:Missing Mexican people',
       'Category:Missing New Zealand people',
       'Category:Missing Nigerian people',
       'Category:Missing Norwegian people',
       'Category:Missing Pakistani people',
       'Category:Missing Palestinian people',
       'Category:Missing Russian people',
       'Category:Missing South African people',
       'Category:Missing South Korean people',
       'Category:Missing Sri Lankan people',
       'Category:Missing Swedish people', 'Category:Missing Swiss people',
       'Category:Missing Syrian people',
       'Category:Missing Ugandan people',
       'Category:Missing Ukrainian people', 'Category:Missing criminals',
       'Category:Lost explorers', 'Category:Disappeared journalists',
       'Category:Military personnel missing in action',
       'Category:Missing person cases by century',
       'Category:Missing person cases by decade',
       'Category:Mexican missing people activists',
       'Category:Missing and Murdered Indigenous Women and Girls activists',
       'Category:Enforced disappearances by country'], dtype=object)

In [ ]:
remaining_overflow_title = list(remaining_overflow['Curr Title'].unique())

In [ ]:
# nned to process again
presented_as_page
direct_links_in_table
direct_links_in_table_restrict
origin_okay_overflow
remaining_overflow_title

False

In [ ]:
data = {
    "presented_as_page":presented_as_page,
    "direct_links_in_table":direct_links_in_table,
    "direct_links_in_table_restrict":direct_links_in_table_restrict,
    "origin_okay_overflow":origin_okay_overflow,
    "remaining_overflow_title":remaining_overflow_title,
}
with open(f"{SAVEFILE_DIR}inspected_next_seed_from2.json", "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=4)
print("--- Inspection Next Seed Saved Successfully ---")

--- Inspection Next Seed Saved Successfully ---

## Round 2

In [ ]:
filename = "inspected_next_seed_from2.json"
with open(f"{SAVEFILE_DIR}{filename}", "r", encoding="utf-8") as f:
    next_data = json.load(f)

In [ ]:
presented_as_page = next_data['presented_as_page']
direct_links_in_table = next_data['direct_links_in_table']
direct_links_in_table_restrict = next_data['direct_links_in_table_restrict']
origin_okay_overflow = next_data['origin_okay_overflow']
remaining_overflow_title = next_data['remaining_overflow_title']

In [ ]:
load_progress()

In [ ]:
new_queue = []

In [ ]:
df_footprint = pd.DataFrame(footprint, columns=['Curr Title', 'Origin', 'Action', 'Depth'])

In [ ]:
all_title = []
all_title.extend(remaining_overflow_title)
all_title.extend(origin_okay_overflow)
all_title = list(set(all_title))
all_pres_page = []
all_pres_page.extend(presented_as_page)
all_pres_page = list(set(all_pres_page))

In [ ]:
df_title = df_footprint[df_footprint['Curr Title'].isin(all_title)]
df_title = df_title[df_title['Action']=='overflow']
for i, row in df_title.iterrows():
  if row['Origin'].lower()=='cold case':
    continue
  new_queue.append((row['Curr Title'],0,row['Origin']))
print(len(new_queue))

1714

In [ ]:
df_title = df_footprint[df_footprint['Curr Title'].isin(presented_as_page)]
df_title = df_title[df_title['Action']=='list not unsolved-manual_inspect']
for i, row in df_title.iterrows():
  new_queue.append((row['Curr Title'],0,"$"+row['Origin']))
print(len(new_queue))

1718

In [ ]:
new_links = []
prefix = 'https://en.wikipedia.org/wiki/'
for p in direct_links_in_table:
  links = get_table_links(p[0], p[-1], allowed_sections=None)
  print(f"{p[0]}: {len(links)} links")
  cleaned_title = []
  for l in links:
    if l.startswith(prefix):
      cleaned_title.append((l[len(prefix):],0,p[0]))
    else:
      cleaned_title.append((l,0,p[0]))
  new_links.extend(cleaned_title)
print(len(new_links))

List of missing ships: 131 links
List of people who disappeared mysteriously (1980s): 85 links
List of people who disappeared mysteriously (2000–present): 255 links
List of people who disappeared mysteriously (1970s): 99 links
List of people who disappeared mysteriously (1990s): 99 links
669

In [ ]:
for p in direct_links_in_table_restrict:
  links = get_table_links(p[0], p[-1], allowed_sections=p[1]['Allowed'])
  print(f"{p[0]}: {len(links)} links")
  cleaned_title = []
  for l in links:
    if l.startswith(prefix):
      cleaned_title.append((l[len(prefix):],0,p[0]))
    else:
      cleaned_title.append((l,0,p[0]))
  new_links.extend(cleaned_title)
print(len(new_links))

List_of_fugitives_from_justice_who_disappeared: 132 links
List of people who disappeared mysteriously at sea: 45 links
846

In [ ]:
new_queue.extend(new_links)
print(len(new_queue))

2564

In [ ]:
TEXT_LIMIT = None  # Set to a number (e.g., 500) or None for full text
WAIT_RANGE = (1, 3)
BATCH_SIZE = 5
MAX_DEPTH = 2

# Queues & Tracking
#wikipedia_queue = deque([("Category:Unsolved crimes",0,"seed")])
external_links_queue = set()
manual_inspection_bucket = set()
overflow = set()
#footprint = []
#pages_with_tables = []  # Stores (Title, URL)
#see_also_title = set()     # Stores potential new Case Titles

In [ ]:
wikipedia_queue = deque(new_queue)

In [ ]:
run_crawler(limit=10000) # Adjust limit as needed
save_progress() # Save results

Crawling: USS Lynx (1814)
Crawling: German submarine U-703
Crawling: German submarine U-529
Crawling: German submarine U-184
Crawling: Aagtekerke (1724)
Crawling: German submarine U-381
Crawling: Amy (ship)
Crawling: SS Waratah
Crawling: USS Snook (SS-279)
Crawling: SS W.H. Gilcher
Crawling: German submarine U-376
Crawling: General Grant (sailing ship)
Crawling: USS Swordfish (SS-193)
Crawling: HMS York (1660)
Crawling: Hanneke Vrome
Crawling: MS Hans Hedtoft
Crawling: SS Bannockburn
Crawling: German submarine U-420
Crawling: Neustria (ship)
Crawling: SS Java (1865)
Crawling: Lyman D. Foster
Crawling: Bounty (1960 ship)
Crawling: French minesweepers Inkerman and Cerisoles
Crawling: USS Capelin
page ORP_Orze%C5%82_(1938) don't exist
Crawling: USS Runner (SS-275)
Crawling: Disappearance of Mirella Gregori
Crawling: Disappearance of Nyleen Marshall
page Agust%C3%ADn_Feced don't exist
page Ala%C3%ADde_Foppa don't exist
Crawling: Disappearance of Diane Suzuki
Crawling: Disappearance of Melanie Melanson
Crawling: Disappearance of Randy Sellers
Crawling: Disappearance of Ann Gotlib
Crawling: Hana Gaddafi
Crawling: Texas Killing Fields
Crawling: Tammy Lynn Leppert
Crawling: Disappearance of Jeremy Bright
Crawling: Disappearance of Julie Weflen
Crawling: Disappearance of John Favara
Crawling: Disappearance of Susan Smalley and Stacie Madison
Crawling: 1980s Franciscan priest murders
Crawling: Disappearance of Michaela Garecht
Crawling: Disappearance of Simon Parkes
Crawling: Disappearance of Ron Arad
Crawling: Kidnapping of Amber Swartz-Garcia
Crawling: Disappearance of Ludovic Janvier
Crawling: Hobo nickel
Crawling: Disappearance of Michelle Lewis
Crawling: Baalu Girma
Crawling: Disappearance of Tiffany Sessions
Crawling: Disappearance of Jenny Pandos
Crawling: 1980s Franciscan priest murders
Crawling: Irma Flaquer
Crawling: V. V. Sadagopan
Crawling: Madame Max Adolphe
Crawling: Disappearance of Suzy Lamplugh
page McDonald%27s_boys_case don't exist
Crawling: Murder of Alisha Heinrich
page Federico_Caff%C3%A8 don't exist
Crawling: Murder of Sara Anne Wood
Crawling: Disappearance of Emanuela Orlandi
Crawling: Disappearance of Royal Marine Alan Addis
Crawling: Reino Gikman
Crawling: Bassett Road machine gun murders
Crawling: Andrew Fluegelman
Crawling: Death of Ayakannu Marithamuthu
page Disappearance_of_Juan_Pedro_Mart%C3%ADnez don't exist
Crawling: Disappearance of Johnny Gosch
Crawling: Disappearance of Kirsa Jensen
Crawling: Sarinthip Siriwan
Crawling: Kidnapping of Melissa Brannen
Crawling: Disappearance of Charles Horvath-Allan
Crawling: Disappearance of Laureen Rahn
Crawling: Don Taxay
Crawling: Sture Bergwall
Crawling: Hristo Prodanov
Crawling: Disappearance of Julie Weflen
Crawling: Disappearance of Martha Jean Lambert
Crawling: Disappearance of Katrice Lee
Crawling: Lewis–Clark Valley murders
Crawling: North Korean abductions of Japanese citizens
Crawling: Disappearance of Lee Boxell
Crawling: Disappearance of Nicole Morin
Crawling: Disappearance of Tara Calico
Crawling: Disappearance of Cherrie Mahan
Crawling: Boris Weisfeiler
Crawling: Disappearance of Piia Ristikankare
Crawling: Naomi Uemura
Crawling: Disappearance of Anthonette Cayedito
Crawling: Antonio Bardellino
Crawling: Disappearance of Kevin Andrew Collins
Crawling: Terry Peder Rasmussen
Crawling: Vladimir Alexandrov
Crawling: Vagn Hoffmeyer Hoelgaard
Crawling: Nicolas Jaeger
Crawling: Disappearance of Tammy Belanger
Crawling: Peng Jiamu
Crawling: Disappearance of Tony Jones
Crawling: Sarkis Zeitlian
Crawling: Disappearance of Louise and Charmian Faulkner
Crawling: George Cogar
Crawling: Thomas A. Mutch
Crawling: Upali Wijewardene
Crawling: Disappearance of Patricia Meehan
Crawling: Ahmad Motevaselian
Crawling: Disappearance of Philip Cairns
Crawling: Jack family disappearance
Crawling: Murder of Jessie Earl
Crawling: A6 disappearances
Crawling: Cotah Ramaswami
Crawling: Ablajan Awut Ayup
Crawling: Death of Corrie McKeague
Crawling: Frood Fouladvand
Crawling: Timothy Verne Perryman
Crawling: Disappearance of David Louis Sneddon
Crawling: Thiruchelvam Nihal Jim Brown
Crawling: Neil McCasland
Crawling: Disappearance of Cynthia Bah-Traore
Crawling: Prageeth Eknaligoda
Crawling: Disappearance of Rahul Raju
Crawling: Aleksandr Khazanov
Crawling: Disappearance of Perry Cohen and Austin Stephanos
Crawling: Disappearance of Phoenix Coldon
Crawling: Disappearance of Joshua Guimond
Crawling: Disappearance of Tracy Splinter
Crawling: Disappearance of Jason Jolkowski
Crawling: Disappearance of Steven Cooper
Crawling: Disappearance of Daniel Robinson
Crawling: Disappearance of Russell Bohling
Crawling: Ameen family
Crawling: Bird of Jannah
Crawling: Karl-Erivan Haub
Crawling: Disappearance of Branson Perry
Crawling: Od Sayavong
Crawling: Disappearance of Jason Landry
Crawling: Disappearance of Garrett Bardsley
page Disappearance_of_Alfredo_Jim%C3%A9nez_Mota don't exist
Crawling: Disappearance of Jennifer Kesse
Crawling: Felix Batista
Crawling: Disappearance of Robert Levinson
Crawling: Disappearance of Logan Schiendelman
Crawling: DY (rapper)
Crawling: Monica Reza
Crawling: Mehbube Ablesh
Crawling: Malaysia Airlines Flight 370
Crawling: Kirk von Ackermann
page Fr%C3%A9d%C3%A9ric_N%C3%A9rac don't exist
Crawling: Disappearance of Tina Lim
Crawling: Drew Peterson
Crawling: Disappearance of LeeAnna Warner
Crawling: Disappearance of Sherlyn Cadapan and Karen Empeño
Crawling: Disappearance of Lisa Marie Young
Crawling: Disappearance of Marsha Brantley
Crawling: Disappearance of Kyron Horman
Crawling: Disappearance of Ben McDaniel
Crawling: Disappearance of Dulce Maria Alavez
page Daniel_Lind_Lagerl%C3%B6f don't exist
Crawling: Austin Tice
Crawling: Joseph Kibweteere
Crawling: Jim Gray (computer scientist)
Crawling: Disappearance of Jamie Fraley
Crawling: Disappearance of Charlene Downes
Crawling: Sombath Somphone
page Disappearance_of_Tiphaine_V%C3%A9ron don't exist
Crawling: Disappearance of Lisa Irwin
Crawling: Mahmoud Mahmoud Atta
Crawling: Arjen Kamphuis
Crawling: Disappearance of Lilly and Jack Sullivan
Crawling: Reda Helal
Crawling: Disappearance of Aeryn Gillern
Crawling: Disappearance of Niamh Maye
Crawling: Dzmitry Zavadski
Crawling: Disappearance of Stephan Sunthararaj
Crawling: Disappearance of Crystal Rogers
Crawling: Joseph Mifsud
Crawling: Disappearance of Sneha Anne Philip
Crawling: Zelim Bakaev
Crawling: MV Queen of the North
Crawling: Disappearance of Carlos Ornelas Puga
Crawling: Disappearance of Lisa Stebic
Crawling: Rahile Dawut
Crawling: Shamsa bint Mohammed Al Maktoum
Crawling: Disappearance of Jessie Foster
Crawling: Disappearance of Madeleine McCann
Crawling: Ananie Nkurunziza
Crawling: Disappearance of Alessia and Livia Schepp
Crawling: Aidin Bozorgi
Crawling: Cristina Siekavizza
Crawling: Wuthipong Kachathamakul
Crawling: Wanchalearm Satsaksit
Crawling: Razan Zaitouneh
Crawling: Disappearance of Zelimkhan Murdalov
Crawling: Disappearance of Samantha Murphy
Crawling: Disappearance of Steven Koecher
Crawling: Disappearance of Hannah Upp
Crawling: Disappearance of Asha Kreimer
Crawling: Murder of Porlajee Rakchongcharoen
Crawling: Disappearance of Danielle Imbo and Richard Petrone Jr.
page Disappearance_of_Allison_and_Marie-Jos%C3%A9_Benitez don't exist
Crawling: Disappearance of Ikran Tahlil Farah
Crawling: Saeed Zeinali
Crawling: Disappearance of Brian Shaffer
Crawling: Disappearance of Heimnot Kassau
Crawling: Paolo Renda
Crawling: Disappearance of Rebecca Coriam
Crawling: Disappearance of Sky Metalwala
Crawling: Disappearance of Alissa Turney
Crawling: Yusra Ismail
Crawling: Bodo Hell
Crawling: Disappearance of Emma Fillipoff
Crawling: Disappearance of Kristal Reisinger
Crawling: Gilgo Beach serial killings
Crawling: Disappearance of Elizabeth Clarke
Crawling: Disappearance of Bryce Laspisa
Crawling: Joseph Xing Wenzhi
Crawling: Disappearance of Georgina Gharsallah
Crawling: Murder of Jennifer Dulos
Crawling: An Myeong-jin
Crawling: Disappearance of Tammy Kingery
Crawling: Abdurehim Heyit
Crawling: Disappearance of Dylan Ehler
Crawling: Craig Arnold
Crawling: Disappearance of Macin Smith
Crawling: Disappearance of Rebecca Reusch
Crawling: Disappearance of Maya Millete
Crawling: Disappearance of Chhori Maiya Maharjan
Crawling: Maciej Berbeka
Crawling: Qari Ahmadullah
Crawling: Disappearance of Tabitha Tuders
Crawling: Gao Zhisheng
Crawling: Disappearances of Shaina Kirkpatrick and Shausha Henson
Crawling: Khadzhi-Murat Yandiev
Crawling: Disappearance of Timothy MacColl
Crawling: Disappearance of Alex Sloley
Crawling: Disappearance of Toni Sharpless
Crawling: Disappearance of Amber Cates
Crawling: Sabina Selimovic and Samra Kesinovic
Crawling: Sam Beal
Crawling: Disappearance of Asami Chida
page Guy-Andr%C3%A9_Kieffer don't exist
Crawling: Disappearance of Leah Roberts
Crawling: Disappearance of Father Francis
Crawling: Louis Roy
Crawling: Shelly Miscavige
Crawling: M. Ilias Ali
Crawling: Disappearance of John Beckenridge and Mike Zhao-Beckenridge
Crawling: Disappearance of Mekayla Bali
Crawling: Disappearance of William Tyrrell
Crawling: Lovinsky Pierre-Antoine
Crawling: Disappearance of Sarah Burton
Crawling: Disappearance of Lars Mittank
Crawling: Joe Pichler
Crawling: Disappearance of Heather Elvis
Crawling: Disappearance of Maura Murray
Crawling: Sim Chol-ho
page Jorge_Julio_L%C3%B3pez don't exist
Crawling: Jonathan Spollen
Crawling: Mohammed Al Afghani (CIA detainee)
Crawling: Disappearance of Zane Plemmons
Crawling: Missing women of Afrin
Crawling: Disappearance of Asha Degree
Crawling: Disappearance of Rahma el-Dennaoui
page 2021%E2%80%932022_Luzon_sabungero_disappearances don't exist
Crawling: Disappearance of Timmothy Pitzen
page Th%C3%A9o_Hayez don't exist
Crawling: Disappearance of Tiffany Whitton
Crawling: Disappearance of Inga Gehricke
Crawling: Disappearance of Gus Lamont
Crawling: Disappearance of Pascal Zimmer
Crawling: Disappearance of Bianca Piper
Crawling: Somchai Neelapaijit
page Disappearance_of_J%C3%B3n_J%C3%B3nsson don't exist
Crawling: Disappearance of Nancy Guthrie
Crawling: Raymond Koh
Crawling: Disappearance of Maureen Kelly
Crawling: Guma Aguiar
Crawling: Disappearance of Michael Vanzandt
Crawling: Disappearance of Marshal Iwaasa
Crawling: Disappearance of Shaun Ritchie
Crawling: Murders of Anna and Olivia Zimmerman
Crawling: Disappearance of Amy Fitzpatrick
Crawling: Disappearance of Kyran Durnin
page Julia_Chu%C3%B1il don't exist
Crawling: Disappearance of Susan Powell
Crawling: Disappearance of Taylor Casey
Crawling: Riaz Ahmed Gohar Shahi
Crawling: Disappearance of Abigail Blagg
Crawling: Disappearance of Ashley Summers
Crawling: Ammar al-Saffar
Crawling: Disappearance of Jordan Ratcliffe
Crawling: Mudassar Naaru
Crawling: Ezra Miller
Crawling: Anthony Zizzo
Crawling: Ray Gricar
Crawling: Disappearance of Iraena Asher
Crawling: Disappearances of Terrance Williams and Felipe Santos
Crawling: Bruno Manser
Crawling: Levi Davis (rugby union)
Crawling: Disappearance of Michele Anne Harris
Crawling: Disappearance of Sofia Juarez
Crawling: Dominick Arduin
Crawling: Disappearance of Rilya Wilson
Crawling: Disappearance of Louise Kerton
Crawling: Gary Hilton
Crawling: Disappearance of Darya Bulba
Crawling: Disappearance of Ayla Reynolds
Crawling: Disappearance of Sarm Heslop
Crawling: Dawood family terrorist cell
Crawling: Sivasubramaniam Raveendranath
Crawling: Disappearance of Luke Durbin
Crawling: Disappearance of Lauren Spierer
Crawling: Tetsu Inoue
Crawling: Tariq Mahmood (detainee)
Crawling: Disappearance of Elodia Ghinescu
Crawling: Murder of Joana Cipriano
Crawling: Sergei Dolgov
Crawling: Tomasz Mackiewicz
Crawling: Park Young-seok
Crawling: Paul Yazigi
Crawling: Disappearance of Marilyn Bergeron
Crawling: Disappearance of Claudia Lawrence
Crawling: Disappearance of Azory Gwanda
Crawling: Disappearance of Najeeb Ahmed
Crawling: Shibli al-Aysami
Crawling: Gill family disappearance
Crawling: Surachai Danwattananusorn
Crawling: Disappearance of Lina Khil
Crawling: Paul Tseng
Crawling: Disappearance of Sharlinie Mohd Nashar
Crawling: Disappearance of Vadivel Nimalarajah
Crawling: Disappearance of Rachel Funari
Crawling: Zarema Gaisanova
Crawling: Disappearance of Subramaniam Ramachandran
Crawling: Disappearance of Ali Astamirov
Crawling: Disappearance of Andrew Gosden
Crawling: Amri Che Mat
Crawling: Disappearance of Trevor Deely
Crawling: Disappearance of Brandon Swanson
Crawling: Disappearance of Christina Calayca
Crawling: 2003 Angola Boeing 727 disappearance
Crawling: Ebrima Manneh
Crawling: Disappearance of Jean-Christophe Morin
Crawling: Disappearance of Immaculate Basil
Crawling: Robert Hutchinson (missing person)
Crawling: Noof Al Maadeed
Crawling: Disappearance of Myra Lewis
Crawling: Masood Ahmed Janjua
Crawling: Julie Betu
Crawling: Disappearance of Natalee Holloway
Crawling: Vasyl Klymentyev
Crawling: Disappearance of Catherine Camilon
page Boris_%C5%9Eyhmyradow don't exist
page Marita_Ver%C3%B3n don't exist
Crawling: Disappearance of Lisa Dorrian
Crawling: John Cantlie
Crawling: Disappearance of Federico Tobares
Crawling: Disappearance of Tiffany Daniels
Crawling: Disappearance of Owen Harding
Crawling: Disappearance of Brianna Maitland
Crawling: Disappearance of Pamela Holopainen
Crawling: Lucassie Etungat
Crawling: Disappearance of Sudiksha Konanki
Crawling: Boyan Petrov
Crawling: Rico Harris
Crawling: Texas Killing Fields
Crawling: Jim Sullivan (musician)
Crawling: Disappearance of Andy Puglisi
Crawling: Disappearance of Adrien McNaughton
Crawling: The Disappeared (Northern Ireland)
Crawling: Norodom Chantaraingsey
Crawling: Disappearance of Lynne Schulze
Crawling: Joseph Kappen
Crawling: Sattar Jabr Naser
Crawling: Disappearance of Joanne Ratcliffe and Kirste Gordon
Crawling: Disappearance of Robin Graham
Crawling: Disappearance of Eloise Worledge
Crawling: Norodom Naradipo
Crawling: Thomas DeSimone
Crawling: Ali Murad Davudi
page Jussi_Kivim%C3%A4ki don't exist
Crawling: Pavlos Kouroupis
Crawling: Disappearance of Julie Weflen
page H%C3%A9ctor_Germ%C3%A1n_Oesterheld don't exist
Crawling: Murder of Georgann Hawkins
Crawling: Gerry Faustino
Crawling: Fritz Stammberger
Crawling: Hanna Mikhail
page Wladimir_Ch%C3%A1vez don't exist
Crawling: Disappearance of Mona Blades
Crawling: Jimmy Hoffa
Crawling: Disappearance of Trudie Adams
Crawling: Musa al-Sadr
Crawling: Brendan Simbwaye
page Mar%C3%ADa_Emilia_Islas don't exist
Crawling: Warren Forrest
Crawling: Juanita Nielsen
page Diana_Ar%C3%B3n don't exist
Crawling: Lewis–Clark Valley murders
Crawling: Boanerges de Souza Massa
Crawling: James Allen da Luz
Crawling: Disappearance of Jean Virginia Sampare
Crawling: Bruce Lindahl (criminal)
Crawling: Zahir Raihan
Crawling: Yaeko Taguchi
Crawling: Fort Worth missing trio
Crawling: Clinton Avenue Five
Crawling: Yuba County Five
Crawling: Ray Robinson (activist)
Crawling: Disappearance of Danielle Judic
Crawling: Disappearance of Jimmy Taylor
Crawling: Gerard John Schaefer
Crawling: Disappearance of Carmen Bueno and Jorge Müller
Crawling: Donald Mackay (anti-drugs campaigner)
Crawling: Disappearance of Genette Tate
Crawling: Disappearance of Frederick Valentich
Crawling: Willi Koeppen
Crawling: Disappearance of Martin Allen
Crawling: Disappearance of Sandy Davidson
Crawling: Sada Abe
Crawling: Disappearance of Mary Boyle
Crawling: Disappearance of Amy Billig
Crawling: Peter Winston (chess player)
Crawling: Gerard John Schaefer
Crawling: Disappearance of Margaret Ellen Fox
page Gu%C3%B0mundur_and_Geirfinnur_case don't exist
Crawling: William Beausire
Crawling: Disappearance of Helen Claire Frost
Crawling: A. B. M. Abdur Rahim
Crawling: Nasser Al Saeed
Crawling: North Korean abductions of Japanese citizens
Crawling: Tish Pascual-Ladlad
Crawling: Akpan Utuk
Crawling: Flag Boshielo
Crawling: Sean Flynn (photojournalist)
Crawling: Jim Robinson (boxer)
page V%C3%ADctor_Olea_Alegr%C3%ADa don't exist
Crawling: Disappearance of Jason Shannon
Crawling: Peter Christy
Crawling: Connie Converse
Crawling: Disappearance of Edward and Stephania Andrews
Crawling: Anocha Panjoy
Crawling: Ana Teresa Diego
Crawling: Henry Lee Lucas
Crawling: Mauro De Mauro
Crawling: Norodom Kantol
Crawling: John Brisker
Crawling: Juan Maino
Crawling: Muhammad Bassiri
Crawling: Nathaniel Bar-Jonah
Crawling: Megumi Yokota
Crawling: 1978 disappearance of Singapore social escorts
Crawling: Jamal Al-Gashey
Crawling: J. C. P. Williams
Crawling: Shahidullah Kaiser
Crawling: A. K. M. Miraj Uddin
Crawling: DNA Doe Project
Crawling: Robert Hohenberger
page Francisco_Ten%C3%B3rio_J%C3%BAnior don't exist
Crawling: Disappearance of Cheryl Grimmer
Crawling: Rakhal Chandra Das
Crawling: Oscar Zeta Acosta
Crawling: Helen Brach
Crawling: Disappearance of John and Gianinna Colonna
Crawling: Osvaldo Romo
Crawling: Death of Marion Barter
Crawling: Robert Leroy Anderson
Crawling: Ukshin Hoti
Crawling: Disappearances of Paul and Sarah Skiba and Lorenzo Chivers
Crawling: Yury Zacharanka
Crawling: Disappearance of Kelly Dae Wilson
Crawling: Aguilar de Campoo case
Crawling: Disappearance of Leonard Dirickson
Crawling: Disappearance of Melanie Ethier
Crawling: Disappearance of Guy Hever
Crawling: Disappearance of Deirdre Jacob
Crawling: Disappearance of Susan Walsh
Crawling: Disappearance of Jo Jo Dullard
Crawling: Gilbert Wynter
Crawling: Taif Ajba
Crawling: Jodi Huisentruit
Crawling: Disappearance of Vernon Jones
Crawling: Pierre Bianconi
page Jaros%C5%82aw_Zi%C4%99tara don't exist
Crawling: Disappearance of Kevin Palmer
Crawling: Ernst Priesner
Crawling: Disappearance of Erica Baker
Crawling: Viktar Hanchar
Crawling: Disappearance of Revelle Balmain
Crawling: Disappearance of Kristen Modafferi
Crawling: Disappearance of Manuel Schadwald
Crawling: Disappearance of Paige Renkoski
Crawling: Wopko Jensma
Crawling: Mary Jane Fonder
Crawling: Richey Edwards
Crawling: Disappearance of Dannette and Jeannette Millbrook
Crawling: Disappearance of Michael Negrete
Crawling: Tanong Po-arn
Crawling: Jacobo Grinberg
Crawling: Disappearance of Damien Nettles
Crawling: Disappearance of Fiona Pender
Crawling: Dor Bahadur Bista
Crawling: Ylenia Carrisi
Crawling: Disappearance of Sarah MacDiarmid
page Hausj%C3%A4rvi_Gravel_Pit_Murders#Maarit_Haantie don't exist
Crawling: Disappearance of Morgan Nick
Crawling: Pirouz Davani
Crawling: Disappearance of Amanda Campbell
Crawling: Disappearance of Katheryne Eggleston
Crawling: Disappearance of Erin Marie Gilbert
page Raisa_R%C3%A4is%C3%A4nen don't exist
Crawling: Altamira child emasculations
Crawling: Marat Manafov
Crawling: Disappearance of Joan Lawrence
Crawling: Disappearance of Cleashindra Hall
Crawling: Andrew Shumack
Crawling: Disappearance of Tin Song Sheng
Crawling: Disappearance of Julie Surprenant
Crawling: Disappearance of Ames Glover
Crawling: Chadrel Rinpoche
Crawling: Gedhun Choekyi Nyima
Crawling: Disappearance of Jared Negrete
Crawling: Eugene John Hebert
Crawling: Disappearance of Helena Andersson
Crawling: Abani Chakraborty
Crawling: Barry Cohen (attorney)
page Disappearance_of_Adam,_Trevor,_and_Mitchell_O%27Brien don't exist
Crawling: Widji Thukul
page Carl-Eric_Bj%C3%B6rkegren don't exist
Crawling: Disappearance of Thomas Gibson
Crawling: Angelo Cruz
Crawling: Kalpana Chakma
Crawling: Disappearance of Tammy Lamondin-Gagnon
Crawling: Licorice McKechnie
Crawling: Ruslan Labazanov
Crawling: Disappearance of Leigh Occhi
Crawling: Disappearance of Derrick Engebretson
Crawling: Florinda Donner
Crawling: Sukhwinder Singh Bhatti
Crawling: Disappearance of Annie McCarrick
Crawling: Disappearance of Patrick Warren and David Spencer
Crawling: Disappearance of Ben Needham
Crawling: Alain Kan
Crawling: Disappearance of Teresa Ann Davidson-Murphy
Crawling: Disappearance of John and Shelly Markley
Crawling: Disappearance of Ruth Wilson
Crawling: Nathaniel Bar-Jonah
Crawling: Boutros Khawand
Crawling: Springfield Three
Crawling: Teddy Wang
Crawling: Disappearance of Tanja Groen
Crawling: Disappearance of Steven Clark
Crawling: Aileen Wuornos

In [ ]:
wikipedia_queue

deque([])

In [ ]:
manual_inspection_bucket = set() #no useful next seed

In [ ]:
overflow

set()

In [ ]:
len(pages_db)

5421

In [ ]:
save_progress()

--- Progress Saved Successfully ---

## Final Clean

In [ ]:
SAVEFILE_DIR = "/content/drive/MyDrive/Mystery Search Engine/"
load_progress()
len(pages_db)

--- Progress Loaded from Checkpoint ---

5422

### Remove Obvious Page Titles & Origins

In [ ]:
cp_pages_db = pages_db.copy()

In [ ]:
page_title = list(cp_pages_db.keys())
rem_num = 0
for keys in page_title:
  #if keys.startswith("User:") or keys.startswith("User talk:") or keys.startswith("Wikipedia:") or keys.startswith("Wikipedia talk:") or keys.startswith("File:") or '.jpg' in keys:
  if keys.startswith("Talk:"):
    delmaybe = cp_pages_db.pop(keys, None)
    if delmaybe:
      rem_num += 1
print(rem_num)

28

In [ ]:
len(cp_pages_db)

5154

In [ ]:
page_title = list(cp_pages_db.keys())
page_title.sort()
for i in page_title:
  print(i)

11th Panchen Lama controversy
18 July 2012 Damascus bombing
1894 Rock Island railroad wreck
1896 Barcelona Corpus Christi procession bombing
1901 Redpath Mansion murders
1924 KLM Fokker F.III disappearance
1931 Avro Ten Southern Cloud disappearance
1939 City of San Francisco derailment
1945 RAAF Douglas C-47 disappearance
1948 Airborne Transport DC-3 disappearance
1948 Beechcraft Model 18 disappearance
1949 Menarsha synagogue bombing
1950 Douglas C-54D disappearance
1951 Atlantic C-124 disappearance
1953 Skyways Avro York disappearance
1955 RAF Shackleton aircraft disappearance
1956 Atlantic R6D-1 disappearance
1956 B-47 disappearance
1957 Pacific Ocean Boeing C-97 disappearance
1965 Argentine Air Force C-54 disappearance
1965–1966 Columbus murders
1966 theft of the Jules Rimet Trophy
1969 RAF Mildenhall C-130 theft
1972 Harlem mosque incident
1972 Montreal Museum of Fine Arts robbery
1972 Queenstown shooting
1973 Canadian Imperial Bank of Commerce bank robbery
1974 United States Air Force WC-130 disappearance
1975 LaGuardia Airport bombing
1977 Krugersdorp bank robbery
1978 Holiday Inn fire
1978 disappearance of Singapore social escorts
1980s Franciscan priest murders
1981 Barrington Tops Cessna 210 disappearance
1982 kidnapping of Iranian diplomats
1983 theft of the Jules Rimet Trophy
1984 Heathrow Airport bombing
1986 Indian Air Force Antonov An-32 disappearance
1987 Opera House heist
1987 Viking Sally murder
1988 Oshakati bomb blast
1989 firebombing of the Riverdale Press
1990 Faucett Perú Boeing 727 disappearance
1991 Sydney synagogue attacks
1992 Buenos Aires Israeli embassy bombing
1995 Palo Verde, Arizona, derailment
1995 kidnapping of western tourists in Kashmir
1996 Raleigh murders
1998 abduction of foreign engineers in Chechnya
1998 tourist kidnappings in Yemen
1999 Iranian student protests
1999 Loomis truck robbery
1999 Russian apartment bombings
2001 anthrax attacks
2003 Angola Boeing 727 disappearance
2003 Columbus, Ohio arson
2003 ricin letters
2006 Jama Masjid bombings
2006 Ulvila homicide case
2006 al-Askari mosque bombing
2007 al-Askari mosque bombing
2008 Damascus car bombing
2008 Istanbul bombings
2008 Noida double murder case
2008 Seattle Street of Dreams arson
2008 Times Square bombing
2008 disappearance of CIA operatives in the South China Sea
2009 Jamrud mosque bombing
2009 Mindanao bombings
2010 Al-Kazimiyya Mosque bombings
2010 Baqubah bombings
2010 Kurram agency mass kidnapping
2011 Alexandria bombing
2011 Matamoros mass kidnapping
2011 Montreal Museum of Fine Arts theft
2012 Alps killings
2012 Dnipropetrovsk explosions
2012 Eker bombing
2012 Gaziantep bombing
2013 Neo Irakleio Golden Dawn office shooting
2014 Gumsuri kidnappings
2014 Midwest FurFest gas attack
2014 hostage rescue operations in Yemen
2014 kidnapping and murders of Israeli teenagers
2015 Ankara bombings
2015 Zabul massacre
2016 Aktobe shootings
2016 Indian Air Force An-32 crash
2016 Tumeremo massacre
2016 Wilkinsburg shooting
2018 Bulawayo bombing
2019 English Channel Piper PA-46 crash
2019 Kabul mosque bombing
2019 Northern British Columbia murders
2020 Afrin bombing
2020 Moss Side shooting
2020 Mozambique attacks
2020 New York City Subway fire
2021 Canadian church burnings
2021 Garland shooting
2021 Pantelhó mass kidnapping
2021–2022 Luzon sabungero disappearances
2022 Aybak bombing
2022 Brink's theft
2022 Winnipeg serial killings
2023 Golden Temple blasts
2023 Matamoros kidnappings
2025 Drents Museum heist
2025 Stockton shooting
20th Century Limited derailment
300 million yen robbery
A Matter of Time (Cook novel)
A. B. M. Abdur Rahim
A. K. M. Miraj Uddin
A6 disappearances
AMIA bombing
ARA Fournier
Aafia Siddiqui
Aagtekerke (1724)
Aarni Neuvonen
Aaron Hall (singer)
Aban Elias
Abani Chakraborty
Abbie Gardner-Sharp
Abdolreza Shahlaei
Abduction and killing of Nissim Toledano
Abduction of Cleo Smith
Abduction of Jakub Fiszman
Abduction of Waliullah and Al Muqaddas
Abdul Aziz Awda
Abdul Karim Mahmoud Ibrahim
Abdullah Al-Rimi
Abdullahil Amaan Azmi
Abdulqadir Jalaleddin
Abdurehim Heyit
Abilio Diniz
Ablajan Awut Ayup
Abraham Gancwajch
Abraham Weinberg
Abram Petrovich Gannibal
Abu Humam al-Shami
Abu Nidal
Abu Omar case
Abu Ubaidah Youssef al-Annabi
Abuja Area Mama
Abuja–Kaduna train attack
Abul Fazal Ziaur Rahman
Acca Larentia killings
Achemez Gochiyayev
Active (1804 ship)
Adalbert Schneider
Adam (murder victim)
Adam Emery
Adelir Antônio de Carli
Adil Mijit
Admiral Karpfanger (barque)
Adolf Heiß
Adolph Coors III
Adolph Dubs
Adrian Lamo
Adriana Calvo
Adur Burzen-Mihr
Adventures with Purpose
Adélaïde Valentin
Adílio Daronch
Aeroflot Flight 773
Agapit Leblanc
Agatha Christie
Agim Hajrizi
Agnès Sorel
Agoston Haraszthy
Agrippina the Younger
Aguanga, California
Aguilar de Campoo case
Aguilas del Desierto
Agustín Feced
Ahmad Farhad
Ahmad Motevaselian
Ahmad Rezaee
Ahmad Tafazzoli
Ahmed Diriye
Ahmed Kousay al-Taie
Ahmed Rilwan
Ahoo Daryaei
Ai Weiwei
Aidin Bozorgi
Aileen Wuornos
Aimee Semple McPherson
Aimée du Buc de Rivéry
Air France Flight 072
Ajjamada B. Devaiah
Akhat Bragin
Akhmad Kadyrov
Akio Kashiwagi
Akpan Utuk
Akwaya massacre
Al Blozis
Al Brenner
Al Indelicato
Al Swearengen
Al-Hakim bi-Amr Allah
Alain Colas
Alain Kan
Alan Cordner
Alan Johnston
Alas Chiricanas Flight 00901
Alastair McNeil
Alaíde Foppa
Albert Anastasia
Albert DeSalvo
Albert Jennings Fountain
Albert Jewell
Albert Johan Petersson
Albert Johnson (criminal)
Albert Leidmann
Albert Tye
Alberta Odell Jones
Alberto Nisman
Albrecht Pflaum
Alcàsser Girls
Aldo Moro
Aldo Pontremoli
Aldo Vera Serafin
Alejandro Carrascosa
Aleksandr Khazanov
Aleksandrs Stankus
Aleksejs Anufrijevs
Aleksey Mozgovoy
Alessa Flores
Alessandro Miglia
Alessandro Stradella
Alex Nash
Alex Odeh
Alexander Bednov
Alexander Dubrovin
Alexander Kuchin
Alexander Litvinenko
Alexander McDonald (surgeon)
Alexander Men
Alexander Pfitzner
Alexander Trishatny
Alexander Zakharchenko
Alexander Zatonski
Alexandru Robot
Alexei Navalny
Alexey Muravyov
Alexis Flores
Alf Giblett
Alf Williamson
Alfonza W. Davis
Alfred Druschel
Alfred Evans (Royal Navy officer)
Alfred Gibson
Alfred Herrhausen
Alfred Loewenstein
Alfred Partikel
Alfred Raper
Alfred Rewane
Alfred Rouse
Alfred Schakron
Ali Macalintal
Ali Mahmoud Abbas
Ali Murad Davudi
Ali Sadpara
Ali Sayyid Muhamed Mustafa al-Bakri
Ali Zeidan
Ali-Akbar Sa'idi Sirjani
Alice Kyteler
Alicia Kozakiewicz
Alicia Ross
Allahabad (ship)
Allan McDonald (New Zealand politician)
Allen Dorfman
Alma Preinkert
Almería Ripper
Alonso de Reinoso
Alphabet murders
Alphonse Gangitano
Altamira child emasculations
Alvar Larsson
Alvin and Judith Neelley
Amanda Lindhout
Amanda Peterson
Amar Singh Chamkila
Amaryllis Garnett
Amber Beacon Tower murder
Amber Kanazbah Crotty
Amber Room
Ambrogio Fogar
Ambrose Bierce
Ameen family
Amelia (1816 ship)
Amelia Earhart
America (airship)
American Society of Criminology
Ames strain
Amina Ali
Amina Masood Janjua
Aminatou Haidar
Amit Soussana
Ammar al-Saffar
Amphiaraos Krater
Amri Che Mat
Amy (ship)
Amy Johnson
Amy Robsart
Amílcar Henríquez
An Myeong-jin
An Seong-hee
Ana Lucrecia Taglioretti
Ana Mendieta
Ana Teresa Diego
Anak Agung Bagus Suteja
Ananda Mahidol
Ananias Dare
Ananie Nkurunziza
Anas Pshikhachev
Anastácio Alves
Anatol Krasouski
Anatoly Trofimov
Anders Eklund (murderer)
Andrea Buchanan
Andrea Gail
Andres Ojamaa
Andrew Carnegie Whitfield
Andrew Evans case
Andrew Fluegelman
Andrew Irvine (mountaineer)
Andrew Koenig
Andrew McAuley
Andrew Shumack
Andrew Veniamin
Andrey Chekharin
Andrey Lukanov
Andriy Klyuyev
Andronikos Kantakouzenos (1553–1601)
André Desjardins
Andrés Pastrana Arango
Angel of the Meadow
Angela Atim Lakor
Angela Toler
Angelo Bruno
Angelo Cruz
Angus Primrose
Anjuman Shehzadi
Ann Arbor Hospital murders
Anna (1790 ship)
Anna Catharina
Anna Ekelöf
Anna Mae Aquash
Anna Politkovskaya
Anne de Mowbray, 8th Countess of Norfolk
Anneka Di Lorenzo
Anocha Panjoy
Antarctic Snow Cruiser
Anthony Cox (producer)
Anthony D'Andrea
Anthony Eden
Anthony Hardy
Anthony Hugh Baldwin
Anthony Spilotro
Anthony Strollo
Anthony Zizzo
Anthrax hoaxes
Anthropological criminology
Anti-gay purges in Chechnya
Antoine Bernardin Fualdès
Antoine Cordonnier
Antoine de Saint-Exupéry
Anton Lubowski
Antonio Anglés
Antonio Bardellino
Antonio Caponigro
Antonio María Oriol Urquijo
Antônio da Costa Santos
Appin Murder
April 2007 Yazidi massacre
Arch Corbett
Archduke Johann Salvator of Austria
Archibald Bisset Smith
Archibald S. Dobbins
Archie E. Mitchell
Ardenwald axe murders
Argo (1806 Chittagong ship)
Ariel Castro kidnappings
Arjan Erkel
Arjen Kamphuis
Ark Project
Ark of the Covenant
Arlington Springs Man
Armada Tapestries
Armando Torres III
Armenia without Armenians
Armita Abbasi
Arnaldo Berni
Arno (ship)
Arnold Rothstein
Arnold Schuster
Arnon Street killings
Arrest of Awad bin Mohammed Al-Qarni
Arsen Pavlov
Art Gilkey
Art Grant (ice hockey)
Art Scholl
Art destruction
Arthur "Buddy" Schumacher
Arthur Bateman (cricketer)
Arthur Brennan
Arthur Coningham (RAF officer)
Arthur Cook (New Zealand politician)
Arthur Cravan
Arthur Forbes Gordon Kilby
Arthur I, Duke of Brittany
Arthur Lang
Arthur Lee Washington Jr.
Arthur Piver
Arthur Rhys-Davids
Arthur St. Clair (minister)
Arthur Warbrick
Arthur William Gebaur Jr.
Artur Marczewski
Artur Phleps
Artwork damaged or destroyed in the September 11 attacks
Arved Crüger
Asa Eldridge
Asau Tran
Asgard II
Ashikaga murder case
Ashraf Marwan
Asian Federation Against Involuntary Disappearances
Askar Simitko
Asor
Assad Saftawi
Assassination of Anna Politkovskaya
Assassination of Antonio Halili
Assassination of Benazir Bhutto
Assassination of Boris Nemtsov
Assassination of Haim Arlosoroff
Assassination of Jamal Khashoggi
Assassination of Juvénal Habyarimana and Cyprien Ntaryamira
Assassination of Mahmoud Al-Mabhouh
Assassination of Marielle Franco
Assassination of Olof Palme
Athalia Ponsell Lindsley
Atilla Altıkat
Atlanta Lover's Lane Murders
Atlanta Ripper
Atlantic (yacht)
Atlas (1811 ship)
Atlas Vampire
Attilio Cubeddu
August Landmesser
August Wesley
Austin Tice
Australians missing in action in the Vietnam War
Auzella Savage
Avdo Palić
Avera Mengistu
Avro Lancaster PA278 disappearance
Axeman of New Orleans
Ayaad Assaad
Ayanda Ngila
Ayman Udas
Aynaghar
Azerbaijanis who went missing during the First Nagorno-Karabakh War
B. H. DeLay
B1 Butcher
BSAA Star Ariel disappearance
BSAA Star Tiger disappearance
Baalu Girma
Babes in the Wood murders (Brighton)
Babes in the Wood murders (Epping Forest)
Babes in the Wood murders (Pine Grove Furnace)
Babes in the Wood murders (Stanley Park)
Bad News Brown (musician)
Bag murders
Baghdad Battery
Bahriye Üçok
Bain family murders
Bakri Wahab
Baloch Long March
Bambi Woods
Baneheia murders
Bangalore (1886 ship)
Banner of Misericordia
Bao Fan
Bar Kupershtein
Bar du Téléphone massacre
Barbara Ann Hackmann Taylor
Barbara Colby
Barbara Newhall Follett
Barbu Catargiu
Barkworth (1811 ship)
Barney Barnato
Baron 52
Barrie MacKenzie
Barry Cohen (attorney)
Barry Cowsill
Barry Evans (actor)
Barry Sherman
Bas Jan Ader
Bashir Khan Qureshi
Basri Tupella
Bass Strait Triangle
Bassett Road machine gun murders
Bastian Vasquez
Batalanda detention centre
Batman rapist
Battle of Mucojo
Battle of Palma
Beate Ulbricht
Bedgebury Forest Woman
Begench Beknazarov
Beilis affair
Belize Ripper
Belle Gunness
Belle Sheridan (1852)
Belle Starr
Bellona (1799 ship)
Ben Golden McCollum
Bengal (1799 EIC ship)
Benjaman Kyle
Benjamin Bathurst (diplomat)
Benjamin Boyd
Benjamin Church (physician)
Benjamin F. Lewis
Benjamin Nathan
Benjamin Weir
Benjamin de Jesus
Benjamín Galván Gómez
Bennington Triangle
Benoît Chamoux
Bermuda
Bermuda Triangle
Bernard Gavrin
Bernard O'Reilly (bishop of Hartford)
Bernardo Araya Zuleta
Bert Peters
Bert Wipiti
Berthold Korts
Betty Lalam
Bhadreshkumar Chetanbhai Patel
Bible John
Bibliography of sociology
Biblioteca della Comunità Israelitica
Big Hawk
Big Jim Colosimo
Big L
Bigfoot Killer
Bill Aldag
Bill Barilko
Bill Biggart
Bill Genaust
Bill Madden (footballer)
Bill Sparks
Bill Tilman
Billy Brewer (footballer)
Billy the Axeman
Bindy Johal
Bird of Jannah
Birendra Shah
Bison Dele
Bisoye Tejuoso
Bitcoin buried in Newport landfill
Bizzy Bone
Black Bart (outlaw)
Black Dahlia
Black Donnellys
Black and Missing Foundation
Blackfriars Massacre
Blanca Fernández Ochoa
Blanche Monnier
Blenheim (1834 ship)
Blessing of the Bay
Blonde Dolly
Blue Ridge Savings Bank murders
Bluefin-21
Blutfahne
Boanerges de Souza Massa
Bob Doll
Bob Lymburne
Bob Neighbors
Bob Smith (New Hampshire politician)
Bobby Donati
Bobby Jack Fowler
Bobi Sourander
Bodo Hell
Body in the cylinder
Bogle–Chandler case
Bola Ige
Bombers Affair
Bombings of Paddington and Victoria stations
Bongboto massacre
Bonifacio Mencias
Bonny Lee Bakley
Borgstrom brothers
Boris Berezovsky (businessman)
Boris Léontieff
Boris Safonov
Boris Weisfeiler
Boris Şyhmyradow
Boston Corbett
Boulie Tacker
Bouncing Ball Killer
Bounty (1960 ship)
Boutros Khawand
Bowe Bergdahl
Bowel Movement Bandit
Bowraville murders
Boyan Petrov
Boyd Wagner
Brabant killers
Brad Booth
Bradford Bishop
Bradford murders
Brahim Dahane
Branko Bulatović
Brazilian battleship São Paulo
Brazilian cargo ship Cabedello
Bražuolė bridge bombing
Brendan Megraw
Brendan Simbwaye
Brent Hesselyn
Brett Cantor
Brett Kebble
Brian "Little Legs" Clifford
Brian Abbot
Brian Keenan (writer)
Brian Lane (RAF officer)
Brian Spencer
Brice Goldsborough
Bridget Tolley
Bridgewater (1785 EIC ship)
Bridgewater Four
Brighton trunk murders
Brilliant (1812 ship)
British Columbia Highway 16
Bruce Edwards Ivins
Bruce Lindahl (criminal)
Bruneri-Canella case
Bruno Bréguet
Bruno Claußen
Bruno Manser
Bruno Neumann
Bruno Pereira
Brussels Islamic State terror cell
Bugsy Siegel
Buhl Woman
Bum Farto
Bureau of Justice Statistics
Burger Chef murders
Burial place of Genghis Khan
Burmah (ship)
Buster from Chicago
Butcher of Mons
Byron McLaughlin
C. B. Johnston
CSS Sumter
Caesarion
Cairo fire
Calcutta (1798 EIC ship)
Caligula case
Cam Lyman
Cambridge (1825 ship)
Camden Town Murder
Camille Lepage
Camillo Berneri
Camilo Cienfuegos
Camoflauge
Campden Wonder
Canadian Pacific Air Lines Flight 21
Canadian Pacific Air Lines Flight 3505
Candice Cohen-Ahnine
Cape Town Prostitute Killer
Capitol Hill mystery soda machine
Cardiff Newsagent Three
Carina (yacht)
Carl Grillmair
Carl R. Disch
Carl Shaeffer
Carl Williams (criminal)
Carl Zeidler
Carl-Eric Björkegren
Carlee Russell disappearance hoax
Carlett Brown Angianlee
Carlo Giuseppe Bertero
Carlo Tresca
Carlo Valdinoci
Carlos Andrés García (politician)
Carlos Barrionuevo
Carlos Meneses Lambis
Carlos Muñiz Varela
Carol Rymer Davis
Caroline (schooner)
Caroline Bittencourt
Carroll A. Deering
Carteron murders
Case of Amarildo de Souza
Casey McCann
Castration serial murders
Castro (musician)
Catharina de Grebber
Causeway Bay Books disappearances
Cavit Orhan Tütengil
Cayara massacre
Cebu City
Ceci Flores Armenta
Cecil Grace
Cecil Kern
Cecil Pugh
Cecilia Cacabelos
Cedric Edwards
Celso Daniel
Centrs department store bombing
Cevat Yurdakul
Ceylanpınar incident
Chad Robinson
Chadrel Rinpoche
Chain murders of Iran
Chalice from Slutsk
Chalino Sánchez
Chan Kai-kit
Chandrashekhar Prasad
Charles B. Stover
Charles Berlitz
Charles Bravo
Charles Budd Robinson
Charles Christian Dutton
Charles Clifford Ogle
Charles Frederick Des Voeux
Charles H. Barker
Charles Hegyalji
Charles J. Loring Jr.
Charles Kingsford Smith
Charles L. Gilliland
Charles L. Keerans
Charles Lefebvre-Desnouettes
Charles M. Waterman (politician)
Charles Miller (musician)
Charles Nicoletti
Charles Nungesser
Charles Pelham, Lord Worsley
Charles Peter O'Sullivan
Charles Quette
Charles Rogers (murder suspect)
Charles Shelton
Charles Ulm
Charles W. Chipp
Charles W. Whittlesey
Charles XII of Sweden
Charlie Chop-off
Charry Napto
Chartist Mural
Chekker
Cheltenham torso mystery
Chen Qiushi
Chen family killings
Cheng Lei (journalist)
Cherie Westell
Chhota Shakeel
Chibok schoolgirls kidnapping
Chicago Strangler
Chicago Tylenol murders
Chilobwe murders
Chinx
Chiong murder case
Chittisinghpura massacre
Chris Trickle
Christer Ericsson
Christian Poveda
Christiana Mall
Christopher Dale Flannery
Christopher Guarin
Christopher Marsden
Chrotta
Chu Anping
Chucheep Chiwasut
Cinco Chagas
Cladh Hallan
Clandestine detention center (Argentina)
Clara Rojas
Clarence 13X
Clarence Triggs
Claude Callegari
Claude Weaver III
Clem Graver
Clement Howell
Cleveland Torso Murderer
Clifton Cushman
Cline Falls axe attack
Clint Castleberry
Clinton Avenue Five
Clive Barry
Clocaenog Forest Man
Cody Legebokoff
Cold case
Coldstream (1810 ship)
Coldstream Packet (1794 ship)
Colin Ridgway
Colin Rutherford
Collet Barker
Colony collapse disorder
Columba McVeigh
Comerford Crown
Commando (aircraft)
Complement of HMS Bounty
Computational criminology
Concordia (1696 ship)
Concordia (ship)
Connecticut River Valley Killer
Connie Converse
Constance Marten and Mark Gordon
Constanze Manziarly
Consuelo Araújo
Cornelia Zangari Bandi
Cornell Gunter
Cornwallis (1812 ship)
Corny Ostermann
Correlates of crime
Corrida (horse)
Costas Taktsis
Costello's
Cotah Ramaswami
Counter-Guerrilla
Cowden family murders
Craig Arnold
Craig, Alaska
Crawford family murder
Credonia Mwerinde
Cremorne (clipper)
Crime clearance rate
Crime harm index
Crime mapping
Crime of Cuenca
Crime science
Crime statistics
Criminology
Cris and Cru Kahui homicides
Crispin Dye
Cristina Catalla
Cristina Siekavizza
Crocker child murders
Crosbie Garstin
Cross of Saint Euphrosyne
Crown of Rus
Crown of Zvonimir
Croye Pithey
Cuatro Vientos (aircraft)
Cullen Finnerty
Cultural criminology
Cumminsville Killer
Curtis Chillingworth
Curtis Flowers
Cuthbert Bromley
Cybercrime
Cymric (schooner)
Cynthia Ann Parker
Cyprien Ntaryamira
Cyprus Airways Flight 284
Cyprus lunar sample displays
D. B. Cooper
DJ Derek
DNA Doe Project
DY (rapper)
Dada Vujasinović
Dag Hammarskjöld
Dagmar Hagelin
Dahlsjö Case
Daisy Grace
Dallas Spirit
Damer Leslie Allen
Dan Billany
Dan Rapoport
Dana Stone
Dane Elkins
Daniel Küblböck
Daniel Lind Lagerlöf
Daniel Montbars
Daniel Pearl
Daniel S. Voorhees
Daniele Mastrogiacomo
Danilovsky Maniac
Danny Leclère
Danny Rodriguez
Danny Walsh
Danube (ship)
Dapchi schoolgirls kidnapping
Daphne Caruana Galizia
Dardeen family homicides
Darius (1824 ship)
Dark figure of crime
Darrell R. Lindsey
Dasha Medova
Dauvray Cup
Dave Rowbotham
Dave Rudabaugh
David Atcherley
David Bacon (actor)
David Bird (journalist)
David Carroll (biker)
David Chingunji
David Cox (Marine)
David Cunio
David Durham (fugitive)
David K. E. Bruce
David Kenyon Webster
David Kraiselburd
David Lytton
David M. Kelly
David Moore Crook
David Park Barnitz
David Sharp (mountaineer)
David Silberman Gurovich
David Smith (murderer)
David Thomas Richardson
David Thompson (New Hampshire settler)
David Wanklyn
David Wilcock
Davy Crockett
Dawn Dumont
Dawood Ibrahim
Dawood family terrorist cell
Dayton Strangler
DeBlase children murders
Deal barracks bombing
Dean A. Pogreba
Death Valley Germans
Death and state funeral of Zia-ul-Haq
Death of Adolf Hitler
Death of Adre-Anna Jackson
Death of Alberto Nisman
Death of Alexander the Great
Death of Alloura Wells
Death of Alonzo Brooks
Death of Amber Tuccaro
Death of Andrew Sadek
Death of Ayakannu Marithamuthu
Death of Azaria Chamberlain
Death of Barbara Precht
Death of Benny Whitehouse
Death of Brandon Crisp
Death of Brandon Lawson
Death of Brian Egg
Death of Brian Murphy
Death of Carl Isaacs Jr.
Death of Caroline Byrne
Death of Caylee Anthony
Death of Chanel Petro-Nixon
Death of Christoph Bulwin
Death of Cindy James
Death of Cleopatra
Death of Corrie McKeague
Death of Daniel Nolan
Death of Dave Walker
Death of David Glenn Lewis
Death of Don Kemp
Death of Doris Girtz
Death of Edgar Allan Poe
Death of Elisa Lam
Death of Esther Dingley
Death of Facundo Astudillo Castro
Death of Felicia Teo
Death of Frances Rasuge
Death of Frances Smith
Death of Gareth Williams
Death of Giorgiana Masi
Death of Gloria Ramirez
Death of Hedviga Golik
Death of Henri Le Masne
Death of James Conklin
Death of Jaryd Atadero
Death of Jason Callahan

In [ ]:
page_origin = set()
for key, value in cp_pages_db.items():
  page_origin.add(value['origin_title'])
page_origin = list(page_origin)
page_origin.sort()
for i in page_origin:
  print(i)

Category:1490s missing person cases
Category:1500s missing person cases
Category:1570s missing person cases
Category:1580s missing person cases
Category:1590s missing person cases
Category:1620s missing person cases
Category:1670s missing person cases
Category:1700s missing person cases
Category:1730s missing person cases
Category:1790s missing person cases
Category:17th-century missing person cases
Category:1800s missing person cases
Category:1810s missing person cases
Category:1820s missing person cases
Category:1830s missing person cases
Category:1840s missing person cases
Category:1850s missing person cases
Category:1860s missing person cases
Category:1870s missing person cases
Category:1880s missing person cases
Category:1890s missing person cases
Category:1900s missing person cases
Category:1910s missing person cases
Category:1920s missing person cases
Category:1930s missing person cases
Category:1940s missing person cases
Category:1950s missing person cases
Category:1960s missing person cases
Category:1970s missing person cases
Category:1980s missing person cases
Category:1990s missing person cases
Category:2000s missing person cases
Category:2001 anthrax attacks
Category:2010s missing person cases
Category:2020s missing person cases
Category:20th-century missing person cases
Category:21st-century missing person cases
Category:Aerial disappearances
Category:Aerial disappearances of military personnel in action
Category:Bermuda Triangle
Category:Castaways
Category:Disappeared journalists
Category:Enforced disappearances
Category:Enforced disappearances in Argentina
Category:Enforced disappearances in Bangladesh
Category:Enforced disappearances in Belarus
Category:Enforced disappearances in Cambodia
Category:Enforced disappearances in Chile
Category:Enforced disappearances in China
Category:Enforced disappearances in Egypt
Category:Enforced disappearances in India
Category:Enforced disappearances in Iran
Category:Enforced disappearances in Northern Ireland
Category:Enforced disappearances in Pakistan
Category:Enforced disappearances in Sri Lanka
Category:Enforced disappearances in Venezuela
Category:Enforced disappearances in the Philippines
Category:Enforced disappearances in the Soviet Union
Category:Formerly missing people
Category:Highway of Tears
Category:Jack the Ripper
Category:Kidnapped Palestinian people
Category:Lost and extinct musical instruments
Category:Lost buildings and structures
Category:Lost explorers
Category:Lost objects
Category:Lost sailing vessels
Category:Lost works of art
Category:Malaysia Airlines Flight 370
Category:Mass disappearances
Category:Melbourne gangland killings
Category:Mexican missing people activists
Category:Military personnel missing in action
Category:Missing American children
Category:Missing American people
Category:Missing Argentine children
Category:Missing Argentine people
Category:Missing Austrian people
Category:Missing Belgian people
Category:Missing Brazilian people
Category:Missing British people
Category:Missing Canadian children
Category:Missing Canadian people
Category:Missing Chinese people
Category:Missing Colombian people
Category:Missing English people
Category:Missing Finnish people
Category:Missing French children
Category:Missing French people
Category:Missing German children
Category:Missing German people
Category:Missing Indian people
Category:Missing Indonesian people
Category:Missing Iranian people
Category:Missing Irish people
Category:Missing Israeli people
Category:Missing Italian children
Category:Missing Italian people
Category:Missing Japanese people
Category:Missing Malaysian people
Category:Missing New Zealand people
Category:Missing Nigerian people
Category:Missing Norwegian people
Category:Missing Pakistani people
Category:Missing Palestinian people
Category:Missing Russian people
Category:Missing Scottish people
Category:Missing South African people
Category:Missing South Korean people
Category:Missing Sri Lankan people
Category:Missing Swedish people
Category:Missing Swiss people
Category:Missing Syrian people
Category:Missing Ugandan people
Category:Missing Ukrainian people
Category:Missing air passengers
Category:Missing aircraft
Category:Missing and Murdered Indigenous Women and Girls activists
Category:Missing aviators
Category:Missing children
Category:Missing fugitives
Category:Missing gangsters
Category:Missing in action of World War I
Category:Missing in action of World War II
Category:Missing people
Category:Missing people activists
Category:Missing people identified through genetic genealogy
Category:Missing people organizations based in the United States
Category:Missing person cases in Afghanistan
Category:Missing person cases in Africa
Category:Missing person cases in Argentina
Category:Missing person cases in Asia
Category:Missing person cases in Australia
Category:Missing person cases in Austria
Category:Missing person cases in Azerbaijan
Category:Missing person cases in Bangladesh
Category:Missing person cases in Belgium
Category:Missing person cases in Brazil
Category:Missing person cases in British Columbia
Category:Missing person cases in Cambodia
Category:Missing person cases in Canada
Category:Missing person cases in Chile
Category:Missing person cases in China
Category:Missing person cases in Colombia
Category:Missing person cases in Cuba
Category:Missing person cases in Denmark
Category:Missing person cases in Egypt
Category:Missing person cases in England
Category:Missing person cases in Europe
Category:Missing person cases in Finland
Category:Missing person cases in France
Category:Missing person cases in Germany
Category:Missing person cases in Greece
Category:Missing person cases in Guatemala
Category:Missing person cases in Haiti
Category:Missing person cases in Hong Kong
Category:Missing person cases in Hungary
Category:Missing person cases in Iceland
Category:Missing person cases in India
Category:Missing person cases in Indonesia
Category:Missing person cases in Iran
Category:Missing person cases in Iraq
Category:Missing person cases in Ireland
Category:Missing person cases in Israel
Category:Missing person cases in Italy
Category:Missing person cases in Japan
Category:Missing person cases in Lebanon
Category:Missing person cases in Libya
Category:Missing person cases in London
Category:Missing person cases in Malaysia
Category:Missing person cases in Mexico
Category:Missing person cases in Morocco
Category:Missing person cases in Nepal
Category:Missing person cases in New Zealand
Category:Missing person cases in Nigeria
Category:Missing person cases in North America
Category:Missing person cases in Northern Ireland
Category:Missing person cases in Norway
Category:Missing person cases in Pakistan
Category:Missing person cases in Paraguay
Category:Missing person cases in Poland
Category:Missing person cases in Portugal
Category:Missing person cases in Romania
Category:Missing person cases in Russia
Category:Missing person cases in Saudi Arabia
Category:Missing person cases in Scotland
Category:Missing person cases in Singapore
Category:Missing person cases in Somalia
Category:Missing person cases in South Africa
Category:Missing person cases in South America
Category:Missing person cases in Spain
Category:Missing person cases in Sweden
Category:Missing person cases in Switzerland
Category:Missing person cases in Syria
Category:Missing person cases in Thailand
Category:Missing person cases in Turkey
Category:Missing person cases in Uganda
Category:Missing person cases in Ukraine
Category:Missing person cases in Venezuela
Category:Missing person cases in Vietnam
Category:Missing person cases in Wales
Category:Missing person cases in Yemen
Category:Missing person cases in Yugoslavia
Category:Missing person cases in the Czech Republic
Category:Missing person cases in the Netherlands
Category:Missing person cases in the Ottoman Empire
Category:Missing person cases in the Philippines
Category:Missing person cases in the United Kingdom
Category:Missing person cases in the United States
Category:Missing scientists investigation
Category:Missing ships
Category:Missing ships of Australia
Category:Missing submarines
Category:Missing submarines of World War II
Category:Missing trains
Category:Moran family
Category:POW/MIA advocacy
Category:People declared dead in absentia
Category:People lost at sea
Category:Richard of Shrewsbury, Duke of York
Category:Search for Malaysia Airlines Flight 370
Category:Terrorist incidents by unknown perpetrators
Category:Unexplained_disappearances
Category:Unidentified American criminals
Category:Unidentified American murderers
Category:Unidentified American rapists
Category:Unidentified American serial killers
Category:Unidentified Australian serial killers
Category:Unidentified British criminals
Category:Unidentified British rapists
Category:Unidentified British serial killers
Category:Unidentified Canadian criminals
Category:Unidentified Japanese serial killers
Category:Unidentified criminals
Category:Unidentified murder victims
Category:Unidentified murder victims in the United Kingdom
Category:Unidentified murder victims in the United States
Category:Unidentified murderers
Category:Unidentified rapists
Category:Unidentified serial killers
Category:Unsolved airliner bombings
Category:Unsolved airliner bombings in the United States
Category:Unsolved arsons
Category:Unsolved crimes
Category:Unsolved crimes in Australia
Category:Unsolved crimes in Belize
Category:Unsolved crimes in Brazil
Category:Unsolved crimes in Canada
Category:Unsolved crimes in China
Category:Unsolved crimes in Costa Rica
Category:Unsolved crimes in England
Category:Unsolved crimes in Europe
Category:Unsolved crimes in France
Category:Unsolved crimes in Germany
Category:Unsolved crimes in India
Category:Unsolved crimes in Iraq
Category:Unsolved crimes in Ireland
Category:Unsolved crimes in Israel
Category:Unsolved crimes in Italy
Category:Unsolved crimes in Japan
Category:Unsolved crimes in Mexico
Category:Unsolved crimes in Nicaragua
Category:Unsolved crimes in Nigeria
Category:Unsolved crimes in Pakistan
Category:Unsolved crimes in Portugal
Category:Unsolved crimes in South Africa
Category:Unsolved crimes in Spain
Category:Unsolved crimes in Sri Lanka
Category:Unsolved crimes in Thailand
Category:Unsolved crimes in the Netherlands
Category:Unsolved crimes in the United Kingdom
Category:Unsolved crimes in the United States
Category:Unsolved mass murders
Category:Unsolved mass murders in California
Category:Unsolved mass murders in France
Category:Unsolved mass murders in Georgia (U.S. state)
Category:Unsolved mass murders in Illinois
Category:Unsolved mass murders in Northern Ireland
Category:Unsolved mass murders in Oregon
Category:Unsolved mass murders in Texas
Category:Unsolved mass murders in the United Kingdom
Category:Unsolved mass murders in the United States
Category:Unsolved murders
Category:Unsolved murders in Afghanistan
Category:Unsolved murders in Africa
Category:Unsolved murders in Angola
Category:Unsolved murders in Argentina
Category:Unsolved murders in Asia
Category:Unsolved murders in Australia
Category:Unsolved murders in Austria
Category:Unsolved murders in Bangladesh
Category:Unsolved murders in Belgium
Category:Unsolved murders in Belize
Category:Unsolved murders in Bosnia and Herzegovina
Category:Unsolved murders in Botswana
Category:Unsolved murders in Brazil
Category:Unsolved murders in Bulgaria
Category:Unsolved murders in Canada
Category:Unsolved murders in Chile
Category:Unsolved murders in China
Category:Unsolved murders in Croatia
Category:Unsolved murders in Cyprus
Category:Unsolved murders in Ecuador
Category:Unsolved murders in Egypt
Category:Unsolved murders in England
Category:Unsolved murders in Finland
Category:Unsolved murders in France
Category:Unsolved murders in Germany
Category:Unsolved murders in Greece
Category:Unsolved murders in Hungary
Category:Unsolved murders in Iran
Category:Unsolved murders in Iraq
Category:Unsolved murders in Ireland
Category:Unsolved murders in Italy
Category:Unsolved murders in Japan
Category:Unsolved murders in Libya
Category:Unsolved murders in London
Category:Unsolved murders in Malta
Category:Unsolved murders in Mexico
Category:Unsolved murders in Myanmar
Category:Unsolved murders in Namibia
Category:Unsolved murders in New Zealand
Category:Unsolved murders in Nigeria
Category:Unsolved murders in Northern Ireland
Category:Unsolved murders in Norway
Category:Unsolved murders in Pakistan
Category:Unsolved murders in Palau
Category:Unsolved murders in Poland
Category:Unsolved murders in Portugal
Category:Unsolved murders in Romania
Category:Unsolved murders in Russia
Category:Unsolved murders in Rwanda
Category:Unsolved murders in Scotland
Category:Unsolved murders in Serbia
Category:Unsolved murders in Singapore
Category:Unsolved murders in South Africa
Category:Unsolved murders in South America
Category:Unsolved murders in Spain
Category:Unsolved murders in Sri Lanka
Category:Unsolved murders in Sweden
Category:Unsolved murders in Turkey
Category:Unsolved murders in Ukraine
Category:Unsolved murders in Utah Territory
Category:Unsolved murders in Wales
Category:Unsolved murders in the Bahamas
Category:Unsolved murders in the Netherlands
Category:Unsolved murders in the Philippines
Category:Unsolved murders in the Russian Empire
Category:Unsolved murders in the Soviet Union
Category:Unsolved murders in the United States
Category:Victims of the Melbourne gangland killings
Category:Vietnam War POW/MIA issues
Category:Works about missing people
List of missing ships
List of people who disappeared mysteriously (1970s)
List of people who disappeared mysteriously (1980s)
List of people who disappeared mysteriously (1990s)
List of people who disappeared mysteriously (2000–present)
List of people who disappeared mysteriously at sea
List of unsolved deaths
List of unsolved murders (1900–1979)
List of unsolved murders (1980–1999)
List of unsolved murders (2000–present)
List of unsolved murders (before 1900)
List of unsolved murders in Belize
List_of_fugitives_from_justice_who_disappeared
Lists of unsolved murders

In [ ]:
erase_origin = ["Category:Castaways","Category:Highway of Tears","Category:Jack the Ripper","Category:Kidnapped Palestinian people",
                "Category:Lost and extinct musical instruments","Category:Melbourne gangland killings","Category:Moran family",
                "Category:POW/MIA advocacy","Category:Search for Malaysia Airlines Flight 370","Category:Vietnam War POW/MIA issues",
                "Category:Vietnam War POW/MIA issues","Category:Victims of the Melbourne gangland killings","Category:Works about missing people"]

to_add_page = [
    ("Black_Dahlia",0,"Unsolved murders in California"),
              ("Murder_of_Tupac_Shakur",0,"Unsolved murders in Nevada"),
               #("2007_Samjhauta_Express_bombings",0,
               ("Mary Celeste",0,"Unexplained disappearances"),
               ("Disappearance of Don Banfield",0,"Unsolved murders in London"),
               ("Jack the Ripper",0,"Unidentified British serial killers"),
               ("Malaysia Airlines Flight 370",0,"Missing aircraft")]

In [ ]:
rem_keys = []
for key, value in c1_pages_db.items():
  if value['origin_title'] in erase_origin:
    origin = value['origin_title']
    if key == origin[9:]:
      print("spared:"+key)
    else:
      rem_keys.append(keys)
print(len(rem_keys))
for i in rem_keys:
  _ = c1_pages_db.pop(i,None)

spared:Highway of Tears
76

In [ ]:
rem_keys

['Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste',
 'Mary Celeste']

In [ ]:
for i in rem_keys:
  _ = c1_pages_db.pop(i,None)

In [ ]:
"Mary Celeste" in cp_pages_db.keys()

True

In [ ]:
rem_keys = []
for key, value in cp_pages_db.items():
  if value['origin_title'] in erase_origin:
    origin = value['origin_title']
    if key == origin[9:]:
      print("spared:"+key)
    else:
      rem_keys.append(keys)
print(len(rem_keys))
for i in rem_keys:
  _ = cp_pages_db.pop(i,None)

NameError: name 'cp_pages_db' is not defined

In [ ]:
_ = cp_pages_db.pop('Moran family',None)

In [ ]:
error guard
wikipedia_queue = deque(to_add_page)
MAX_DEPTH = 1
run_crawler(limit=10000,force_visit=True) # Adjust limit as needed
save_progress() # Save results

Crawling: Black Dahlia
Crawling: Murder of Tupac Shakur
Crawling: Mary Celeste
Crawling: Disappearance of Don Banfield
Crawling: Jack the Ripper
Crawling: Malaysia Airlines Flight 370
Finished while loop
--- Progress Saved Successfully ---
Crawler stopped. Progress has been secured.
--- Progress Saved Successfully ---

In [ ]:
for p in to_add_page:
  content = pages_db.get(p[0],None)
  if content:
    cp_pages_db[p[0]] = content
  else:
    print("Not found "+p[0])

Not found Black_Dahlia
Not found Murder_of_Tupac_Shakur

In [ ]:
with open(f"{SAVEFILE_DIR}cleaning_pages_db_1.json", "w", encoding="utf-8") as f:
    json.dump(cp_pages_db, f, ensure_ascii=False, indent=4)

### Sections Cleaning

In [ ]:
with open(f"{SAVEFILE_DIR}cleaning_pages_db_1.json", "r", encoding="utf-8") as f:
    c1_pages_db = json.load(f)
print("--- Progress Loaded from Checkpoint ---")

--- Progress Loaded from Checkpoint ---

In [ ]:
len(c1_pages_db)

5076

In [ ]:
erase_origin = ["Category:Castaways","Category:Highway of Tears","Category:Jack the Ripper","Category:Kidnapped Palestinian people",
                "Category:Lost and extinct musical instruments","Category:Melbourne gangland killings","Category:Moran family",
                "Category:POW/MIA advocacy","Category:Search for Malaysia Airlines Flight 370","Category:Vietnam War POW/MIA issues",
                "Category:Vietnam War POW/MIA issues","Category:Victims of the Melbourne gangland killings","Category:Works about missing people"]

In [ ]:
rm_keys = []
for keys, value in c1_pages_db.items():
  if value['origin_title'] in erase_origin:
    print(keys)
    rm_keys.append(keys)

Asor
Chekker
Chrotta
Giga (instrument)
Gingras (instrument)
Gittith
Gue
Nevel (instrument)
Sambuca (instrument)
Suka (string instrument)
Symphonia
Poirot Investigates
The Labours of Hercules
Complement of HMS Bounty
Fat Tony & Co.
Keith Faure
Zarah Garde-Wilson
Mick Gatto
Evangelos Goussis
Murders of Terrence and Christine Hodson
Informer 3838
Tony Mokbel
Underbelly series 1
Carl Williams (criminal)
Highway of Tears
British Columbia Highway 16
Finding Dawn
Bobby Jack Fowler
Highway of Tears (film)
Edward Dennis Isaac
Cody Legebokoff
Bluefin-21
Joint Agency Coordination Centre
Ocean Infinity
West Ridge (ship)
Killing of Rami Ayyad
Kidnapping and murder of Mohammed Abu Khdeir
National Alliance of Families
National League of POW/MIA Families
POW bracelet
Rolling Thunder (organization)
The Saluting Marine
Ted Sampley
Vietnam War POW/MIA issue
Ark Project
Australians missing in action in the Vietnam War
Baron 52
The Code of Conduct and the Vietnam Prisoners of War
Defense Prisoner of War/Missing Personnel Office
Robert R. Garwood
Evelyn Grubb
Hanoi March
Operation Ivory Coast
Joint Casualty Resolution Center
Joint Personnel Recovery Center
Joint POW/MIA Accounting Command
John Kerry
A Matter of Time (Cook novel)
Mayaguez incident
US House and Senate career of John McCain (until 2000)
Operation Homecoming
Bob Smith (New Hampshire politician)
U.S.–Russia Joint Commission on POW/MIAs
Unclaimed (2013 film)
United States Senate Select Committee on POW/MIA Affairs
Jason Moran (criminal)
Judy Moran
Lewis Moran
Lewis Caine
Dino Dibra
Charles Hegyalji
Graham Kinniburgh
Victor Peirce
Andrew Veniamin
Frederick Abberline
Theodore Dyke Acland
Robert Anderson (Scotland Yard official)

In [ ]:
rm_keys

['Asor',
 'Chekker',
 'Chrotta',
 'Giga (instrument)',
 'Gingras (instrument)',
 'Gittith',
 'Gue',
 'Nevel (instrument)',
 'Sambuca (instrument)',
 'Suka (string instrument)',
 'Symphonia',
 'Poirot Investigates',
 'The Labours of Hercules',
 'Complement of HMS Bounty',
 'Fat Tony & Co.',
 'Keith Faure',
 'Zarah Garde-Wilson',
 'Mick Gatto',
 'Evangelos Goussis',
 'Murders of Terrence and Christine Hodson',
 'Informer 3838',
 'Tony Mokbel',
 'Underbelly series 1',
 'Carl Williams (criminal)',
 'Highway of Tears',
 'British Columbia Highway 16',
 'Finding Dawn',
 'Bobby Jack Fowler',
 'Highway of Tears (film)',
 'Edward Dennis Isaac',
 'Cody Legebokoff',
 'Bluefin-21',
 'Joint Agency Coordination Centre',
 'Ocean Infinity',
 'West Ridge (ship)',
 'Killing of Rami Ayyad',
 'Kidnapping and murder of Mohammed Abu Khdeir',
 'National Alliance of Families',
 'National League of POW/MIA Families',
 'POW bracelet',
 'Rolling Thunder (organization)',
 'The Saluting Marine',
 'Ted Sampley',
 'Vietnam War POW/MIA issue',
 'Ark Project',
 'Australians missing in action in the Vietnam War',
 'Baron 52',
 'The Code of Conduct and the Vietnam Prisoners of War',
 'Defense Prisoner of War/Missing Personnel Office',
 'Robert R. Garwood',
 'Evelyn Grubb',
 'Hanoi March',
 'Operation Ivory Coast',
 'Joint Casualty Resolution Center',
 'Joint Personnel Recovery Center',
 'Joint POW/MIA Accounting Command',
 'John Kerry',
 'A Matter of Time (Cook novel)',
 'Mayaguez incident',
 'US House and Senate career of John McCain (until 2000)',
 'Operation Homecoming',
 'Bob Smith (New Hampshire politician)',
 'U.S.–Russia Joint Commission on POW/MIAs',
 'Unclaimed (2013 film)',
 'United States Senate Select Committee on POW/MIA Affairs',
 'Jason Moran (criminal)',
 'Judy Moran',
 'Lewis Moran',
 'Lewis Caine',
 'Dino Dibra',
 'Charles Hegyalji',
 'Graham Kinniburgh',
 'Victor Peirce',
 'Andrew Veniamin',
 'Frederick Abberline',
 'Theodore Dyke Acland',
 'Robert Anderson (Scotland Yard official)']

In [ ]:
for i in rm_keys:
  a = c1_pages_db.pop(i,None)
  if not a:
    print("not remove "+i)

In [ ]:
len(c1_pages_db)

5076

In [ ]:
all_outer_section = set()

def print_outer_section(sections):
  for s in sections:
    #print(prev + s["title"])
    all_outer_section.add(s["title"])

for keys, value in c1_pages_db.items():
  sect_tree = value["sections_tree"]
  #print_section_tree(sect_tree,"")
  print_outer_section(sect_tree)

In [ ]:
all_outer_section = list(all_outer_section)
all_outer_section.sort()
for i in all_outer_section:
  print(i)

"Bodyhunters" documentary
"Brides on Tour" Project
"Fifty Mission Cap"
"French connection"
"Fritz" Johnson
"Hereditary prince" theory
"Historic Truth" version of events
"Rubbish" of Vincent
"Ruislip's Murder Mile"
"Sacrifice" of ritual artwork
"Seacroft"
"Stand your ground" laws
"Thirty-Seven Days of Peril"
"Toxic Truck"
"Yo me niego a rendirme"
#AmINext campaign
#BringBackOurGirls movement and protests
'Bloody April'
'Take It Down' tool
(October 1985) Broadwater Farm riot
10 August 1975
12 February 2002 terror alert
13 December 2008 incident
16 May 2009 incident
161 (Special Duties) Squadron
1776–1783
1831 murder
1865 fire at the Smithsonian
1882 voyage
18F
1900 crew disappearance
1908 Olympic results
1912 Arctic expedition
1917–18
1919 World Series
1921 Travers Stakes
1926 Ford Reliability NationalTour
1927 Circumnavigation of Australia
1928 Trans-Pacific flight
1928 Trans-Tasman flight
1929 "Coffee Royal" tragedy
1930s and beyond
1936 Olympic results
1938 mausoleum looting incident
1945 disappearance and investigation
1945–1946
1949 excavation
1951 waterfront dispute
1959 murder case
1960 deaths
1973 murders
1974 campaign
1976 activities
1977 doctors' strike
1980s and retirement
1980s developments
1981 coup attempt
1981 killing
1984 Florida perjury charges against Jaffe
1987–1991 forced disappearance
1991 elections and aftermath
1992 Carandiru massacre
1992 murder spree
1993 Bombay bombings
1993 plane crash
1997 border-crossing incident
1997 trial
1st voyage (1800–1801)
2 May: second murder
2 November 2024 protest and arrest
20 December: third murder
2000 murder inquiry
2001 GBM controversy
2005–2006 imprisonment
2006 "Great Lakes Dive Company" hoax
2006 Fox journalists kidnapping
2006 murder trial
2007 Karbala raid
2007 corruption charges
2008 Mumbai attacks
2008 election/change of government
2008 kidnapping
2009 Lanzarote Airport hunger strike
2009 anniversary protests
2009-10 investigation
2010 Accident Meets Another Same Tragedy
2010 Commercial Radio controversy
2011 Barschel case review
2011 detention in Libya
2012 developments
2013 appeal
2013 disappearance
2014 double homicide
2014 purge and reported execution
2014: Roldan's North Carolina arrest and trial
2015 Investigation probe
2015 Paris attackers
2015 developments
2016 Brussels attackers
2016 investigations
2017 developments
2017 presidential election
2018 Forces TV documentary
2018 Ocean Infinity search
2018 revival of investigation
2018 trial
2018–2019 Atlantic voyage
2019 Royal Commission
2019 court proceedings
2019 developments
2020 arrests
2020 assassination attempt by the US
2020 kidnapping
2020 murder investigation
2021 documentary and dig
2021 resurge
2022 Atlantic voyage
2022 documentary
2022 report
2023 Developments
2023 Naples version
2023 arrest
2023 developments
2023 indictments and 2025 trials
2023 reopening of the case
2024 arrest in Miami
2024 review
2025 arrest
2025–2026 Ocean Infinity search
2026 re-examination
21st century controversies
21st-century developments
21st-century searches
22 March: first murder
27 December 1973
2Pac's group Thug Life
2nd voyage (1802)
3rd voyage (1804–1805)
4th voyage (1806–1807)
5 July 1919
5 November 1979
5th voyage
6 September 2009 incident
7 October attacks
7th Cavalry
8 December 1984
8 June 2009 incident
8 March Group
81 Days Below Zero
9 January 2010 incident
911 call
A "practical Christian"
A Beautiful Child and Finding Sharon
A Death in Peking
A Few Good Men
A class of nine sisters
AFTV
AIDS activism
AMLO "truth commission"
ANO
ASU at UCLA
Abandonment
Abandonment of Jack Rosenthal
Abbreviation (botany)
Abduction
Abduction and Death
Abduction and aftermath
Abduction and captivity
Abduction and death
Abduction and killing
Abduction and legal developments
Abduction and life in North Korea
Abduction and manhunt
Abduction and missing person inquiry
Abduction and murder
Abduction and rendition to Egypt
Abduction and search
Abduction by ISIS
Abduction during the Iraq War
Abduction of Mehsud and his friends
Abduction theory
Abduction, murder, and investigation
Abdul Majud
Abe Sada panic
Abousfian Abdelrazik
Abu Taleb's visit to England
Abuse
Abuse and death
Academic career
Academic opinion
Access to Russian authorities
Accession
Accession to the throne and upbringing
Accident
Accident and aftermath
Accident and disappearance
Accident sequence
Accident victims
Accidental exposure theory
Account of her past from McAlphin
Accounts and speculation
Accounts of William's murder
Accounts of her past from Kelly
Accounts of the fatal climb
Accusations
Accusations against Algerian army
Accusations against Egyptian officials and trial
Accusations of Quinn family
Accusations of collective punishment
Accusations of criminal activity
Accusations of rape
Accusations of war crimes
Accused
Accusers and their motives
Achievements
Acquaintance
Acquaintance with Kichizō Ishida
Acquaintance with Kotovsky
Acquittal and honorable discharge
Acquittal of Karthigesu
Acquittal of suspect
Acrimony and separation
Acting boss
Acting versatility
Activation criteria
Active campaigns
Active service
Activism
Activism and career
Activism and missing person status
Activism and politics
Activism and songwriting
Activist involvement
Activist, negotiator and leader of the workers
Activities
Activities and legal issues
Activities before marriage
Activities during the Nigerian Army mutiny of July 1966 and October Kano massacres
Activities during the Nigerian Civil War (1967–1970)
Activities during the Second Chechen War
Activities from 1919 to 1924
Activities in London
Activities in Ukraine
Activities prior to death
Adaptation
Adaptations
Addiction and recovery
Additional English voyages
Additional information
Adelaide's family
Administration
Admiral Karpfanger
Admiral of the Ottoman Navy
Adolfo Scilingo's death flights
Adoption of the ritual version by the investigation
Adult behavior
Adult career
Adult life
Adult life and music career
Adulthood
Advances in forensic technology
Adventures
Advocacy
Advocacy and legacy
Advocacy work
Advocate for the poor
Advocates for missing people
Aerial Service
Aerial combat career
Aerial victories
Aerial victory credits
Africa interests
African circumnavigation attempts
After Stonewall
After World War I
After basketball
After imprisonment
After prison
After release
After release from Iran
After the Iranian Revolution
After the Iranian revolution
After the Revolution
After the escape
After the fall of the Hasina regime
After the genocide
After the kidnapping
After the trial
After the war
Aftermath
Aftermath and activism
Aftermath and consequences
Aftermath and developments
Aftermath and discovery
Aftermath and investigation
Aftermath and legacy
Aftermath and memorials
Aftermath and mystery about bomber's identity
Aftermath and political position
Aftermath and potential sightings
Aftermath and public debate
Aftermath and reactions
Aftermath and recovery
Aftermath and representation in other media
Aftermath and rewards
Aftermath and rumours
Aftermath and theories
Aftermath and trial
Aftermath and wreck
Aftermath of Delhi Accord
Aftermath of Mackay's murder
Aftermath of disappearance
Aftermath of kidnapping
Aftermath of the 12 October 1943 incident
Aftermath of the murder
Aftermath of the trial
Aftermath: 27 April 1984 – 5 February 1985
Aftermath: the anti-Masonic movement
Afterword
Agenda
Ahmad Motevaselian Memorial
Air France Flight 139
Air France robbery
Air crash
Air mail pilot
Air race
Air racing and record-breaking 1930s
Air victories
Aircraft
Aircraft Assigned
Aircraft crash
Airstrike
Aisenberg case
Al-Qaeda activities
Alan Decabral case
Alfred Potter
Ali Forney Center
Allegations
Allegations by An Phoblacht
Allegations in the poisoning of Alexander Litvinenko (2006) and libel suit (2010)
Allegations of British Government involvement
Allegations of Soviet involvement
Allegations of assassinations
Allegations of corruption
Allegations of forgery
Allegations of harassment
Allegations of involvement in the assassination of JFK
Allegations of police misconduct
Allegations of torture
Allegations of wider involvement
Alleged Loyalist paramilitary involvement
Alleged Russian government involvement
Alleged Son of Sam link
Alleged assassination attempts in London
Alleged assassinations of perpetrators
Alleged child abuse
Alleged claims of prophethood in childhood
Alleged crimes
Alleged criminal activities
Alleged drug smuggling
Alleged findings
Alleged flight to Malta
Alleged involvement in 2001 anthrax attacks and investigations
Alleged involvement in bombings
Alleged involvement in the JFK assassination
Alleged kidnappers
Alleged killer's confession letters
Alleged links to Al-Shabaab
Alleged links to Margaret Frame case
Alleged perpetrators
Alleged race issues
Alleged role in terror activities
Alleged role in the Lincoln conspiracy
Alleged sabotage of the "Southern Cross"
Alleged sightings
Alleged victims
Alliance with Zapata against Carranza, 1914–15
Alloura Wells's disappearance
Alternate suspects
Alternative explanations
Alternative suspect Douglas Franklin
Alternative theories
Alternative theory
Alton riot trial
Amadas–Barlowe expedition
Amateur career
Ambassador of Colombia to the United States
Ambassadors' plot
American Atheists
American Civil War
American years
An early clipper ship
Ana Kriégel
Analogous cases that do not involve missing persons
Analysis
Analysis and conclusions
Analysis by the Joint Investigation Team
Analysis of hydroacoustic data
Analysis of videos
Ancestors
Ancestry
Anchor stores
Andrew Stephen book controversy
Ang Soo Hoon's confession
Angie Housman
Angiolini Inquiry
Anglo-Boer War
Anglo-Irish Treaty
Animals
Ann Tennant
Announcement of a serial killer
Antecedents
Anthrax attacks
Anthrax investigation, post-death
Anthrax material
Anthrax vaccines
Anthropometry
Anti-corruption investigations
Anti-fascism
Anti-gravity research
Anti-seasick bed
Anti-war activism
Antibiotic resistance
Apologies from government employees
Apparent Tommy Lynn Sells confession
Apparent distress message discovery
Appeal
Appeal and acquittal
Appeal and compensation
Appeal and execution
Appeal and implications
Appeal and re-conviction
Appeal process
Appeal processes of Hill
Appeals
Appeals and execution
Appeals and exoneration
Appeals and exonerations
Appeals of Christopher Collings
Appeals of the duo
Appeals of the four
Appearance
Appearance and dimensions
Appearance in Steven Sotloff video
Appearance of the "ritual" version
Appellate proceedings
Application
Application to RAF
Applications
Applications and Practices
Appraisal and legacy
Apprehension and interrogation
Apprehension of suspect
Apprehension of the killer
Approach to comedy
April – May 2014
Aquila Airways 1954–1958
Arbitrary detention
Arbitration and compensation award
Archaeological research
Archaeological study
Archaeology and historical context
Archbishop's special envoy
Architecture
Architecture and equipment
Arctic Exploration
Arctic expeditions
Arctic exploration
Areas of usage
Arklow schooners
Armament
Armed Forces of Ukraine
Armed merchant cruiser
Armenian genocide
Arms
Army Air Forces
Army career and disappearance
Arranging staff and compositions
Arrest
Arrest and Assassination
Arrest and aftermath
Arrest and charges
Arrest and confession
Arrest and continuing investigation
Arrest and conviction
Arrest and conviction of Tony Agostini
Arrest and criminal charges
Arrest and death
Arrest and death of her father
Arrest and detention
Arrest and developments
Arrest and disappearance
Arrest and discovery
Arrest and enforced disappearance
Arrest and fate
Arrest and first trial
Arrest and flight
Arrest and guilty plea
Arrest and imprisonment
Arrest and interrogation
Arrest and investigation
Arrest and kidnapping trial
Arrest and legal proceedings
Arrest and prosecution
Arrest and repressions
Arrest and subsequent trial of Denise Williams
Arrest and the first-instance trial
Arrest and trial
Arrest and trial in Spain
Arrest and trial of David Boyd
Arrest and trial of Duane Davis
Arrest and trial of James King
Arrest and trial of Nils Gustafsson
Arrest for a tweet
Arrest in Canada and legal proceedings
Arrest in India
Arrest of Ahmed Chelh Gerj
Arrest of Dmitry Voroshilov
Arrest of Dwi Sumaji
Arrest of Hauptmann
Arrest of Larry Gibson
Arrest of Martin Ney
Arrest of Ou Biaofeng
Arrest of Robert Bayne
Arrest of Thurman Price in 2007
Arrest of a top suspect
Arrest of suspect and court proceedings
Arrest warrant
Arrest, investigations and aftermath
Arrest, trial and imprisonment
Arrest, trial and incarceration
Arrest, trial, and sentencing
Arrest, trials and imprisonment
Arrested at the Cenotaph
Arrests
Arrests and aftermath
Arrests and charges
Arrests and confessions
Arrests and convictions
Arrests and convictions of the perpetrators
Arrests and criminal charges
Arrests and deportation
Arrests and incarcerations
Arrests and repression against eKhenana
Arrests and sentencing
Arrests and torture of Emanuel Fairbairn
Arrests and trial
Arrests and trials
Arrests of Lamar and Ruth Vickerstaff
Arrests of the couple
Arrests of whistleblowers
Arrests, imprisonment, and torture
Arrival at Jekyll Island and publicity
Arrival at Riyadh
Arrival in New Lebanon
Arrival in Sligo
Arson
Arson and arrests of Lattimore, Leighton and Salih
Art and literature
Art and technique
Art studios in the World Trade Center
Art, entertainment and media
Artifact and commemorations
Artifacts
Artifacts and remains
Artist
Artistic career
Artistic work
Artistic works
Artistry
Artistry, style, and themes
Artists who sabotage their own work
Artwork
As F/V Pacesetter
As a barquentine
As a schooner
As an English crown jewel
As emperor
As the dredge Lady Escott
Ascents of peaks over 6000 meters
Ashley Brown's videos
Asmat artifacts and photographs
Aspects of the case
Assailant
Assassination
Assassination and attempts
Assassination and funeral
Assassination and investigation
Assassination and legacy
Assassination and remembrance
Assassination attempt
Assassination attempts and prosecution
Assassination of Bachir Gemayel
Assassination of Kotovsky
Assassination of Lumumba
Assassination of Sir Henry Wilson
Assassination plot
Assault
Assault charge
Assaults and perpetrator profile
Assessment
Assessment of foreign policy
Assistance of Scotland Yard
Assistance to Hamas
Associated cases
Associated crimes
Associated dog remains
Associates
Astan Quds chairmanship
At the Ontario Court of Appeal: 2001–2007
At the Supreme Court: the 1960s
Athletics
Athletics career (1963–1970)
Atlantic flight and disappearance
Atrocities
Atrocities and war crimes
Attack
Attack and death
Attack and response
Attack at 31 Connollystraße
Attack on Raymond Sigler
Attack on police
Attack, abduction, and aftermath
Attack, torture and murder in Tullycoora
Attacks
Attacks on the electrical grid in the United States
Attempted assassination
Attempted coup d'état
Attempted hostage negotiations
Attempted kidnapping and death
Attempted murder
Attempted murder of Brandon Boudreaux
Attempted transatlantic flight
Attempts at an independent investigation
Attestations
Attorney-General of Van Diemen's Land
Attribution
Audio recording
Auer arrested
August 2014 incident
August 24, 1951
Australasian Antarctic Expedition
Australia
Australia-China dispute, cooperation, and conviction
Australian National Airways
Authenticity
Author
Authorities
Authorship
Autopsy
Autopsy and forensic evidence
Autopsy findings
Autopsy results
Auxiliary ship
Avenger wreckage mistaken for Flight 19 and other searches
Avi Sasportas
Aviation
Aviation career
Aviation career and marriage
Aviation enthusiast
Aviation explorer
Aviation firsts for the motion pictures
Aviation pioneer
Aviator
Award and tomb
Awards and legacy
Awareness effort
Ayoola Ajayi
B-24 incident and survival
BJS directors
Ba'ath politics
Background
Background & education
Background and IRA activity
Background and allegation
Background and attempted hit
Background and before disappearance story
Background and case
Background and death
Background and disappearance
Background and dispute
Background and early career
Background and early training
Background and education
Background and imprisonment
Background and influence
Background and investigation
Background and lead-up
Background and mission
Background and murder
Background and murders
Background and planning
Background and role in genocide
Background information
Background into disappearance
Background of Aw
Background of Lai Ying Xin
Background of Lars Mittank
Background of founding the New Hampshire colony
Background of the shooting
Background of victim
Background to the dispute
Background to the frozen meat shipment
Background, arrest, and sentencing
Background, disappearance, and aftermath
Background, early life and career
Backgrounds of the kidnappers
Backing and opposing Ben Bella
Backlash and impact
Baháʼí life
Balloon bomb deaths
Balloon design
Ballooning
Baloch Yakjehti Committee's March Initiatives and Declarations
Banco Ambrosiano scandal
Bancourt murdered after being kidnapped
Bandon phone recordings
Bangalore and Burma
Bank accounts of Rizwanur's relatives
Banking and public speaking career
Bankruptcy and estate
Barataria
Barron Report
Barthometer
Base Line Road
Baseball career
Basketball career
Batalanda Commission
Bathymetric survey (May–December 2014)
Battle
Battle against John of England
Battle of France, 1940
Battle of Sultan Yacoub and captivity
Battle of the Coral Sea
Battle of the North Cape
Battle off Samar
Battle with Constellation
Battles of Charles XII
Beatification
Beating of Lamar Howard
Beer Hall Putsch
Before her death
Before shooting
Before the 1900 massacre
Before the Iranian Revolution
Beginnings
Beilis and other involved individuals' future
Bella Wright
Belongings
Beria
Berlin 1945
Bert Spencer
Bestowal
Betrayal
Betrayal of Jesus
Between the wars
Between wars (1905–1914)
Biafran War involvement
Biblical account
Bigamy trial
Bilevičius' death
Biographical and career information
Biographical details
Biographical profile
Biographical record
Biographies
Biography
Biography and career
Biography and death
Biography and disappearance
Biography of Eliza Samudio
Biography of Zbigniew Huminski
Biography of the brothers
Biography/memories
Biosocial criminology and other analysis of environmental factors
Birth
Birth and early career
Birth and early life
Birth and early years, 1957–1959
Birth and family
Birth and origins
Birth and siblings
Birth and youth
Bishop and Archbishop
Bishop of Samara and Stavropol
Bit-part Hollywood career
Blackbirding
Blackpool
Blackpool F.C. Hall of Fame
Blame
Blencathra
Blenheim
Blenheim again & fate
Blitar revolt
Blockade runner Gibraltar
Blog ‘ProgramThink’ and Project ‘zhao’
Bloody Sunday
Board of directors
Boating accident and disappearance
Bodies
Body
Body discovered
Body discovered and investigation
Body discovered and murder charge
Body discovery
Body discovery and murder investigation
Body found
Body found and homicide investigation
Body moved
Body preservation
Boer War
Bombing
Bombing and result
Bombings
Book La danza de los cuervos
Book by Paul Klebnikov
Book of Mormon
Book on Freemasonry
Border guard service
Boris Nemtsov Plaza
Borough council investigation and disciplinary hearing
Bosnian War
Boss
Bosworth and aftermath
Bottecchia bicycles
Bought for the royal collection
Boundaries
Bout with Clay/Ali
Boxing career
Boxing manager
Braganstown Massacre
Brandon's Law
Brazilian service
Break with Carranza, 1914
Breaking the silence
Breakthrough
Breda Museum's Lost and Found exhibition
Brian Lunn Field as a prime suspect
Brian Winchester's kidnapping of Denise
Brinchang remains theory
Brink's-Mat robbery
British career
British letter of marque
British privateer
British service
British service and loss
Broader impact
Brooklyn crime boss
Brooks's escape
Brother André's heart
Brothers
Buchanan administration
Buenos Aires Province
Bug bounty
Building
Building and early career
Building and registration
Building, registration and identification
Bundeswehr's role model
Burglary and destruction
Burial

In [ ]:
error guard
with open("section_name.txt", "w", encoding="utf-8") as f:
    for title in all_outer_section:
        f.write(title + "\n")

In [ ]:
discardable_sections = [
    "Accolades",    "Acknowledgements",    "Additional links",    "Album",    "Albums",    "Appendices",    "Archival collections",    "Archives",    "Archives At",    "Articles",    "Articles or Books on Turner",    "Articles written",    "Autobiography: The Contras' Valley Forge",
    "Award",    "Award Citations",    "Awards",    "Awards and Decorations",    "Awards and accolades",    "Awards and citations",    "Awards and commendation",    "Awards and decorations",    "Awards and honors",    "Awards and honours",    "Awards and memory",    "Awards and nominations",    "Awards and recognition",    "Awards and showings",    "Awards and tributes",    "Awards, decorations, and honors",
    "BAA/NBA career statistics",    "Bibliographies",    "Bibliography",    "Biographical works",    "Book",    "Book publication",    "Books",    "Books about Abani Chakravarty",    "Books about Edwards",    "Books and films about Litvinenko",    "Books and films about the Oakes case",    "Books and movie",    "Books and movies",    "Books and publications",    "Books by Earhart",
    "Books by or about Murray O'Hair",    "Books, documentaries and media",    "Career statistics",    "Championships",    "Championships and accomplishments",    "Cinematic adaptations",    "Citation",    "Citations",    "Citations and references",    "Citations of honors",    "Cited sources",    "Cited works and further reading",
    "Collections",    "Collections and exhibitions",    "Compilation contributions",    "Compilations",    "Compositions",    "Contents",    "Creative works",    "Cultural depictions",    "Cultural references",    "Databases",    "Dedicated taxa",
    "Depictions in art and literature",    "Depictions in fiction",    "Depictions in film",    "Depictions in music and popular culture",    "Depictions in popular culture",    "Discography",    "Discography and writing credits",    "Documentaries",    "Documentary",    "Documentary film",    "Documentary films",    "EP",    "Electoral history",
    "Electoral record",    "Engravings from John Pine's 1739 publication",    "Eponym",    "Eponyms",    "Eponymy",    "Exhibition history",    "Exhibitions",    "Exhibitions, reception and impact",    "Explanatory notes",    "External",    "External Links",    "External link",
    "External links",    "External links and further reading",    "External links and sources",    "External websites",    "Figures",    "Film adaptation",    "Film adaptations",    "Film adaptations and documentaries",    "Film adaptations based upon the events",
    "Filmography",    "Filmography (selection)",    "Films",    "Films about Calvi's death",    "Films about the Johann Orth mystery",    "Films and documentaries",    "Films and music",    "Footnote",    "Footnotes",    "Footnotes and references",    "Foreign honours",
    "Further reading",    "Further references",    "Gallery",    "Genealogical table",    "General and cited references",    "General and cited sources",    "General references",    "General sources",    "George Cross award",    "George Cross citation",    "Heraldry",    "His books",    "Honours",    "Honours and arms",    "Honours and awards",    "Honours and family",
    "Honours and legacy",    "Honours and memorials",    "Honours and recognition",    "Honours and tributes",    "Image gallery",    "In art",    "In art and media",    "In books",    "In fiction",    "In fiction and popular culture",    "In film",    "In literature",    "In literature and the arts",    "In literature and theater",
    "In literature, media and popular culture",    "In media",    "In media and culture",    "In other media and popular culture",    "In popular culture",    "In popular culture and mass media",    "In popular culture and media",    "In popular media",    "Individual publications",    "Informational notes",    "Inline citations",    "Institutions with his works",    "Library",    "List of characters",
    #"List of deceased players",
    "List of tours",    "List of victories",    "List of works",    "Lists of Wikipedia articles on notable destroyed artworks",    "Literary activity",    "Literary archives",
    "Literary career",    "Literary contributions",    "Literary depictions",    "Literary relevance",    "Literary works",    "Literary writer",    "Literature",    "Literature and other cultural influences",
    "Managerial statistics",    "Medal of Honor citation",    "Memorial events",    "Memorial fund",    "Memorial seat",    "Memorial services",    "Memorial stones in Gallehus",    "Memorial surfing invitational",    "Memorials",
    "Memorials and legacy",    "Memorials and other legacies",    "Mixed martial arts record",    "Monuments and memorials",    "Monument to Laporte",    "Monument to Morgan",    "Movies with DeLay",    "Multilingual editions",    "Musical pieces",    "Namesake",    "Namesakes",    "Namesake honors",
    "Navy Cross citation",    "Newspaper references",    "Note",    "Notes",    "Notes and citations",    "Notes and references",    "Novels",    "Other reading",    "Other references",    "Other websites",    "Other works",    "Paintings",    "Patents",    "Patents and cameras",
    "Personal bests",    "Photographs",    "Plays",    "Plot summary",    "Podcasts",    "Podcasts and documentaries",    "Pop culture",    "Popular culture",    "Popular songs",    "Portrayal in film",    "Portrayal in media",    "Portrayal in movies",    "Portrayal in popular media",    "Portrayals",    "Portrayals and cultural references",
    "Portrayals and references in media",    "Portrayals in fiction",    "Portrayals in film",    "Postage stamp",    "Postscript",    "Posthumous awards and honours",    "Posthumous honours",    "Posthumous publications",    "Posthumous releases",
    "Precursor publications",    "Primary sources",    "Private art collections",    "Professional boxing record",    "Public collections (selection)",    "Publications",    "Publications by Berezovsky",    "Published works",    "Published works by Peter V. Verigin",    "Publishing",    "Quotations",    "Quote",    "Quotes",    "Radio career",
    "Radio credits",    "Radio documentaries",    "Radio documentary",    "Recordings",    "References",    "References and further reading",    "References and notes",    "References in Abrahamic religions",    "References in books and plays",    "References in media",    "References in pop culture",    "References in popular culture",    "Related books",    "Related reading",
    "Related works",    "Replica",    "Replica vessels",    "Replicas",    "Replicas and imitations",    "Representation in art and media",    "Representation in film and literature",    "Representation in other media",    "Representation in popular culture",    "Representations in contemporary art",    "Representations in culture and media",    "RSPCA Purple Cross Award",
    "See Also",    "See also",    "Selected articles in collective works",    "Selected bibliography",    "Selected filmography",    "Selected groups",    "Selected media",    "Selected publications",    "Selected videography",    "Selected works",    "Selective list of works",
    "Singles",    "Sister cities",    "Songs about Yokota",    "Sources",    "Sources and bibliograpahy",    "Sources and bibliography",    "Sources and notes",
    "Sources cited",    "Succession table",    "Table of contents",    "Televised documentaries and dramas",    "Television",    "Television career",    "Television documentaries",    "Television documentary",    "Television movies",    "Tribute",    "Tribute website",    "Tributes",    "Tributes and political reactions",    "Tributes and public reaction",    "Tributes to Ananda Mahidol",
    "Tributes to Marin Preda",    "Translation notes",    "Translations",    "Translations of Preda's work",    "Unreleased work",    "Verse",    "Verses",    "Victoria Cross citation",    "Videography",    "Wallpapers",    "Website on Abani Chakravarty",    "Works",
    "Works about Berezovsky",    "Works by Amundsen",    "Works cited",    "Works consulted",    "Works related to García Lorca",    "Works, editions and recordings",    "World Championship results",    "World Cup results",    "Writing",    "Writing and translation",
    "Writings",    "Writings and awards",    "Written works involving Paul Crampel"
]

In [ ]:
discardable_sections = [s.lower() for s in discardable_sections]

In [ ]:
for keys, value in c1_pages_db.items():
  sect_tree = value["sections_tree"]
  value["sections_tree"] = [d for d in sect_tree if d.get('title').lower() not in discardable_sections]

In [ ]:
with open(f"{SAVEFILE_DIR}cleaning_pages_db_2.json", "w", encoding="utf-8") as f:
    json.dump(c1_pages_db, f, ensure_ascii=False, indent=4)

In [ ]:
error guard
all_sections = set()
def print_section_tree(sections, prev=""):
  for s in sections:
    #print(prev + s["title"])
    all_sections.add(prev + s["title"])
    for c in s["content"]:
      if type(c) is list:
        print_section_tree(c,prev=f"{prev}{s["title"]} > ")

print(len(all_sections))
all_sections = list(all_sections)
all_sections.sort()
for i in all_sections[:5000]:
  print(i)

### Further Page Cleaning

In [ ]:
with open(f"{SAVEFILE_DIR}cleaning_pages_db_2.json", "r", encoding="utf-8") as f:
    c2_pages_db = json.load(f)
print("--- Progress Loaded from Checkpoint ---")

--- Progress Loaded from Checkpoint ---

In [ ]:
all_title = list(c2_pages_db.keys())
with open("page_title.txt", "w", encoding="utf-8") as f:
    for title in all_title:
        f.write(title + "\n")

In [ ]:
page_origin = set()
for key, value in c2_pages_db.items():
  page_origin.add(value['origin_title'])
page_origin = list(page_origin)
page_origin.sort()
for i in page_origin:
  print(i)

Category:1490s missing person cases
Category:1500s missing person cases
Category:1570s missing person cases
Category:1580s missing person cases
Category:1590s missing person cases
Category:1620s missing person cases
Category:1670s missing person cases
Category:1700s missing person cases
Category:1730s missing person cases
Category:1790s missing person cases
Category:17th-century missing person cases
Category:1800s missing person cases
Category:1810s missing person cases
Category:1820s missing person cases
Category:1830s missing person cases
Category:1840s missing person cases
Category:1850s missing person cases
Category:1860s missing person cases
Category:1870s missing person cases
Category:1880s missing person cases
Category:1890s missing person cases
Category:1900s missing person cases
Category:1910s missing person cases
Category:1920s missing person cases
Category:1930s missing person cases
Category:1940s missing person cases
Category:1950s missing person cases
Category:1960s missing person cases
Category:1970s missing person cases
Category:1980s missing person cases
Category:1990s missing person cases
Category:2000s missing person cases
Category:2001 anthrax attacks
Category:2010s missing person cases
Category:2020s missing person cases
Category:20th-century missing person cases
Category:21st-century missing person cases
Category:Aerial disappearances
Category:Aerial disappearances of military personnel in action
Category:Bermuda Triangle
Category:Disappeared journalists
Category:Enforced disappearances
Category:Enforced disappearances in Argentina
Category:Enforced disappearances in Bangladesh
Category:Enforced disappearances in Belarus
Category:Enforced disappearances in Cambodia
Category:Enforced disappearances in Chile
Category:Enforced disappearances in China
Category:Enforced disappearances in Egypt
Category:Enforced disappearances in India
Category:Enforced disappearances in Iran
Category:Enforced disappearances in Northern Ireland
Category:Enforced disappearances in Pakistan
Category:Enforced disappearances in Sri Lanka
Category:Enforced disappearances in Venezuela
Category:Enforced disappearances in the Philippines
Category:Enforced disappearances in the Soviet Union
Category:Formerly missing people
Category:Lost buildings and structures
Category:Lost explorers
Category:Lost objects
Category:Lost sailing vessels
Category:Lost works of art
Category:Malaysia Airlines Flight 370
Category:Mass disappearances
Category:Mexican missing people activists
Category:Military personnel missing in action
Category:Missing American children
Category:Missing American people
Category:Missing Argentine children
Category:Missing Argentine people
Category:Missing Austrian people
Category:Missing Belgian people
Category:Missing Brazilian people
Category:Missing British people
Category:Missing Canadian children
Category:Missing Canadian people
Category:Missing Chinese people
Category:Missing Colombian people
Category:Missing English people
Category:Missing Finnish people
Category:Missing French children
Category:Missing French people
Category:Missing German children
Category:Missing German people
Category:Missing Indian people
Category:Missing Indonesian people
Category:Missing Iranian people
Category:Missing Irish people
Category:Missing Israeli people
Category:Missing Italian children
Category:Missing Italian people
Category:Missing Japanese people
Category:Missing Malaysian people
Category:Missing New Zealand people
Category:Missing Nigerian people
Category:Missing Norwegian people
Category:Missing Pakistani people
Category:Missing Palestinian people
Category:Missing Russian people
Category:Missing Scottish people
Category:Missing South African people
Category:Missing South Korean people
Category:Missing Sri Lankan people
Category:Missing Swedish people
Category:Missing Swiss people
Category:Missing Syrian people
Category:Missing Ugandan people
Category:Missing Ukrainian people
Category:Missing air passengers
Category:Missing aircraft
Category:Missing and Murdered Indigenous Women and Girls activists
Category:Missing aviators
Category:Missing children
Category:Missing fugitives
Category:Missing gangsters
Category:Missing in action of World War I
Category:Missing in action of World War II
Category:Missing people
Category:Missing people activists
Category:Missing people identified through genetic genealogy
Category:Missing people organizations based in the United States
Category:Missing person cases in Afghanistan
Category:Missing person cases in Africa
Category:Missing person cases in Argentina
Category:Missing person cases in Asia
Category:Missing person cases in Australia
Category:Missing person cases in Austria
Category:Missing person cases in Azerbaijan
Category:Missing person cases in Bangladesh
Category:Missing person cases in Belgium
Category:Missing person cases in Brazil
Category:Missing person cases in British Columbia
Category:Missing person cases in Cambodia
Category:Missing person cases in Canada
Category:Missing person cases in Chile
Category:Missing person cases in China
Category:Missing person cases in Colombia
Category:Missing person cases in Cuba
Category:Missing person cases in Denmark
Category:Missing person cases in Egypt
Category:Missing person cases in England
Category:Missing person cases in Europe
Category:Missing person cases in Finland
Category:Missing person cases in France
Category:Missing person cases in Germany
Category:Missing person cases in Greece
Category:Missing person cases in Guatemala
Category:Missing person cases in Haiti
Category:Missing person cases in Hong Kong
Category:Missing person cases in Hungary
Category:Missing person cases in Iceland
Category:Missing person cases in India
Category:Missing person cases in Indonesia
Category:Missing person cases in Iran
Category:Missing person cases in Iraq
Category:Missing person cases in Ireland
Category:Missing person cases in Israel
Category:Missing person cases in Italy
Category:Missing person cases in Japan
Category:Missing person cases in Lebanon
Category:Missing person cases in Libya
Category:Missing person cases in London
Category:Missing person cases in Malaysia
Category:Missing person cases in Mexico
Category:Missing person cases in Morocco
Category:Missing person cases in Nepal
Category:Missing person cases in New Zealand
Category:Missing person cases in Nigeria
Category:Missing person cases in North America
Category:Missing person cases in Northern Ireland
Category:Missing person cases in Norway
Category:Missing person cases in Pakistan
Category:Missing person cases in Paraguay
Category:Missing person cases in Poland
Category:Missing person cases in Portugal
Category:Missing person cases in Romania
Category:Missing person cases in Russia
Category:Missing person cases in Saudi Arabia
Category:Missing person cases in Scotland
Category:Missing person cases in Singapore
Category:Missing person cases in Somalia
Category:Missing person cases in South Africa
Category:Missing person cases in South America
Category:Missing person cases in Spain
Category:Missing person cases in Sweden
Category:Missing person cases in Switzerland
Category:Missing person cases in Syria
Category:Missing person cases in Thailand
Category:Missing person cases in Turkey
Category:Missing person cases in Uganda
Category:Missing person cases in Ukraine
Category:Missing person cases in Venezuela
Category:Missing person cases in Vietnam
Category:Missing person cases in Wales
Category:Missing person cases in Yemen
Category:Missing person cases in Yugoslavia
Category:Missing person cases in the Czech Republic
Category:Missing person cases in the Netherlands
Category:Missing person cases in the Ottoman Empire
Category:Missing person cases in the Philippines
Category:Missing person cases in the United Kingdom
Category:Missing person cases in the United States
Category:Missing scientists investigation
Category:Missing ships
Category:Missing ships of Australia
Category:Missing submarines
Category:Missing submarines of World War II
Category:Missing trains
Category:People declared dead in absentia
Category:People lost at sea
Category:Richard of Shrewsbury, Duke of York
Category:Terrorist incidents by unknown perpetrators
Category:Unexplained_disappearances
Category:Unidentified American criminals
Category:Unidentified American murderers
Category:Unidentified American rapists
Category:Unidentified American serial killers
Category:Unidentified Australian serial killers
Category:Unidentified British criminals
Category:Unidentified British rapists
Category:Unidentified British serial killers
Category:Unidentified Canadian criminals
Category:Unidentified Japanese serial killers
Category:Unidentified criminals
Category:Unidentified murder victims
Category:Unidentified murder victims in the United Kingdom
Category:Unidentified murder victims in the United States
Category:Unidentified murderers
Category:Unidentified rapists
Category:Unidentified serial killers
Category:Unsolved airliner bombings
Category:Unsolved airliner bombings in the United States
Category:Unsolved arsons
Category:Unsolved crimes
Category:Unsolved crimes in Australia
Category:Unsolved crimes in Belize
Category:Unsolved crimes in Brazil
Category:Unsolved crimes in Canada
Category:Unsolved crimes in China
Category:Unsolved crimes in Costa Rica
Category:Unsolved crimes in England
Category:Unsolved crimes in Europe
Category:Unsolved crimes in France
Category:Unsolved crimes in Germany
Category:Unsolved crimes in India
Category:Unsolved crimes in Iraq
Category:Unsolved crimes in Ireland
Category:Unsolved crimes in Israel
Category:Unsolved crimes in Italy
Category:Unsolved crimes in Japan
Category:Unsolved crimes in Mexico
Category:Unsolved crimes in Nicaragua
Category:Unsolved crimes in Nigeria
Category:Unsolved crimes in Pakistan
Category:Unsolved crimes in Portugal
Category:Unsolved crimes in South Africa
Category:Unsolved crimes in Spain
Category:Unsolved crimes in Sri Lanka
Category:Unsolved crimes in Thailand
Category:Unsolved crimes in the Netherlands
Category:Unsolved crimes in the United Kingdom
Category:Unsolved crimes in the United States
Category:Unsolved mass murders
Category:Unsolved mass murders in California
Category:Unsolved mass murders in France
Category:Unsolved mass murders in Georgia (U.S. state)
Category:Unsolved mass murders in Illinois
Category:Unsolved mass murders in Northern Ireland
Category:Unsolved mass murders in Oregon
Category:Unsolved mass murders in Texas
Category:Unsolved mass murders in the United Kingdom
Category:Unsolved mass murders in the United States
Category:Unsolved murders
Category:Unsolved murders in Afghanistan
Category:Unsolved murders in Africa
Category:Unsolved murders in Angola
Category:Unsolved murders in Argentina
Category:Unsolved murders in Asia
Category:Unsolved murders in Australia
Category:Unsolved murders in Austria
Category:Unsolved murders in Bangladesh
Category:Unsolved murders in Belgium
Category:Unsolved murders in Belize
Category:Unsolved murders in Bosnia and Herzegovina
Category:Unsolved murders in Botswana
Category:Unsolved murders in Brazil
Category:Unsolved murders in Bulgaria
Category:Unsolved murders in Canada
Category:Unsolved murders in Chile
Category:Unsolved murders in China
Category:Unsolved murders in Croatia
Category:Unsolved murders in Cyprus
Category:Unsolved murders in Ecuador
Category:Unsolved murders in Egypt
Category:Unsolved murders in England
Category:Unsolved murders in Finland
Category:Unsolved murders in France
Category:Unsolved murders in Germany
Category:Unsolved murders in Greece
Category:Unsolved murders in Hungary
Category:Unsolved murders in Iran
Category:Unsolved murders in Iraq
Category:Unsolved murders in Ireland
Category:Unsolved murders in Italy
Category:Unsolved murders in Japan
Category:Unsolved murders in Libya
Category:Unsolved murders in London
Category:Unsolved murders in Malta
Category:Unsolved murders in Mexico
Category:Unsolved murders in Myanmar
Category:Unsolved murders in Namibia
Category:Unsolved murders in New Zealand
Category:Unsolved murders in Nigeria
Category:Unsolved murders in Northern Ireland
Category:Unsolved murders in Norway
Category:Unsolved murders in Pakistan
Category:Unsolved murders in Palau
Category:Unsolved murders in Poland
Category:Unsolved murders in Portugal
Category:Unsolved murders in Romania
Category:Unsolved murders in Russia
Category:Unsolved murders in Rwanda
Category:Unsolved murders in Scotland
Category:Unsolved murders in Serbia
Category:Unsolved murders in Singapore
Category:Unsolved murders in South Africa
Category:Unsolved murders in South America
Category:Unsolved murders in Spain
Category:Unsolved murders in Sri Lanka
Category:Unsolved murders in Sweden
Category:Unsolved murders in Turkey
Category:Unsolved murders in Ukraine
Category:Unsolved murders in Utah Territory
Category:Unsolved murders in Wales
Category:Unsolved murders in the Bahamas
Category:Unsolved murders in the Netherlands
Category:Unsolved murders in the Philippines
Category:Unsolved murders in the Russian Empire
Category:Unsolved murders in the Soviet Union
Category:Unsolved murders in the United States
List of missing ships
List of people who disappeared mysteriously (1970s)
List of people who disappeared mysteriously (1980s)
List of people who disappeared mysteriously (1990s)
List of people who disappeared mysteriously (2000–present)
List of people who disappeared mysteriously at sea
List of unsolved deaths
List of unsolved murders (1900–1979)
List of unsolved murders (1980–1999)
List of unsolved murders (2000–present)
List of unsolved murders (before 1900)
List of unsolved murders in Belize
List_of_fugitives_from_justice_who_disappeared
Lists of unsolved murders
Missing aircraft
Unexplained disappearances
Unidentified British serial killers
Unsolved murders in London

In [ ]:
discarded_pages = [
    "Cold case",
    "Missing person",
    "Office on Missing Persons",
    "Anthropological criminology",
    "Presumption of death",
    "Bermuda",
    "Sargasso Sea",
    "Template:Bermuda Triangle",
    "Missing children",
    "Unreported missing",
    "Missing white woman syndrome",
    "National Missing Children's Day",
    "Latter Day Saint movement and engraved metal plates",
    "Terrorism in Canada",
    "Miscarriage of justice",
    "Draft:Santa Fe County Jane Doe",
    "Michael Collins (Irish leader)",
    "Zachary Taylor",
    "Crime clearance rate",
    "Crime statistics",
    "Cybercrime",
    "Samuel Liddell MacGregor Mathers",
    "Emil Hácha",
    "Crime mapping",
    "Crime science",
    "National Incident-Based Reporting System",
    "Dark figure of crime",
    "Bureau of Justice Statistics",
    "American Society of Criminology",
    "Quantitative methods in criminology",
    "Computational criminology",
    "Victimisation",
    "Cultural criminology",
    "Unsolved murder",
    "Bibliography of sociology",
    "Criminology",
    "Evidence-based policing",
    "Women's fear of crime",
    "Crime harm index",
    "Predictive policing",
    "Unsolved crime",
    "Template:Criminology",
    "Shawn Hornbeck Foundation",
    "Asian Federation Against Involuntary Disappearances",
    "The Emergency (India)",
    "National Commission for the Missing (Syria)",
    "MIA Hunters",
    "Hainan Island incident",
    "Missing in action",
    "Madres buscadoras",
    "Abuja Area Mama",
    "Cebu City",
    "Manchester, Calgary",
    "Prostitution in Rwanda",
    "Rainbow Honor Walk",
    "Adventures with Purpose",
    "Aguilas del Desierto",
    "Black and Missing Foundation",
    "Defense POW/MIA Accounting Agency",
    "The Doe Network",
    "FBI Laboratory",
    "International Centre for Missing & Exploited Children",
    "Laura Recovery Center",
    "Mattie's Call",
    "National Center for Missing & Exploited Children",
    "National Child Victim Identification Program",
    "National Crime Information Center",
    "National Missing and Unidentified Persons System",
    "Office of Children's Issues",
    "Office to Monitor and Combat Trafficking in Persons",
    "Outpost for Hope",
    "Polly Klaas Foundation",
    "Sahnish Scouts",
    "Silver Alert",
    "Texas EquuSearch",
    "Trans Doe Task Force",
    "University of North Texas Center for Human Identification",
    "DNA Doe Project",
    "Reported Missing (TV series)",
    "Vanished (British TV series)",
    "Sensing Murder",
    "Fear of crime",
    "Jōhatsu",
    "Mayer Daak",
    "Voice for Baloch Missing Persons",
    "FUNDENL",
    "Grandmothers of Plaza de Mayo",
    "HIJOS",
    "Independent Commission for the Location of Victims' Remains",
    "Henry VII Chapel",
    "Ludlow Castle",
    "St John's Abbey, Colchester",
    "St Stephen's Chapel",
    "St George's Chapel, Windsor Castle",
    "Titulus Regius",
    "History of the Indian Tribes of North America",
    "Harley Street",
    "Zoroaster",
    "Judas Iscariot",
    "Peter III of Russia",
    "Haile Selassie",
    "Venustiano Carranza",
    "Liaquat Ali Khan",
    "Michael Collins (Irish leader)",
    "Pat Garrett",
    "Adolph Dubs",
    "Charles XII of Sweden",
    "Agnès Sorel",
    "Zannanza",
    "Prostitution in Rwanda"
]

In [ ]:
for p in discarded_pages:
  a = c2_pages_db.pop(p,None)
  if not a:
    print("not found "+p)

not found Michael Collins (Irish leader)
not found Prostitution in Rwanda

In [ ]:
error guard
#manual
a = c2_pages_db.pop("Prostitution in Rwanda",None)
a

In [ ]:
c2_pages_db["Jack the Ripper"]

{'origin_title': 'Unidentified British serial killers',
 'url': 'https://en.wikipedia.org/wiki/Jack_the_Ripper',
 'last_update_text': 'This page was last edited on 10 May 2026, at 03:41(UTC).',
 'summary': 'Jack the Ripper was an unidentified serial killer active in and around the impoverished Whitechapel district of London, England, in 1888. In both criminal case files and the contemporaneous journalistic accounts, the killer was also called the Whitechapel Murderer and Leather Apron.\nAttacks ascribed to Jack the Ripper typically involved women working as prostitutes who lived in the slums of the East End of London. Their throats were cut prior to abdominal mutilations. The removal of internal organs from at least three of the victims led to speculation that the killer had some anatomical or surgical knowledge. Rumours that the murders were connected intensified in September and October 1888, and numerous letters were received by media outlets and Scotland Yard from people purporting to be the murderer.\nThe name "Jack the Ripper" originated in the "Dear Boss letter" written by someone claiming to be the murderer, which was disseminated in the press. The letter is widely believed to have been a hoax and may have been written by journalists to heighten interest in the story and increase their newspapers\' circulation. Another, the "From Hell letter", was received by George Lusk of the Whitechapel Vigilance Committee and came with half a preserved human kidney, purportedly taken from one of the victims. The public came to believe in the existence of a single serial killer known as Jack the Ripper, mainly because of both the extraordinarily brutal nature of the murders and extensive media coverage of the crimes.\nExtensive newspaper coverage bestowed enduring international notoriety on the Ripper, and the legend solidified. A police investigation into a series of eleven brutal murders committed in Whitechapel and Spitalfields between 1888 and 1891 was unable to connect all the killings conclusively to the 1888 murders. Five victims—Mary Ann Nichols, Annie Chapman, Elizabeth Stride, Catherine Eddowes and Mary Jane Kelly—are known as the "canonical five", and their murders between 31 August and 9 November 1888 are often considered the most likely to be linked. The murders were never solved, and the legends surrounding these crimes became a combination of historical research, folklore and pseudohistory, capturing public imagination to the present day.',
 'infobox': {'Other\xa0names': '"The Whitechapel Murderer""Leather Apron"',
  'Victims': 'Unknown (5 canonical)',
  'Date': '1888–1891(1888: 5 canonical)',
  'Locations': 'WhitechapelandSpitalfields, London, England (5 canonical)'},
 'sections_tree': [{'title': 'Background',
   'content': ['In the mid-19th century, England experienced an influx of Irish immigrants who swelled the populations of the major cities, including the East End of London. From 1882, Jewish refugees fleeing pogroms in the Russian Empire and other parts of Eastern Europe immigrated into the same area. The parish of Whitechapel in the East End became increasingly overcrowded, with the population rising to approximately 80,000 inhabitants by 1888. Work and housing conditions deteriorated, and a substantial economic underclass developed. Fifty-five per cent of children born in the East End died before the age of five. Robbery, violence, and alcohol dependency were commonplace, and the endemic poverty drove many women to prostitution to survive on a daily basis.\nIn October 1888, London\'s Metropolitan Police Service estimated that there were 62 brothels and 1,200 women working as prostitutes in Whitechapel. Approximately 8,500 people resided in the 233 common lodging-houses within Whitechapel every night, with the nightly price for a coffin bed being fourpence (equivalent to £2 in 2025) and the cost of sleeping upon a "lean-to" or "hang-over" rope stretched across the dormitory being two pence per person.\nThe economic problems in Whitechapel were accompanied by a steady rise in social tensions. Between 1886 and 1889, frequent demonstrations led to police intervention and public unrest, such as Bloody Sunday (1887). Antisemitism, crime, nativism, racism, social unrest, and severe deprivation influenced public perceptions that Whitechapel was a notorious den of immorality. These perceptions were strengthened in 1888 when the series of vicious and grotesque murders attributed to "Jack the Ripper" received unprecedented coverage in the media.']},
  {'title': 'Murders',
   'content': ['The large number of attacks against women in the East End during this time adds uncertainty to how many victims were murdered by the same person. Eleven separate murders, stretching from 3 April 1888 to 13 February 1891, were included in a Metropolitan Police investigation and were known collectively in the police docket as the "Whitechapel murders". Opinions vary as to whether these murders should be linked to the same culprit, but five of the eleven Whitechapel murders, known as the "canonical five", are widely believed to be the work of the Ripper. Most experts point to deep slash wounds to the throat, followed by extensive abdominal and genital-area mutilation, the removal of internal organs, and progressive facial mutilations as the distinctive features of the Ripper\'s modus operandi. The first two cases in the Whitechapel murders file, those of Emma Elizabeth Smith and Martha Tabram, are not included in the canonical five.\nSmith was robbed and sexually assaulted in Osborn Street, Whitechapel, at approximately 1:30 am on 3 April 1888. She had been bludgeoned about the face and received a cut to her ear. A blunt object was also inserted into her vagina, rupturing her peritoneum. She developed peritonitis and died the following day at London Hospital. Smith stated that she had been attacked by two or three men, one of whom she described as a teenager. This attack was linked to the later murders by the press, but most authors attribute this murder to general East End gang violence unrelated to the Ripper case.\nTabram was murdered on a staircase landing in George Yard, Whitechapel, on 7 August 1888; she had suffered 39 stab wounds to her throat, lungs, heart, liver, spleen, stomach, and abdomen, with additional knife wounds inflicted to her breasts and vagina. All but one of Tabram\'s wounds had been inflicted with a bladed instrument such as a penknife, and with one possible exception, all the wounds had been inflicted by a right-handed person. \nThe savagery of the Tabram murder, the lack of an obvious motive, and the closeness of the location and date to the later canonical Ripper murders led police to link this murder to those later committed by Jack the Ripper. However, this murder differs from the later canonical murders because although Tabram had been repeatedly stabbed, she had not suffered any slash wounds to her throat or abdomen. Many experts do not connect Tabram\'s murder with the later murders because of this difference in the wound pattern.',
    [{'title': 'Canonical five',
      'content': ['The "canonical five" Ripper victims are Mary Ann Nichols, Annie Chapman, Elizabeth Stride, Catherine Eddowes, and Mary Jane Kelly.\nThe body of Mary Ann Nichols was discovered at about 3:40 am on Friday 31 August 1888 in Buck\'s Row (now Durward Street), Whitechapel. Nichols had last been seen alive approximately one hour before the discovery of her body by a Mrs. Emily Holland, with whom she had previously shared a bed at a common lodging-house in Thrawl Street, Spitalfields, walking in the direction of Whitechapel Road. Her throat was severed by two deep cuts, one of which completely severed all the tissue down to the vertebrae. Her vagina had been stabbed twice, and the lower part of her abdomen was partly ripped open by a deep, jagged wound, causing her bowels to protrude. Several other incisions inflicted to both sides of her abdomen had also been caused by the same knife; each of these wounds had been inflicted in a downward thrusting manner.\n\nOne week later, on Saturday 8 September 1888, the body of Annie Chapman was discovered at approximately 6 am near the steps to the doorway of the back yard of 29 Hanbury Street, Spitalfields. As in the case of Nichols, the throat was severed by two deep cuts. Her abdomen had been cut entirely open, with a section of the flesh from her stomach being placed upon her left shoulder and another section of skin and flesh—plus her small intestines—being removed and placed above her right shoulder. Chapman\'s autopsy also revealed that her uterus and sections of her bladder and vagina had been removed.\nAt the inquest into Chapman\'s murder, Elizabeth Long described having seen Chapman standing outside 29 Hanbury Street at about 5:30 am in the company of a dark-haired man wearing a brown deerstalker hat and dark overcoat, and of a "shabby-genteel" appearance. According to this eyewitness, the man had asked Chapman, "Will you?" to which Chapman had replied, "Yes."\nElizabeth Stride and Catherine Eddowes were both killed in the early morning hours of Sunday 30 September 1888. Stride\'s body was discovered at approximately 1 am in Dutfield\'s Yard, off Berner Street (now Henriques Street) in Whitechapel. The cause of death was a single clear-cut incision, measuring six inches across her neck which had severed her left carotid artery and her trachea before terminating beneath her right jaw. The absence of any further mutilations to her body has led to uncertainty as to whether Stride\'s murder was committed by the Ripper, or whether he was interrupted during the attack. Several witnesses later informed police they had seen Stride in the company of a man in or close to Berner Street on the evening of 29 September and in the early hours of 30 September, but each gave differing descriptions: some said that her companion was fair, others dark; some said that he was shabbily dressed, others well-dressed.\n\nEddowes\'s body was found in a corner of Mitre Square in the City of London, three-quarters of an hour after the discovery of the body of Elizabeth Stride. Her throat was severed from ear to ear and her abdomen ripped open by a long, deep and jagged wound before her intestines had been placed over her right shoulder, with a section of the intestine being completely detached and placed between her body and left arm.\nThe left kidney and the major part of Eddowes\'s uterus had been removed, and her face had been disfigured, with her nose severed, her cheek slashed, and cuts measuring a quarter of an inch and a half an inch respectively vertically incised through each of her eyelids. A triangular incision—the apex of which pointed towards Eddowes\'s eye—had also been carved upon each of her cheeks, and a section of the auricle and lobe of her right ear was later recovered from her clothing. The police surgeon who conducted the post mortem upon Eddowes\'s body stated his opinion these mutilations would have taken "at least five minutes" to complete.\nA local cigarette salesman named Joseph Lawende had passed by a narrow walkway to Mitre Square named Church Passage with two friends shortly before the murder; he later described seeing a fair-haired man of medium build with a shabby appearance with a woman who may have been Eddowes. Lawende\'s companions were unable to confirm his description. The murders of Stride and Eddowes ultimately became known as the "double event".\nA section of Eddowes\'s bloodied apron was found at the entrance to a tenement in Goulston Street, Whitechapel, at 2:55 am. A chalk inscription upon the wall directly above this piece of apron read: "The Juwes are The men That Will not be Blamed for nothing." This graffito became known as the Goulston Street graffito. The message appeared to imply that a Jew or Jews in general were responsible for the series of murders, but it is unclear whether the graffito was written by the murderer on dropping the section of apron, or was merely incidental and nothing to do with the case. Such graffiti were commonplace in Whitechapel. Sir Charles Warren, the Police Commissioner, feared that the graffito might spark antisemitic riots and ordered the writing washed away before dawn.\nThe extensively mutilated and disembowelled body of Mary Jane Kelly was discovered lying on the bed in the single room where she lived at 13 Miller\'s Court, off Dorset Street, Spitalfields, at 10:45 am on Friday 9 November 1888. Her face had been "hacked beyond all recognition", with her throat severed down to the spine, and the abdomen almost emptied of its organs. Her uterus, kidneys and one breast had been placed beneath her head, and other viscera from her body placed beside her foot, about the bed and sections of her abdomen and thighs upon a bedside table. The heart was missing from the crime scene. Multiple ashes found within the fireplace at 13 Miller\'s Court suggested Kelly\'s murderer had burned several combustible items to illuminate the single room as he mutilated her body. A recent fire had been severe enough to melt the solder between a kettle and its spout, which had fallen into the grate of the fireplace.\n\n Each of the canonical five murders was perpetrated at night, on or close to a weekend, either at the end of a month or a week (or so) after. The mutilations became increasingly severe as the series of murders proceeded, except for that of Stride, whose attacker may have been interrupted. Nichols was not missing any organs; Chapman\'s uterus and sections of her bladder and vagina were taken; Eddowes had her uterus and left kidney removed and her face mutilated; and Kelly\'s body was extensively eviscerated, with her face "gashed in all directions" and the tissue of her neck being severed to the bone, although the heart was the sole body organ missing from this crime scene.\nHistorically, the belief that these five canonical murders were committed by the same perpetrator is derived from contemporaneous documents which link them together to the exclusion of others. In 1894, Sir Melville Macnaghten, Assistant Chief Constable of the Metropolitan Police Service and Head of the Criminal Investigation Department (CID), wrote a report that stated: "the Whitechapel murderer had 5 victims—& 5 victims only". Similarly, the canonical five victims were linked together in a letter written by police surgeon Thomas Bond to Robert Anderson, head of the London CID, on 10 November 1888.\nSome researchers have posited that some of the murders were undoubtedly the work of a single killer, but an unknown larger number of killers acting independently were responsible for the other crimes. Authors Stewart P. Evans and Donald Rumbelow argue that the canonical five is a "Ripper myth" and that three cases (Nichols, Chapman, and Eddowes) can be definitely linked to the same perpetrator, but that less certainty exists as to whether Stride and Kelly were also murdered by the same person. Conversely, others suppose that the six murders between Tabram and Kelly were the work of a single killer. Percy Clark, assistant to the examining pathologist George Bagster Phillips, linked only three of the murders and thought that the others were perpetrated by "weak-minded individual[s] ... induced to emulate the crime". Macnaghten did not join the police force until the year after the murders, and his memorandum contains serious factual errors about possible suspects.']},
     {'title': 'Later Whitechapel murders',
      'content': ['Mary Jane Kelly is generally considered to be the Ripper\'s final victim, and it is assumed that the crimes ended because of the culprit\'s death, imprisonment, institutionalisation, or emigration. The Whitechapel murders file details another four murders that occurred after the canonical five: those of Rose Mylett, Alice McKenzie, the Pinchin Street torso, and Frances Coles.\nThe strangled body of 26-year-old Rose Mylett was found in Clarke\'s Yard, High Street, Poplar on 20 December 1888. There was no sign of a struggle, and the police believed that she had either accidentally hanged herself with her collar while in a drunken stupor or committed suicide. However, faint markings left by a cord on one side of her neck suggested Mylett had been strangled. At the inquest into Mylett\'s death, the jury returned a verdict of murder.\nAlice McKenzie was murdered shortly after midnight on 17 July 1889 in Castle Alley, Whitechapel. She had suffered two stab wounds to her neck, and her left carotid artery had been severed. Several minor bruises and cuts were found on her body, which also bore a seven-inch long superficial wound extending from her left breast to her navel. One of the examining pathologists, Thomas Bond, believed this to be a Ripper murder, though his colleague George Bagster Phillips, who had examined the bodies of three previous victims, disagreed. Opinions among writers are also divided between those who suspect McKenzie\'s murderer copied the modus operandi of Jack the Ripper to deflect suspicion from himself, and those who ascribe this murder to Jack the Ripper.\n"The Pinchin Street torso" was a decomposing headless and legless torso of an unidentified woman aged between 30 and 40 discovered beneath a railway arch in Pinchin Street, Whitechapel, on 10 September 1889. Bruising about the victim\'s back, hip, and arm indicated the decedent had been extensively beaten shortly before her death. The victim\'s abdomen was also extensively mutilated, although her genitals had not been wounded. She appeared to have been killed approximately one day prior to the discovery of her torso. The dismembered sections of the body are believed to have been transported to the railway arch, hidden under an old chemise.\n\nAt 2:15 am on 13 February 1891, PC Ernest Thompson discovered a 31-year-old prostitute named Frances Coles lying beneath a railway arch at Swallow Gardens, Whitechapel. Her throat had been deeply cut but her body was not mutilated, leading some to believe Thompson had disturbed her assailant. Coles was still alive, although she died before medical help could arrive. A 53-year-old stoker, James Thomas Sadler, had earlier been seen drinking with Coles, and the two are known to have argued approximately three hours before her death. Sadler—a known client of Coles—was arrested by the police and charged with her murder. He was briefly thought to be the Ripper, but was later discharged from court for lack of evidence on 3 March 1891.']},
     {'title': 'Other alleged victims',

In [ ]:
erase_origin = ["Category:Malaysia Airlines Flight 370"]

In [ ]:
rem_keys = []
for key, value in c2_pages_db.items():
  if value['origin_title']=="Category:Malaysia Airlines Flight 370":
    origin = value['origin_title']
    if key == origin[9:]:
      print("spared:"+key)
    else:
      rem_keys.append(key)
print(len(rem_keys))

0

In [ ]:
for i in rem_keys:
  _ = c2_pages_db.pop(i,None)

In [ ]:
with open(f"{SAVEFILE_DIR}cleaning_pages_db_3.json", "w", encoding="utf-8") as f:
    json.dump(c2_pages_db, f, ensure_ascii=False, indent=4)

### Categories

In [ ]:
with open(f"{SAVEFILE_DIR}cleaning_pages_db_3.json", "r", encoding="utf-8") as f:
    c3_pages_db = json.load(f)
print("--- Progress Loaded from Checkpoint ---")

--- Progress Loaded from Checkpoint ---

In [ ]:
all_title = list(c3_pages_db.keys())
all_title.sort()
with open("page_title.txt", "w", encoding="utf-8") as f:
    for title in all_title:
        f.write(title + "\n")

In [ ]:
murder_keywords = [
    "murder", "killing", "massacre", "assassination", "homicide",
    "shooting", "bombing", "arson", "strangler", "killer", "ripper", "poisoning",
]

missing_keywords = [
    "disappearance", "missing", "kidnapping", "abduction",
    #"lost", "theft", "heist", "robbery", "escape", "stolen", "disappeared"
]

unexplained_death_keywords = [
    "death"
]

In [ ]:
for key, value in c3_pages_db.items():
  if any(word in key.lower() for word in murder_keywords):
    value["SE_Category"] = "murder"
  elif any(word in key.lower() for word in missing_keywords):
    value["SE_Category"] = "missing"
  elif any(word in key.lower() for word in missing_keywords):
    value["SE_Category"] = "unexplained death"
  else:
    value["SE_Category"] = "-"

In [ ]:
blank = 0
for key, value in c3_pages_db.items():
  if value["SE_Category"]=="-":
    blank+=1
print(blank)

3511

In [ ]:
error guard
with open(f"{SAVEFILE_DIR}cleaning_pages_db_4a.json", "w", encoding="utf-8") as f:
    json.dump(c3_pages_db, f, ensure_ascii=False, indent=4)

In [ ]:
with open(f"{SAVEFILE_DIR}cleaning_pages_db_4a.json", "r", encoding="utf-8") as f:
    c4a_pages_db = json.load(f)
print("--- Progress Loaded from Checkpoint ---")

--- Progress Loaded from Checkpoint ---

In [ ]:
all_origin = set()
for key, value in c4a_pages_db.items():
  if value["SE_Category"] == "-":
    all_origin.add(value['origin_title'])
all_origin = list(all_origin)
all_origin.sort()
with open("page_origin.txt", "w", encoding="utf-8") as f:
    for title in all_origin:
        f.write(title + "\n")

In [ ]:
for key, value in c4a_pages_db.items():
  if value["SE_Category"] == "-":
    if 'murder' in value['origin_title'].lower():
      value["SE_Category"] = "murder"
    elif ('missing' in value['origin_title'].lower() or 'disappear' in value['origin_title'].lower()) and 'people' in value['origin_title'].lower():
      value["SE_Category"] = "missing"
    elif 'death' in value['origin_title'].lower():
      value["SE_Category"] = "unexplained death"

In [ ]:
for key, value in c4a_pages_db.items():
  if value["SE_Category"] == "-":
    if 'missing' in value['origin_title'].lower() and 'person' in value['origin_title'].lower():
      value["SE_Category"] = "missing"

In [ ]:
for key, value in c4a_pages_db.items():
  if value["SE_Category"] == "-":
    if 'enforced disappearances' in value['origin_title'].lower():
      value["SE_Category"] = "missing"

In [ ]:
origin_missing = ['Category:Aerial disappearances',
 'Category:Aerial disappearances of military personnel in action','Category:Disappeared journalists','Category:Lost explorers', 'Category:Mass disappearances',
 'Category:Missing American children', 'Category:Missing German children', 'Category:Missing air passengers',
 'Category:Missing aircraft', 'Category:Missing aviators',
 'Category:Missing children','Category:Lost sailing vessels','Category:Missing in action of World War I',
 'Category:Missing in action of World War II','Category:Missing ships',
 'Category:Missing ships of Australia', 'Category:Missing submarines',
 'Category:Missing submarines of World War II', 'Category:Missing trains','Category:People declared dead in absentia',
 'Category:People lost at sea','Category:Unexplained_disappearances','Missing aircraft',
 'Unexplained disappearances','Category:Unexplained_disappearances','List of missing ships',"Category:Missing scientists investigation"]

In [ ]:
for key, value in c4a_pages_db.items():
  if value["SE_Category"] == "-":
    if value['origin_title'] in origin_missing:
      value["SE_Category"] = "missing"

In [ ]:
origin_wanted = ['Category:Missing fugitives', 'Category:Missing gangsters','Category:Terrorist incidents by unknown perpetrators',
 'Category:Unidentified American criminals', 'Category:Unidentified American rapists', 'Category:Unidentified American serial killers',
 'Category:Unidentified British criminals', 'Category:Unidentified British rapists', 'Category:Unidentified Canadian criminals',
 'Category:Unidentified criminals', 'Category:Unidentified rapists', 'Category:Unidentified serial killers','List_of_fugitives_from_justice_who_disappeared']

In [ ]:
for key, value in c4a_pages_db.items():
  if value["SE_Category"] == "-":
    if value['origin_title'] in origin_wanted:
      value["SE_Category"] = "wanted"

In [ ]:
origin_treasure = ['Category:Lost buildings and structures', 'Category:Lost objects', 'Category:Lost works of art']
origin_legend = ['Category:Bermuda Triangle']

In [ ]:
for key, value in c4a_pages_db.items():
  if value["SE_Category"] == "-":
    if value['origin_title'] in origin_treasure:
      value["SE_Category"] = "treasure"
    elif value['origin_title'] in origin_legend:
      value["SE_Category"] = "legend"

In [ ]:
a = c4a_pages_db.pop("National Biodefense Analysis and Countermeasures Center",None)
a

{'origin_title': 'Category:2001 anthrax attacks',
 'url': 'https://en.wikipedia.org/wiki/National_Biodefense_Analysis_and_Countermeasures_Center',
 'last_update_text': 'This page was last edited on 18 May 2026, at 12:09(UTC).',
 'summary': 'The National Biodefense Analysis and Countermeasures Center (NBACC) is a government biodefense research laboratory created by the U.S. Department of Homeland Security (DHS) and located at the sprawling biodefense campus at Fort Detrick in Frederick, MD, USA. The NBACC (pronounced EN-back) is the principal U.S. biodefense research institution engaged in laboratory-based threat assessment and bioforensics.  NBACC is an important part of the National Interagency Biodefense Campus (NIBC) also located at Fort Detrick for the US Army, National Institutes of Health and the US Department of Agriculture.',
 'infobox': {'Formed': '2002; 24\xa0years ago(2002)',
  'Jurisdiction': 'Federal government of the United States',
  'Headquarters': 'Fort Detrick,Frederick, Maryland, USA',
  'Employees': '190',
  'Agency executive': 'Dr. Nicholas Bergman, Director',
  'Parent agency': 'United States Department of Homeland Security'},
 'sections_tree': [{'title': 'Background and mission',
   'content': ['The NBACC was created as a federal response to the 2001 anthrax attacks as the first national laboratory operating under the Department of Homeland Security. The Department of Homeland Security said the mission of the NBACC is "to provide the scientific basis for the characterization of biological threats and bioforensic analysis to support attribution of their planned or actual use." Part of the NBACC\'s mission is to conduct realistic tests of the pathogens and tactics that might be used in a bioterrorism attack. It seeks to quantitatively answer questions pertaining to what might happen in a biological attack. This work is carried out by about 180 researchers and support staff and has become more advanced since the NBACC became certified to work with biological select agents and toxins in September 2011.\nIts work is necessary in the preparation and response to biological threats, which can be handled as they emerge through the NBACC national security biocontainment laboratory. The NBACC is equipped to develop and investigate genetically engineered viruses and bacteria. The NBACC evaluates new and emerging technologies, along with delivery devices that U.S. adversaries might use to disseminate the pathogens.\nThe NBACC coordinates closely with the many departments and agencies in the U.S. government, including the U.S. intelligence community which has assigned advisers to the Center. The NBACC is involved in a partnership with the National Interagency Confederation for Biological Research at Fort Detrick and initiated the "Work for Others" program, which expands the NBACC\'s capacity to share information with a variety of related federal agencies.']},
  {'title': 'Significance of operation',
   'content': ['In June 2017, Daniel M. Gerstein, senior policy researcher at the RAND Corporation and former acting Under Secretary and Deputy Under Secretary of the DHS\'s Science and Technology Directorate, said, "In the last 40 to 60 years, hundreds of new diseases have cropped up across the world ... The country and the world have not proven ready to handle a true public health crisis." Describing the NBACC\'s value to science, Gerstein said, "Back in 2001, we did not have this facility, and it literally took months in order to do the forensics analysis of samples ... they had to outsource ... to 12 different facilities to get everything analyzed back then. Today, the NBACC can do those forensic analyses in a couple days."\nThe risk of a bioterrorism attack continues to grow. International terrorist organizations, such as ISIS, have shown growing desire to access and use biological weapons. A 19-page document providing instructions on the creation of biological weapons was discovered on a laptop obtained from ISIS in 2014. Kenyan authorities stopped an ISIS-affiliated anthrax plot in late 2016. In early 2017, South Korea speculated that North Korea was developing biological weapons that could be dispersed through drones. The NBACC and affiliated groups play an important role in protecting the public from these mounting threats.\nNBACC has already proven capable of responding to these types of threats, as an important actor in the United States response to the Ebola Outbreak of 2014. During the crisis, NBACC scientists carried out experiments to test the duration of the virus\' activity when placed on different surfaces, and best practices for sanitation after completing tests.']},
  {'title': 'Threats to continued work',
   'content': ['Under President Trump\'s budget proposal for fiscal year 2018, the NBACC stands to lose funding that allows it to continue scientific studies. The NBACC is faced with the threat of complete shutdown of its facilities by September 2018. Daniel M. Gerstein said the result of the closure of the NBACC would be a "potentially devastating public health concern."\nThe cost of replacing the services provided by the NBACC will be more expensive than continuing its operations simply due to the nature of changing the role of the NBACC\'s facilities, according to Homeland Preparedness News.\nCongressman John Delaney (D-MD), who represents the Maryland congressional district in which the NBACC resides, said in a statement from May 2017:\n\nI am 100 percent opposed to the closing of the National Biodefense Analysis and Countermeasures Center in Frederick and will fight this deeply misguided move by the Trump Administration ... The National Biodefense Analysis and Countermeasures Center is a unique facility that is crucial to our homeland security, intelligence, and anti-terrorism endeavors. This is the lab that protects us against anthrax attacks, ricin attacks and other bioterrorism threats. \nIn May 2017, several faculty at the Johns Hopkins Center for Health Security, said the loss of the NBACC would make the impact of a bioterror attack "far more dire." They said, "In the first moments after the attack is identified, we\'d want to know the identity of the pathogen used in the attack, whether it could spread from person to person and what drugs and vaccines would work to treat and protect people. But with ... complete elimination [of the NBACC] ... the delay before these and other facts are known would increase, costing many lives."\nIn September 2015, the Battelle National Biodefense Institute (which operates the NBACC) was awarded a 10-year contract for operations and management. At the time, Battelle said the contract would be worth $480 million if fully executed. The proposed Trump budget for 2018, though, would see this award retracted, leading to the end of all scientific operations by March 2018.']},
  {'title': 'Facilities',
   'content': ["NBACC laboratories operate at the biosafety levels of 2, 3, and 4, providing the optimal level of safety and operational capacity. In particular, the NBACC's biosafety level of 4 allows its facilities to research pathogens that have no existing vaccines or treatment. This makes it one of only seven locations in the United States where this occurs.\nIn June 2006, construction began on a new $128 million, 160,000 sq ft (15,000 m2) facility inside the Ft. Detrick installation. The facility contains two centers:\n\nThe National Biological Threat Characterization Center (NBTCC), which seeks to identify and prioritize biological threats and our vulnerabilities to those threats through its laboratory threat assessments. It includes biocontainment suites, including air-handling equipment, security controls, and other supporting features. It is classified as a SCIF, or Sensitive Compartmented Information Facility, meaning that while the majority of research that occurs at the lab is unclassified, some research results must remain classified for security purposes.\nThe National Bioforensic Analysis Center (NBFAC), a forensic testing center equipped to identify and characterize the possible culprit pathogens after an attack has already occurred."]},
  {'title': 'Notable accomplishments',
   'content': ['The NBACC achieved a "Superior" Defense Security Service (DSS) rating in 2012 and 2013 and was recognized for staff volunteerism. It has played a role in over 100 federal law enforcement cases.\nThe NBTCC has unique national biosafety level 3 and 4 aerobiology capabilities, which are necessary to collect crucial data that is used to develop biodefense plans and responses. In 2013, it provided necessary data, which addressed 10 specific biological agent knowledge gaps, to improve hazard, risk, and threat assessments. The data allowed for significant growth in the credibility of hazard and risk assessment modeling of bioterrorism scenarios for a variety of toxin threat agents, including both bacteria and viruses.\nThe NBFAC played a role in more than 45 federal law enforcement investigations of biological crimes in 2013 alone. Also in 2013, it activated unique bioforensic laboratories at biosafety level 3 with accreditation for casework operations. Its processes maintain operational capability to study more than 60 high-priority human, animal, and plant pathogens and toxins. Its sequencing methods are imperative to enable new kinds of studies. It played a central role in developing capabilities to investigate genetically modified and de novo synthetic agents (new complex molecules formed from simple molecules).\nIn January 2018, the Intelligence Advanced Research Projects Activity selected Battelle to create a software platform able to fight the development of synthetic biological threats. Battelle said it would develop the threat assessment platform with collaboration from Ginkgo Bioworks, One Codex and Twist Bioscience. The intended final result is a program that can "merge computational approaches into a software tool that can be applied in real-world scenarios."']},
  {'title': 'Controversy and response',
   'content': ['Questions have been raised by some arms-control and international law experts as to the necessity and advisability of the very high level of security surrounding the NBACC and as to whether it does (or will) place the United States in violation of the 1972 Biological and Toxin Weapons Convention (BWC). (The BWC outlawed developing, stockpiling, acquiring or retaining pathogens "of types and in quantities that have no justification" for peaceful purposes.)\nNBACC\'s opponents contended that the facility would operate in a "legal gray zone" and skirt the edges of the BWC, which outlaws production of even small amounts of biological weapons. They contend that a high degree of transparency is needed to reassure Americans (and the rest of the world) of the U.S. government\'s good intentions. In their view, the U.S. government may find it hard in the future to object to other countries testing genetically engineered pathogens and novel delivery systems when they invoke their own national biodefense requirements.\nThe Bush administration contended that the NBACC is purely defensive and thus its operations are fully legal and in accord with the BWC. A principle is that assessing the technical threat of biological pathogens is essential to inform and help develop biodefense policy. Administration officials say that making small amounts of biowarfare pathogens for study is permitted under a broad interpretation of the treaty.\nFaculty at the NBACC provided their own responses to help answer questions raised by critics.\nIn May 2008, director Patrick Fitch said that research at the laboratory is not conducted to "create threats in order to study them." Maureen McCarthy, former Homeland Security director of research and development, said, "All the programs we do are defensive in nature. Our job is to ensure that the civilian population of the country is protected, and that we know what the threats are." Bernard Courtney, the NBACC\'s former scientific director, described oversight, mentioning that frequent independent reviews over particular experiments occur. These reviews are operated by a group of up to four scientists on a case-by-case scenario.\nAdditionally, research at the labs is overseen by the Institutional Biosafety Committee. The CDC also conducts inspections to assure labs comply with Select Agents rules. The Final Environmental Impact Statement, or FEIS, for NBACC facilities states that all research is performed for defense purposes and is conducted in a legal manner, including under the BWC.']}],
 'table': [],
 'categories': ['Category:2001 anthrax attacks',
  'Category:2002 establishments in Maryland',
  'Category:All Wikipedia articles written in American English',
  'Category:All articles with unsourced statements',
  'Category:Articles with short description',
  'Category:Articles with unsourced statements from September 2022',
  'Category:Biological warfare',
  'Category:Biosafety level 4 laboratories',
  'Category:Buildings and structures in Frederick County, Maryland',
  'Category:CS1 maint: archived copy as title',
  'Category:Coordinates on Wikidata',
  'Category:Disaster preparedness in the United States',
  'Category:Federally Funded Research and Development Centers',
  'Category:Government agencies established in 2002',
  'Category:Pages using gadget WikiMiniAtlas',
  'Category:Pages using infobox mapframe without shape links in Wikidata',
  'Category:Pages using the Kartographer extension',
  'Category:Research installations of the United States Army',
  'Category:Short description matches Wikidata',
  'Category:United States Department of Homeland Security',
  'Category:Use American English from July 2025'],
 'SE_Category': '-'}

In [ ]:
error guard
with open(f"{SAVEFILE_DIR}cleaning_pages_db_4b.json", "w", encoding="utf-8") as f:
    json.dump(c4a_pages_db, f, ensure_ascii=False, indent=4)

In [ ]:
#============================

In [ ]:
with open(f"{SAVEFILE_DIR}cleaning_pages_db_4b.json", "r", encoding="utf-8") as f:
    c4b_pages_db = json.load(f)
print("--- Progress Loaded from Checkpoint ---")

--- Progress Loaded from Checkpoint ---

In [ ]:
len(c4b_pages_db)

4939

In [ ]:
rm_keys = []
for keys, value in c4b_pages_db.items():
  if value['origin_title']=="Category:2001 anthrax attacks":#'Category:Richard of Shrewsbury, Duke of York':
    rm_keys.append(keys)
for i in rm_keys:
  _ = c4b_pages_db.pop(i,None)

In [ ]:
#Checking
#all_title = set()
for key, value in c4b_pages_db.items():
  if value["SE_Category"] == "-":
    if any(('death' in cat.lower() or 'murder' in cat.lower() or 'killing' in cat.lower()) for cat in value['categories']):
      print(f"{key} < {value['origin_title']}")
      value["SE_Category"] = 'murder'
    #value['categories'] any(word in key.lower() for word in murder_keywords):
    #all_title.add(key)
#all_title = list(all_title)
#all_title.sort()
#all_title

Elfrieda Knaak < Category:Unsolved crimes
Harry Roy Veevers < Category:Unsolved crimes
Cairo fire < Category:Unsolved arsons
1978 Holiday Inn fire < Category:Unsolved arsons
Myojo 56 building fire < Category:Unsolved arsons
2020 New York City Subway fire < Category:Unsolved arsons
Stouffer's Inn fire < Category:Unsolved arsons
The Gentleman of Heligoland < Category:Unsolved crimes in Europe
Operation Identify Me < Category:Unsolved crimes in Europe
Mr Cruel < Category:Unsolved crimes in Australia
Hummingbird heist < Category:Unsolved crimes in Belize
El Psicópata < Category:Unsolved crimes in Costa Rica
Francis Imbard affair < Category:Unsolved crimes in France
Prithipal Singh < Category:Unsolved crimes in India
Death of Benny Whitehouse < Category:Unsolved crimes in Ireland
Stolero-Yachman-Chachkes affair < Category:Unsolved crimes in Israel
San Juan del Sur Psychopath < Category:Unsolved crimes in Nicaragua
Ekiti prison break < Category:Unsolved crimes in Nigeria
Haji Sulong < Category:Unsolved crimes in Thailand
Denver Mint robbery < Category:Unsolved crimes in the United States
Aeroflot Flight 773 < Category:Unsolved airliner bombings
Cyprus Airways Flight 284 < Category:Unsolved airliner bombings
Itavia Flight 870 < Category:Unsolved airliner bombings
JAT Flight 367 < Category:Unsolved airliner bombings
Middle East Airlines Flight 438 < Category:Unsolved airliner bombings
National Airlines Flight 967 < Category:Unsolved airliner bombings in the United States
United Air Lines Flight 23 < Category:Unsolved airliner bombings in the United States

In [ ]:
#Checking
#all_title = set()
for key, value in c4b_pages_db.items():
  if value["SE_Category"] == "-":
    if any(('theft' in cat.lower() or 'lost object' in cat.lower() or 'robbery' in cat.lower()) for cat in value['categories']):
      print(f"{key} < {value['origin_title']}")
      value["SE_Category"] = 'treasure'
    #value['categories'] any(word in key.lower() for word in murder_keywords):
    #all_title.add(key)
#all_title = list(all_title)
#all_title.sort()
#all_title

Corrida (horse) < Category:Unsolved crimes in Europe
1983 theft of the Jules Rimet Trophy < Category:Unsolved crimes in Brazil
1972 Montreal Museum of Fine Arts robbery < Category:Unsolved crimes in Canada
2011 Montreal Museum of Fine Arts theft < Category:Unsolved crimes in Canada
Irish Crown Jewels < Category:Unsolved crimes in Ireland
Biblioteca della Comunità Israelitica < Category:Unsolved crimes in Italy
2025 Drents Museum heist < Category:Unsolved crimes in the Netherlands
1966 theft of the Jules Rimet Trophy < Category:Unsolved crimes in the United Kingdom
2022 Brink's theft < Category:Unsolved crimes in the United States
Easter Sunday heist < Category:Unsolved crimes in the United States
Isabella Stewart Gardner Museum theft < Category:Unsolved crimes in the United States

In [ ]:
c4b_pages_db['Eastcastle Street robbery']["SE_Category"] = 'treasure'
c4b_pages_db['300 million yen robbery']["SE_Category"] = 'treasure'
c4b_pages_db['1987 Opera House heist']["SE_Category"] = 'treasure'
c4b_pages_db['1977 Krugersdorp bank robbery']["SE_Category"] = 'treasure'
c4b_pages_db['1999 Loomis truck robbery']["SE_Category"] = 'treasure'

In [ ]:
c4b_pages_db['Gajraula Nuns rape case']["SE_Category"] = 'wanted'

In [ ]:
c4b_pages_db['Woman-Ochre']["SE_Category"] = 'treasure'

In [ ]:
c4b_pages_db['Christiana Mall']["SE_Category"] = 'murder'

In [ ]:
c4b_pages_db['Christiana Mall']["SE_Category"] = 'missing'

In [ ]:
error guard
if c4b_pages_db.pop('Hans van de Kimmenade',None):
  print("deleted")

deleted

In [ ]:
blank = 0
for key, value in c4b_pages_db.items():
  if value["SE_Category"]=="-":
    blank+=1
print(blank)

0

In [ ]:
list_se_cat = []
for key, value in c4b_pages_db.items():
  list_se_cat.append(value["SE_Category"])
distribution = Counter(list_se_cat)
print(distribution)

Counter({'missing': 2706, 'murder': 1719, 'unexplained death': 221, 'wanted': 187, 'treasure': 87, 'legend': 8})

In [ ]:
c4b_pages_db.pop("Aguanga, California",None)

{'origin_title': 'Category:Unsolved mass murders in California',
 'url': 'https://en.wikipedia.org/wiki/Aguanga,_California',
 'last_update_text': 'This page was last edited on 16 May 2026, at 23:29(UTC).',
 'summary': 'Aguanga (; Luiseño: Awáanga, meaning "dog place") is a census-designated place located within the Inland Empire in Riverside County, California.  It is located about 18 miles (29 km) east of Temecula and 22 miles (35 km) south-southeast of Hemet. Aguanga lies at an elevation of 1955 feet (596 m). As of the 2020 census, it had a population of 989.',
 'infobox': {'Country': 'United States',
  'State': 'California',
  'County': 'Riverside',
  '•\xa0Total': '989',
  '•\xa0Land': '13.60\xa0sq\xa0mi (35.22\xa0km2)',
  '•\xa0Water': '0\xa0sq\xa0mi (0.00\xa0km2) \xa00%',
  'Elevation[2]': '1,955\xa0ft (596\xa0m)',
  '•\xa0Density': '72.7/sq\xa0mi (28.08/km2)',
  'Time zone': 'UTC-8(Pacific (PST))',
  '•\xa0Summer (DST)': 'UTC-7(PDT)',
  'ZIP codes': '92536',
  'Area code': '951',
  'FIPS code': '06-00464',
  'GNISfeature IDs': '269448;2582929'},
 'sections_tree': [{'title': 'History',
   'content': ['The town gets its name from a former village of the Native village called awáanga, meaning \'dog place\'. Butterfield Overland Mail established a station 1.7 miles to the west of the current post office in 1858. It was at first called Tejungo Station and was located 14 miles east of Temecula Station and 12 miles northwest of Oak Grove Stage Station. The wooden building was located in a grove of trees a few hundred feet from the stage road.  Soon, however, it became known as Aguanga Station after the name of the nearby Luiseño village.\nThe November 7, 1861, report of Lieut. Col. Joseph R. West, mentioned the abandoned station location was then called Giftaler\'s Ranch, after its German owner Joseph Giftaler, in a journal of his unit\'s march to Fort Yuma on the old Butterfield Overland Mail route. In a later Civil War itinerary of the route, it is referred to as the "Dutchman\'s". In 1863, Camp Giftaler Ranch was established at the ranch as a post along the march route of troops to the Arizona Territory by the Union army.\nIn 1864, Giftaler\'s Ranch was purchased by Jacob Bergman, also a German immigrant, stagecoach driver and Union army veteran, who operated the Bergman Ranch there for many years until his death on September 13, 1894. After the Civil War, he ran Bergman\'s Stage Station there for the Banning and Tomlinson Stage lines for many years.  During the Julian gold rush, he ran the Guahonga post office there from July 27, 1870, to September 13, 1871. The post office for the area was then moved to Oak Grove until the Bergman post office was opened in 1894, but its name was changed to Aguanga in 1901.\nToday the station site is on the Twin Creek Stage Stop Ranch, on Allmouth Road, found just east of the Stagecoach Inn at 43851 Highway 79. The ruins of the old wooden station building and ranch house is located among a grove of trees, at the foot of the west end of the hill at the bottom of the meadow, along the right fork of Allmouth Road. The small, fenced-in Bergman Family Cemetery and the Jacob Bergman Marker are found on Caprice Road, 200 feet from the highway, just across the highway from the entrance to the ranch and a short distance to the east.',
    [{'title': '2020 shooting',
      'content': ["On September 7, 2020, deputies with the Riverside County Sheriff's Department responded to reports of an assault with a deadly weapon at a residence on Gibson Road just off Road Runner Lane, along Route 371. Upon responding, they found a woman suffering gunshot wounds, who eventually died from her injuries after being rushed to a hospital. The deputies then discovered six additional victims inside the home, all of whom were dead from gunshots. Authorities believed the shooting was an isolated incident. The residence where the shooting occurred was reportedly being used to grow illegal marijuana. Authorities did not find a motive or any viable suspects. The shooting is the deadliest in Riverside County's history. In 2024, new details came out, no suspects were captured, but police believe the robbery was committed by gang members of Laotian descent, and the motive was drug competition/robbery related, because 1,000 pounds and hundreds of plants of weed were on the property, which is 1-5 million dollars' worth of drugs, and the victims, five women and two men, were recent immigrants from Laos, aged between 44 and 64."]},
     {'title': 'Highland Fire',
      'content': ['At approximately 12:27PM PST on October 30, 2023, the Highland Fire ignited near the intersection of Highlands road and Aguanga Ranchos Road. The vegetation fire was eventually contained on November 5, 2023, at approximately 7PM PST. In total, 2,487 acres burned, including thirteen structures destroyed and two more damaged in the Aguanga Valley near Tule Creek off of the 371. Cal Fire reports two firefighters were injured during the fire.']},
     {'title': 'Nixon Fire',
      'content': ['On July 29, 2024, the Nixon Fire ignited near Tule Valley Road and Richard Nixon Boulevard.']}]]},
  {'title': 'Geography',
   'content': ['According to the United States Census Bureau, the CDP covers an area of 13.6 square miles (35.2 km2), all of it land.\nThe community of Aguanga lies near the intersection of State Route 79 (SR 79) and State Route 371 (Cahuilla Road), along the historic Butterfield Overland Mail stage route. The area lies at about 1,940 feet (590 m) above mean sea level (AMSL) and is north of the Cleveland National Forest. The straight-line distance to Palomar Observatory is 5.9 miles (9.5 km) south, and the observatory site is about 3,500 feet (1,100 m) higher than the community. The town is also home to Cottonwood Elementary School (K–8) operated by the Hemet Valley Unified School District. The largest nearby city is Temecula, along the Interstate 15 corridor, about 17 miles (27 km) west of Aguanga on SR 79.\nThis area is in a canyon beside Temecula Creek near Pechanga tribal lands and the San Diego County line. Official U.S. Geological Survey NAD27 coordinates for the community are 33°26′34″N 116°51′51″W. It is within area code 951 and shares its ZIP Code, 92536, with the San Diego County community of Holcomb Village.',
    [{'title': 'Climate',
      'content': ['According to the Köppen climate classification system, Aguanga has a hot-summer Mediterranean climate, abbreviated "Csa" on climate maps. The climate makes it significantly easier to grow olive trees, so the Temecula Olive Oil Company is based here.']}]]},
  {'title': 'Demographics',
   'content': ['',
    [{'title': 'Racial and ethnic composition', 'content': ['']},
     {'title': '2020 census',
      'content': ['As of the 2020 census, Aguanga had a population of 989, with a population density of 72.7 inhabitants per square mile (28.1/km2). The age distribution was 9.0% under the age of 18, 5.9% aged 18 to 24, 12.6% aged 25 to 44, 25.1% aged 45 to 64, and 47.4% who were 65 years of age or older. The median age was 64.0 years. For every 100 females there were 97.4 males, and for every 100 females age 18 and over there were 98.7 males age 18 and over.\nThe census reported that 100% of the population lived in households. 0.0% of residents lived in urban areas, while 100.0% lived in rural areas.\nThere were 476 households in Aguanga, of which 9.2% had children under the age of 18 living in them. Of all households, 55.0% were married-couple households, 4.8% were cohabiting couple households, 21.4% were households with a male householder and no spouse or partner present, and 18.7% were households with a female householder and no spouse or partner present. About 28.0% of all households were made up of individuals and 18.1% had someone living alone who was 65 years of age or older. The average household size was 2.08. There were 316 families (66.4% of all households).\nThere were 567 housing units, of which 16.0% were vacant. Of occupied units, 85.1% were owner-occupied and 14.9% were occupied by renters. The homeowner vacancy rate was 2.9% and the rental vacancy rate was 11.3%.']},
     {'title': '2010 census',
      'content': ['Aguanga first appeared as a census designated place in the 2010 U.S. census.']}]]},
  {'title': 'Education',
   'content': ['It is in the Hemet Unified School District.']},
  {'title': 'Wildlife Conservation Efforts',
   'content': ['',
    [{'title': 'Endangered Animals',
      'content': ["Several federally and state-listed endangered or threatened animals are found in Aguanga. Conservation efforts are underway to help protect their remaining habitats and restore their populations.\n1. Stephens’ Kangaroo Rat (Dipodomys stephensi)\nThis small, hopping rodent is unique to southwestern Riverside County and parts of San Diego County. It prefers open grasslands and is particularly vulnerable to urban sprawl and agriculture. It is listed as endangered and is a focus of regional habitat conservation plans.\n2. San Bernardino Kangaroo Rat (Dipodomys merriami parvus)\nSimilar in appearance to the Stephens’ kangaroo rat, this subspecies inhabits rocky, alluvial soils in sage scrub ecosystems. Due to extensive habitat fragmentation, it is listed as federally endangered.\n3. Quino Checkerspot Butterfly (Euphydryas editha quino)\nOnce widespread across Southern California, this butterfly now exists in only a few fragmented areas. It depends on specific host plants and sunny, open landscapes. The butterfly's status is federally endangered, and habitat restoration is key to its recovery.\n4. Coastal California Gnatcatcher (Polioptila californica californica)\nThis small, gray bird is a resident of the coastal sage scrub ecosystem. Due to widespread destruction of its habitat, it is listed as a threatened species. Preserves near Aguanga play an important role in protecting the species' remaining breeding grounds.\n5. Least Bell's Vireo (Vireo bellii pusillus)\nA riparian songbird, the Least Bell's Vireo was once common but declined dramatically due to loss of riverside vegetation and nest parasitism by cowbirds. It is federally endangered, though its population is beginning to rebound thanks to conservation efforts.\n6. Southwestern Willow Flycatcher (Empidonax traillii extimus)\nThis flycatcher depends on dense willow and cottonwood forests along streams. Declines in riparian habitat from water diversion and development have led to its endangered status.\n7. Vernal Pool Fairy Shrimp (Branchinecta lynchi)\nThis tiny aquatic animal inhabits seasonal vernal pools that form after rain. These habitats are extremely rare and easily destroyed by land alteration. The shrimp is listed as threatened under the Endangered Species Act."]},
     {'title': 'Native Flora of Aguanga',
      'content': ["The vegetation in Aguanga is just as vital as its wildlife. The region falls within the California Floristic Province, one of the world's largest biodiversity hotspots. Its unique blend of Mediterranean climate and elevation changes supports several plant communities:",
       [{'title': 'Coastal Sage Scrub',
         'content': ['This is the dominant plant in much of Aguanga. It consists of drought-deciduous shrubs such as:\n\nCalifornia Sagebrush (Artemisia californica)\nBlack Sage (Salvia mellifera)\nWhite Sage (Salvia apiana)\nCalifornia Buckwheat (Eriogonum fasciculatum)']},
        {'title': 'Chaparral',
         'content': ['On higher, rockier terrain, dense chaparral shrubs dominate. These plants are highly adapted to dry summers and provide food and shelter for many animals, including endangered species. Chaparral plants are fire-adapted and play an important role in erosion control and carbon storage. Key species include:\n\nChamise (Adenostoma fasciculatum)\nManzanita (Arctostaphylos spp.)\nCeanothus (Ceanothus spp.)']},
        {'title': 'Riparian Vegetation',
         'content': ["Found along streams and wet areas, this vegetation supports birds and amphibians. These areas are crucial for endangered birds like the Least Bell's Vireo and the Willow Flycatcher. Common species include:\n\nWillows (Salix spp.)\nCottonwoods (Populus fremontii)\nWestern Sycamores (Platanus racemosa)"]},
        {'title': 'Vernal Pool Flora',
         'content': ['Seasonal pools host rare wildflowers and grasses. These ephemeral wetlands support a surprising variety of life during the brief wet season like:\n\nNavarretia spp.\nDowningia spp.\nHairgrass (Deschampsia danthonioides)']}]]}]]}],
 'table': [{'section': 'Racial and ethnic composition',
   'headers': ['Race / Ethnicity(NH = Non-Hispanic)',
    'Pop 2010[38]',
    'Pop 2020[39]',
    '% 2010',
    '% 2020'],
   'data': [['Whitealone (NH)', '781', '687', '69.24%', '69.46%'],
    ['Black or African Americanalone (NH)', '11', '9', '0.98%', '0.91%'],
    ['Native AmericanorAlaska Nativealone (NH)', '15', '14', '1.33%', '1.42%'],
    ['Asianalone (NH)', '23', '22', '2.04%', '2.22%'],
    ['Native HawaiianorPacific Islanderalone (NH)',
     '0',
     '2',
     '0.00%',
     '0.20%'],
    ['Other racealone (NH)', '1', '3', '0.09%', '0.30%'],
    ['Mixed race or Multiracial(NH)', '23', '42', '2.04%', '4.25%'],
    ['Hispanic or Latino(any race)', '274', '210', '24.29%', '21.23%'],
    ['Total', '1,128', '989', '100.00%', '100.00%']]}],
 'categories': ['Category:All Wikipedia articles written in American English',
  'Category:All articles needing additional references',
  'Category:All articles with dead external links',
  'Category:Articles needing additional references from June 2025',
  'Category:Articles with dead external links from December 2024',
  'Category:Articles with short description',
  'Category:Butterfield Overland Mail in California',
  'Category:CS1: unfit URL',
  'Category:Census-designated places in California',
  'Category:Census-designated places in Riverside County, California',
  'Category:Coordinates on Wikidata',
  'Category:Pages using gadget WikiMiniAtlas',
  'Category:Short description is different from Wikidata',
  'Category:Use American English from March 2025',
  'Category:Use mdy dates from April 2024'],
 'SE_Category': 'murder'}

In [ ]:
with open(f"{SAVEFILE_DIR}cleaning_pages_db_4c.json", "w", encoding="utf-8") as f:
    json.dump(c4b_pages_db, f, ensure_ascii=False, indent=4)

In [ ]:
#Checking
all_title = set()
for key, value in c4b_pages_db.items():
  if value["SE_Category"] == "-":
    all_title.add(key)
all_title = list(all_title)
all_title.sort()
all_title

[]

In [ ]:
#Checking
for key, value in c4a_pages_db.items():
    if value['origin_title']=='Category:Unsolved crimes in England' and value["SE_Category"] == "-":
      print(key)

Gatwick Airport drone incident

In [ ]:
#Checking
all_origin = set()
for key, value in c4a_pages_db.items():
  if value["SE_Category"] == "-":
    all_origin.add(value['origin_title'])
all_origin = list(all_origin)
all_origin.sort()
all_origin

['Category:2001 anthrax attacks',
 'Category:Richard of Shrewsbury, Duke of York',
 'Category:Unsolved airliner bombings',
 'Category:Unsolved airliner bombings in the United States',
 'Category:Unsolved arsons',
 'Category:Unsolved crimes',
 'Category:Unsolved crimes in Australia',
 'Category:Unsolved crimes in Belize',
 'Category:Unsolved crimes in Brazil',
 'Category:Unsolved crimes in Canada',
 'Category:Unsolved crimes in China',
 'Category:Unsolved crimes in Costa Rica',
 'Category:Unsolved crimes in England',
 'Category:Unsolved crimes in Europe',
 'Category:Unsolved crimes in France',
 'Category:Unsolved crimes in Germany',
 'Category:Unsolved crimes in India',
 'Category:Unsolved crimes in Ireland',
 'Category:Unsolved crimes in Israel',
 'Category:Unsolved crimes in Italy',
 'Category:Unsolved crimes in Japan',
 'Category:Unsolved crimes in Nicaragua',
 'Category:Unsolved crimes in Nigeria',
 'Category:Unsolved crimes in South Africa',
 'Category:Unsolved crimes in Thailand',
 'Category:Unsolved crimes in the Netherlands',
 'Category:Unsolved crimes in the United Kingdom',
 'Category:Unsolved crimes in the United States']

### Location

In [ ]:
cc = coco.CountryConverter()

In [ ]:
with open(f"{SAVEFILE_DIR}cleaning_pages_db_4c.json", "r", encoding="utf-8") as f:
    c4c_pages_db = json.load(f)
print("--- Progress Loaded from Checkpoint ---")

--- Progress Loaded from Checkpoint ---

In [ ]:
for keys, value in c4c_pages_db.items():
  infobox = value['infobox']
  infobox_country = infobox.get('Country',None)
  infobox_location = infobox.get('Location',None)
  infobox_place = infobox.get('Place',None)
  se_location = "-"
  full_location = "-"
  if infobox_country:
    country = cc.convert(infobox_country,to = 'name')
    if country != 'not found':
      se_location = cc.convert(infobox_country,to = 'name')
      if infobox_location:
        full_location = infobox_location
        if cc.convert(infobox_location[-1])=='not found':
          full_location += f", {se_location}"
  elif infobox_location:
    full_location = infobox_location
    parts = [p.strip() for p in full_location.split(',')]
    country = cc.convert(parts[-1],to = 'name')
    if country != 'not found':
      se_location = country
  elif infobox_place:
    full_location = infobox_place
    parts = [p.strip() for p in full_location.split(',')]
    country = cc.convert(parts[-1],to = 'name')
    if country != 'not found':
      se_location = country
  value['SE_Location'] = se_location
  value['Full Location'] = full_location

WARNING:country_converter.country_converter:t not found in regex
WARNING:country_converter.country_converter:Reading not found in regex
WARNING:country_converter.country_converter:New York not found in regex
WARNING:country_converter.country_converter:U.S.[1] not found in regex
WARNING:country_converter.country_converter:Jerusalem not found in regex
WARNING:country_converter.country_converter:West Bengal not found in regex
WARNING:country_converter.country_converter:Illinois not found in regex
WARNING:country_converter.country_converter:Arizona not found in regex
WARNING:country_converter.country_converter:D.C. not found in regex
WARNING:country_converter.country_converter:Paris not found in regex
WARNING:country_converter.country_converter:andVolgodonsk not found in regex
WARNING:country_converter.country_converter:New York City not found in regex
WARNING:country_converter.country_converter:New York City not found in regex
WARNING:country_converter.country_converter:e not found in regex
WARNING:country_converter.country_converter:Melbourne not found in regex
WARNING:country_converter.country_converter:Beijing not found in regex
WARNING:country_converter.country_converter:16th arrondissement of Paris not found in regex
WARNING:country_converter.country_converter:Gajraula not found in regex
WARNING:country_converter.country_converter:e not found in regex
WARNING:country_converter.country_converter:betweenKita-SenjuandAyaseStations (body found) not found in regex
WARNING:country_converter.country_converter:Location not found in regex
WARNING:country_converter.country_converter:a not found in regex
WARNING:country_converter.country_converter:Florida not found in regex
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa
WARNING:country_converter.country_converter:More than one regular expression match for Italy,Switzerland,Germany,South Africa

In [ ]:
for keys, value in c4c_pages_db.items():
  if value['SE_Location']=="-":
    if value['origin_title'].startswith('Category:Missing person cases in '):
      country = cc.convert(value['origin_title'][33:],to = 'name')
      if country != 'not found':
        value['SE_Location'] = country
        value['Full Location'] = country
    elif value['origin_title'].startswith('Category:Enforced disappearances in '):
      country = cc.convert(value['origin_title'][36:],to = 'name')
      if country != 'not found':
        value['SE_Location'] = country
        value['Full Location'] = country
    elif value['origin_title'].startswith('Category:Unsolved crimes in '):
      country = cc.convert(value['origin_title'][28:],to = 'name')
      if country != 'not found':
        value['SE_Location'] = country
        value['Full Location'] = country

WARNING:country_converter.country_converter:Europe not found in regex
WARNING:country_converter.country_converter:Europe not found in regex
WARNING:country_converter.country_converter:Europe not found in regex
WARNING:country_converter.country_converter:Africa not found in regex
WARNING:country_converter.country_converter:Africa not found in regex
WARNING:country_converter.country_converter:Africa not found in regex
WARNING:country_converter.country_converter:Africa not found in regex
WARNING:country_converter.country_converter:Africa not found in regex
WARNING:country_converter.country_converter:Africa not found in regex
WARNING:country_converter.country_converter:Africa not found in regex
WARNING:country_converter.country_converter:Africa not found in regex
WARNING:country_converter.country_converter:Africa not found in regex
WARNING:country_converter.country_converter:Africa not found in regex
WARNING:country_converter.country_converter:Africa not found in regex
WARNING:country_converter.country_converter:Africa not found in regex
WARNING:country_converter.country_converter:Africa not found in regex
WARNING:country_converter.country_converter:Asia not found in regex
WARNING:country_converter.country_converter:Asia not found in regex
WARNING:country_converter.country_converter:Asia not found in regex
WARNING:country_converter.country_converter:Asia not found in regex
WARNING:country_converter.country_converter:Europe not found in regex
WARNING:country_converter.country_converter:Europe not found in regex
WARNING:country_converter.country_converter:Europe not found in regex
WARNING:country_converter.country_converter:Europe not found in regex
WARNING:country_converter.country_converter:Europe not found in regex
WARNING:country_converter.country_converter:Europe not found in regex
WARNING:country_converter.country_converter:North America not found in regex
WARNING:country_converter.country_converter:North America not found in regex
WARNING:country_converter.country_converter:South America not found in regex
WARNING:country_converter.country_converter:Northern Ireland not found in regex
WARNING:country_converter.country_converter:Northern Ireland not found in regex
WARNING:country_converter.country_converter:Northern Ireland not found in regex
WARNING:country_converter.country_converter:Northern Ireland not found in regex
WARNING:country_converter.country_converter:Scotland not found in regex
WARNING:country_converter.country_converter:Scotland not found in regex
WARNING:country_converter.country_converter:Scotland not found in regex
WARNING:country_converter.country_converter:Scotland not found in regex
WARNING:country_converter.country_converter:Scotland not found in regex
WARNING:country_converter.country_converter:Scotland not found in regex
WARNING:country_converter.country_converter:Scotland not found in regex
WARNING:country_converter.country_converter:Scotland not found in regex
WARNING:country_converter.country_converter:Wales not found in regex
WARNING:country_converter.country_converter:Wales not found in regex
WARNING:country_converter.country_converter:Wales not found in regex
WARNING:country_converter.country_converter:Wales not found in regex
WARNING:country_converter.country_converter:Wales not found in regex
WARNING:country_converter.country_converter:Yugoslavia not found in regex
WARNING:country_converter.country_converter:Yugoslavia not found in regex
WARNING:country_converter.country_converter:Yugoslavia not found in regex
WARNING:country_converter.country_converter:the Ottoman Empire not found in regex
WARNING:country_converter.country_converter:the Ottoman Empire not found in regex
WARNING:country_converter.country_converter:the Ottoman Empire not found in regex
WARNING:country_converter.country_converter:the Soviet Union not found in regex
WARNING:country_converter.country_converter:the Soviet Union not found in regex
WARNING:country_converter.country_converter:the Soviet Union not found in regex
WARNING:country_converter.country_converter:the Soviet Union not found in regex
WARNING:country_converter.country_converter:London not found in regex
WARNING:country_converter.country_converter:British Columbia not found in regex

In [ ]:
for keys, value in c4c_pages_db.items():
  if value['SE_Location']=="-":
    if value['origin_title'].startswith('Category:Unsolved murders in '):
      country = cc.convert(value['origin_title'][29:],to = 'name')
      if country != 'not found':
        value['SE_Location'] = country
        value['Full Location'] = country

WARNING:country_converter.country_converter:Africa not found in regex
WARNING:country_converter.country_converter:Africa not found in regex
WARNING:country_converter.country_converter:Africa not found in regex
WARNING:country_converter.country_converter:Africa not found in regex
WARNING:country_converter.country_converter:Africa not found in regex
WARNING:country_converter.country_converter:Asia not found in regex
WARNING:country_converter.country_converter:Asia not found in regex
WARNING:country_converter.country_converter:South America not found in regex
WARNING:country_converter.country_converter:South America not found in regex
WARNING:country_converter.country_converter:the Soviet Union not found in regex
WARNING:country_converter.country_converter:the Soviet Union not found in regex
WARNING:country_converter.country_converter:the Soviet Union not found in regex
WARNING:country_converter.country_converter:the Soviet Union not found in regex
WARNING:country_converter.country_converter:the Soviet Union not found in regex
WARNING:country_converter.country_converter:Northern Ireland not found in regex
WARNING:country_converter.country_converter:Northern Ireland not found in regex
WARNING:country_converter.country_converter:London not found in regex
WARNING:country_converter.country_converter:Scotland not found in regex
WARNING:country_converter.country_converter:Scotland not found in regex
WARNING:country_converter.country_converter:Scotland not found in regex
WARNING:country_converter.country_converter:Scotland not found in regex
WARNING:country_converter.country_converter:Scotland not found in regex
WARNING:country_converter.country_converter:Scotland not found in regex
WARNING:country_converter.country_converter:Scotland not found in regex
WARNING:country_converter.country_converter:Scotland not found in regex
WARNING:country_converter.country_converter:Scotland not found in regex
WARNING:country_converter.country_converter:Wales not found in regex
WARNING:country_converter.country_converter:Wales not found in regex
WARNING:country_converter.country_converter:Wales not found in regex
WARNING:country_converter.country_converter:Utah Territory not found in regex
WARNING:country_converter.country_converter:Utah Territory not found in regex
WARNING:country_converter.country_converter:London not found in regex
WARNING:country_converter.country_converter:London not found in regex
WARNING:country_converter.country_converter:London not found in regex
WARNING:country_converter.country_converter:London not found in regex
WARNING:country_converter.country_converter:London not found in regex
WARNING:country_converter.country_converter:London not found in regex
WARNING:country_converter.country_converter:London not found in regex
WARNING:country_converter.country_converter:London not found in regex
WARNING:country_converter.country_converter:London not found in regex
WARNING:country_converter.country_converter:London not found in regex
WARNING:country_converter.country_converter:London not found in regex
WARNING:country_converter.country_converter:London not found in regex
WARNING:country_converter.country_converter:London not found in regex
WARNING:country_converter.country_converter:London not found in regex
WARNING:country_converter.country_converter:London not found in regex
WARNING:country_converter.country_converter:London not found in regex
WARNING:country_converter.country_converter:London not found in regex
WARNING:country_converter.country_converter:London not found in regex
WARNING:country_converter.country_converter:London not found in regex
WARNING:country_converter.country_converter:London not found in regex
WARNING:country_converter.country_converter:London not found in regex
WARNING:country_converter.country_converter:London not found in regex
WARNING:country_converter.country_converter:London not found in regex
WARNING:country_converter.country_converter:London not found in regex
WARNING:country_converter.country_converter:London not found in regex
WARNING:country_converter.country_converter:London not found in regex
WARNING:country_converter.country_converter:London not found in regex
WARNING:country_converter.country_converter:London not found in regex

In [ ]:
map_l ={
    "Category:Missing person cases in London":('United Kingdom','London, United Kingdom'),
    "Category:Missing person cases in Scotland":('United Kingdom','United Kingdom'),
    "Category:Missing person cases in Wales":('United Kingdom','United Kingdom'),
    "Category:Unidentified American criminals":("United States","United States"),
    "Category:Unidentified American rapists":("United States","United States"),
    "Category:Unidentified British rapists":('United Kingdom','United Kingdom'),
    "Category:Unidentified British serial killers":('United Kingdom','United Kingdom'),
    "Category:Unidentified Canadian criminals":('Canada','Canada'),
    "Category:Unidentified murder victims in the United Kingdom":('United Kingdom','United Kingdom'),
    "Category:Unidentified murder victims in the United States":("United States","United States"),
    "Category:Unsolved airliner bombings in the United States":("United States","United States"),
    "Category:Unsolved mass murders in California":("United States","United States"),
    "Category:Unsolved mass murders in Georgia (U.S. state)":("United States","United States"),
    "Category:Unsolved mass murders in Northern Ireland":('United Kingdom','United Kingdom'),
    "Category:Unsolved mass murders in the United States":("United States","United States"),
"Category:Unsolved murders in London":('United Kingdom','United Kingdom'),
"Category:Unsolved murders in Northern Ireland":('United Kingdom','United Kingdom'),
"Category:Unsolved murders in Scotland":('United Kingdom','United Kingdom'),
"Category:Unsolved murders in Utah Territory":("United States","United States"),
"Category:Unsolved murders in Wales":('United Kingdom','United Kingdom'),
"Category:Unsolved murders in the Soviet Union":("United States","United States"),
"Category:Missing person cases in Northern Ireland":('United Kingdom','United Kingdom')

}
map1 = {
    'Category:Unidentified American serial killers': 'United States',
'Category:Unidentified British criminals': 'United Kingdom',
    'Category:Missing American children': 'United States',
    'Category:Missing American people': 'United States',
    'Category:Missing Argentine people': 'Argentina',
    'Category:Missing Austrian people': 'Austria',
    'Category:Missing Belgian people': 'Belgium',
    'Category:Missing Brazilian people': 'Brazil',
    'Category:Missing British people': 'United Kingdom',
    'Category:Missing Canadian people': 'Canada',
    'Category:Missing Chinese people': 'China',
    'Category:Missing Colombian people': 'Colombia',
    'Category:Missing English people': 'United Kingdom',
    'Category:Missing Finnish people': 'Finland',
    'Category:Missing French children': 'France',
    'Category:Missing French people': 'France',
    'Category:Missing German children': 'Germany',
    'Category:Missing German people': 'Germany',
    'Category:Missing Indian people': 'India',
    'Category:Missing Indonesian people': 'Indonesia',
    'Category:Missing Iranian people': 'Iran',
    'Category:Missing Irish people': 'Ireland',
    'Category:Missing Israeli people': 'Israel',
    'Category:Missing Italian children': 'Italy',
    'Category:Missing Italian people': 'Italy',
    'Category:Missing Japanese people': 'Japan',
    'Category:Missing Malaysian people': 'Malaysia',
    'Category:Missing New Zealand people': 'New Zealand',
    'Category:Missing Nigerian people': 'Nigeria',
    'Category:Missing Pakistani people': 'Pakistan',
    'Category:Missing Palestinian people': 'Palestine',
    'Category:Missing Russian people': 'Russia',
    'Category:Missing Scottish people': 'United Kingdom',
    'Category:Missing South African people': 'South Africa',
    'Category:Missing South Korean people': 'South Korea',
    'Category:Missing Swedish people': 'Sweden',
    'Category:Missing Swiss people': 'Switzerland',
    'Category:Missing Syrian people': 'Syria',
    'Category:Missing Ugandan people': 'Uganda',
    'Category:Missing Ukrainian people': 'Ukraine'
}

In [ ]:
for keys, value in c4c_pages_db.items():
  if value['SE_Location']!="-":
    continue
  if value['origin_title'] in map_l:
    c2 = map_l[value['origin_title']]
    value['SE_Location'] =c2[0]
    value['Full Location'] =c2[1]
  elif value['origin_title'] in map1:
    c = map1[value['origin_title']]
    value['SE_Location'] =c
    value['Full Location'] =c

In [ ]:
count=0
for keys, value in c4c_pages_db.items():
  if value['SE_Location']=="-":
    #print(keys)
    #break
    count+=1
print(count)

3218

In [ ]:
origins = set()
for keys, value in c4c_pages_db.items():
  if value['SE_Location']=="-":
    origins.add(value['origin_title'])
origins = list(origins)
origins.sort()
for i in origins:
  print(i)

Category:1490s missing person cases
Category:1500s missing person cases
Category:1570s missing person cases
Category:1580s missing person cases
Category:1590s missing person cases
Category:1620s missing person cases
Category:1670s missing person cases
Category:1700s missing person cases
Category:1730s missing person cases
Category:1790s missing person cases
Category:17th-century missing person cases
Category:1800s missing person cases
Category:1810s missing person cases
Category:1820s missing person cases
Category:1830s missing person cases
Category:1840s missing person cases
Category:1850s missing person cases
Category:1860s missing person cases
Category:1870s missing person cases
Category:1880s missing person cases
Category:1890s missing person cases
Category:1900s missing person cases
Category:1910s missing person cases
Category:1920s missing person cases
Category:1930s missing person cases
Category:1940s missing person cases
Category:1950s missing person cases
Category:1960s missing person cases
Category:1970s missing person cases
Category:1980s missing person cases
Category:1990s missing person cases
Category:2000s missing person cases
Category:2010s missing person cases
Category:2020s missing person cases
Category:20th-century missing person cases
Category:21st-century missing person cases
Category:Aerial disappearances
Category:Aerial disappearances of military personnel in action
Category:Bermuda Triangle
Category:Disappeared journalists
Category:Enforced disappearances
Category:Enforced disappearances in the Soviet Union
Category:Formerly missing people
Category:Lost buildings and structures
Category:Lost explorers
Category:Lost objects
Category:Lost sailing vessels
Category:Lost works of art
Category:Mass disappearances
Category:Mexican missing people activists
Category:Military personnel missing in action
Category:Missing air passengers
Category:Missing aircraft
Category:Missing and Murdered Indigenous Women and Girls activists
Category:Missing aviators
Category:Missing children
Category:Missing fugitives
Category:Missing gangsters
Category:Missing in action of World War I
Category:Missing in action of World War II
Category:Missing people
Category:Missing people activists
Category:Missing people identified through genetic genealogy
Category:Missing person cases in Africa
Category:Missing person cases in Asia
Category:Missing person cases in British Columbia
Category:Missing person cases in Europe
Category:Missing person cases in North America
Category:Missing person cases in South America
Category:Missing person cases in Yugoslavia
Category:Missing person cases in the Ottoman Empire
Category:Missing scientists investigation
Category:Missing ships
Category:Missing ships of Australia
Category:Missing submarines
Category:Missing submarines of World War II
Category:People declared dead in absentia
Category:People lost at sea
Category:Terrorist incidents by unknown perpetrators
Category:Unexplained_disappearances
Category:Unidentified criminals
Category:Unidentified murder victims
Category:Unidentified murderers
Category:Unidentified rapists
Category:Unidentified serial killers
Category:Unsolved airliner bombings
Category:Unsolved arsons
Category:Unsolved crimes
Category:Unsolved crimes in Europe
Category:Unsolved mass murders
Category:Unsolved murders
Category:Unsolved murders in Africa
Category:Unsolved murders in Asia
Category:Unsolved murders in South America
List of missing ships
List of people who disappeared mysteriously (1970s)
List of people who disappeared mysteriously (1980s)
List of people who disappeared mysteriously (1990s)
List of people who disappeared mysteriously (2000–present)
List of people who disappeared mysteriously at sea
List of unsolved deaths
List of unsolved murders (1900–1979)
List of unsolved murders (1980–1999)
List of unsolved murders (2000–present)
List of unsolved murders (before 1900)
List of unsolved murders in Belize
List_of_fugitives_from_justice_who_disappeared
Lists of unsolved murders
Missing aircraft
Unidentified British serial killers
Unsolved murders in London

In [ ]:
error guard
with open(f"{SAVEFILE_DIR}cleaning_pages_db_4d.json", "w", encoding="utf-8") as f:
    json.dump(c4c_pages_db, f, ensure_ascii=False, indent=4)

In [ ]:
c4c_pages_db.pop("Operation Identify Me",None)

{'origin_title': 'Category:Unsolved crimes in Europe',
 'url': 'https://en.wikipedia.org/wiki/Operation_Identify_Me',
 'last_update_text': 'This page was last edited on 19 May 2026, at 05:33(UTC).',
 'summary': 'Operation Identify Me was launched on 10 May 2023 by Interpol to solve cold cases across Western Europe to identify 22 unidentified women who were found deceased in the Netherlands, Belgium and Germany between 1976 and 2019. Most of the women were murdered, and none had ever been identified.\nA public appeal was made for information surrounding the unidentified women. Interpol alongside Dutch, German, and Belgian police forces released forensic facial reconstructions as well as other information used in the investigations. It is believed some of the murdered women may be from parts of Eastern Europe.\nThe second phase of the project was launched in October 2024. The 46 newly publicised cases were expanded to France, Italy and Spain.\n\nSince its inception, five women have been identified.',
 'infobox': {},
 'sections_tree': [{'title': 'Cases (2023)',
   'content': ['The suspected murder cases in the first phase span five decades. The bodies were discovered between October 1976 and August 2019. Their average ages range from 15 to 30. Most of the women suffered violent deaths.']},
  {'title': 'Cases (2024)', 'content': ['']},
  {'title': 'Further inquiries',
   'content': ['On 16 May 2023, it was reported that police had received over 200 tip-offs regarding the cases, with 122 tips from Germany, 55 from Belgium and 51 from the Netherlands, some of them with names. Near the end of August, the number of tips had increased to over 500. By November police said they had received about 1,250 tips.\nOn August 29, 2023, Interpol made a public appeal on the identification of an unidentified dead boy in Großmehring, Bavaria, Germany. While the unknown dead child was not officially added in Operation Identify Me, he was part of an effort to publicly request tips for unidentified decedents.']},
  {'title': 'Identifications',
   'content': ['In November 2023, "The woman with the flower tattoo" was named as British woman Rita Roberts. Roberts was 31 years old when she moved from Cardiff to Antwerp in February 1992 but was reported missing months later. Due to the publicization of the case, a member of her family in Britain recognised the tattoo and contacted the Belgian authorities to formally identify the body.\nIn mid-March 2025, a second phase case called "The woman in the shed" of 2018 was identified as Ainoha Izaga Ibieta Lima from Paraguay through fingerprints comparison. She was last contacted in 2018 and was reported missing by her brother months later.\nIn September 2025, "The woman in pink" was identified as Russian citizen Liudmila Zavada because of Turkish authorities\' fingerprint analysis. She was so named for the pink top, pink trousers, and pink shoes she was wearing. She had been dead for less than 24 hours at the time of discovery, and her death was considered suspicious by Spanish police. Her body was discovered by the side of a road in Viladecans near Barcelona on 3 July 2005.\nBarely a month after the previous identification, "The woman with German keys" was identified as German citizen, Eva Pommer after a vital tip about her. There was no mention if she was from Eastern Europe while being a German citizen.\nIn March 2026, the woman with the Richmond dental crown was identified as Hakima Boukerouis. French police made an arrest in connection to her death.\nIn May 2026, the identification of "The girl in the River Main" as "Diana S." was announced. On 12 May 2026, the victim\'s father, a 67-year-old German citizen, was arrested by the Hessian State Criminal Police Office on suspicion of her murder.']}],
 'categories': ['Category:2023 establishments in Europe',
  'Category:Articles with short description',
  'Category:CS1 Dutch-language sources (nl)',
  'Category:CS1 French-language sources (fr)',
  'Category:CS1 German-language sources (de)',
  'Category:CS1 maint: deprecated archival service',
  'Category:Death of women',
  'Category:History of women in Belgium',
  'Category:History of women in Germany',
  'Category:History of women in the Netherlands',
  'Category:Interpol',
  'Category:Murder investigation',
  'Category:Short description matches Wikidata',
  'Category:Unidentified murder victims',
  'Category:Unsolved crimes in Europe',
  'Category:Unsolved murders in Belgium',
  'Category:Unsolved murders in Europe',
  'Category:Unsolved murders in France',
  'Category:Unsolved murders in Germany',
  'Category:Unsolved murders in Italy',
  'Category:Unsolved murders in Spain',
  'Category:Unsolved murders in the Netherlands',
  'Category:Violence against women in Europe',
  'Category:Women in Europe'],
 'SE_Category': 'murder',
 'SE_Location': '-',
 'Full Location': '-'}

In [ ]:
page_with_hole = set()

In [ ]:
def clean_sections_recursive(keys, sections, path=""):
    # Iterate backwards so we can delete while looping
    for i in range(len(sections) - 1, -1, -1):
        section = sections[i]
        title = section.get('title', 'Unknown')
        current_path = f"{path} > {title}" if path else title

        content_list = section.get('content', [])

        # 1. Look for a list inside 'content' (these are the subsections)
        for j in range(len(content_list) - 1, -1, -1):
            if isinstance(content_list[j], list):
                # Recurse into the subsections
                clean_sections_recursive(keys, content_list[j], current_path)

                # If the subsections list is now empty, remove it from content
                if len(content_list[j]) == 0:
                    content_list.pop(j)

        # 2. Check if the section is now "Empty"
        # Criteria: content is just [""] or is completely empty []
        is_only_empty_string = len(content_list) == 1 and content_list[0] == ""
        is_completely_empty = len(content_list) == 0

        if is_only_empty_string or is_completely_empty:
            print(f"Deleted empty section: {current_path}")
            found_table = False
            #for table in c4c_pages_db[keys]['table']:
            #  if table["section"]==title:
            #    found_table = True
            #    break
            #if not found_table:
            #  print(f"Deleted {keys} [empty]:{current_path}")
              #page_with_hole.add(keys)
              #sections.pop(i)

In [ ]:
backup = c4c_pages_db.copy()

In [ ]:
for keys, value in c4c_pages_db.items():
  #if not keys in rm_holes:
  #  continue
  section_tree = value["sections_tree"]
  clean_sections_recursive(keys,section_tree)

Deleted empty section: The firefighters
Deleted empty section: Timeline
Deleted empty section: Robberies
Deleted empty section: Victims
Deleted empty section: Motorsports career results > NASCAR > Craftsman Truck Series
Deleted empty section: Supreme Court decision > Composition
Deleted empty section: Known victims > Cases that were included, but later ruled out
Deleted empty section: Known victims > Cases linked to the murders
Deleted empty section: Race summary
Deleted empty section: Crews of Flight 19 and PBM-5 BuNo 59225
Deleted empty section: Vehicle details
Deleted empty section: Notable search efforts
Deleted empty section: Disappearance theories
Deleted empty section: International competitions
Deleted empty section: Windisch victories
Deleted empty section: Tables > Second raiding cruise
Deleted empty section: Tables > First raiding cruise
Deleted empty section: List of Wikipedia articles on notable finds
Deleted empty section: Legal proceedings > Convictions and sentences
Deleted empty section: Arms
Deleted empty section: Death > Ships attacked
Deleted empty section: Statistics
Deleted empty section: Summary of Career > Ships attacked
Deleted empty section: Summary of Career > Ships sunk
Deleted empty section: Summary of career > Ships attacked
Deleted empty section: Ships attacked
Deleted empty section: Summary of career > Ships sunk
Deleted empty section: Summary of career > Ships sunk
Deleted empty section: Theatre credits
Deleted empty section: Complete filmography
Deleted empty section: Participants of the rescue and search efforts
Deleted empty section: War record
Deleted empty section: Ships sunk
Deleted empty section: Arms
Deleted empty section: Timeline of investigations
Deleted empty section: Career achievements > Grand Tour results timeline
Deleted empty section: Suspicious deaths > 2026
Deleted empty section: Suspicious deaths > 2025
Deleted empty section: Suspicious deaths > 2024
Deleted empty section: Suspicious deaths > 2023
Deleted empty section: Suspicious deaths > 2022
Deleted empty section: Victims
Deleted empty section: History > Partial list of incidents
Deleted empty section: Robberies > List of robberies
Deleted empty section: Murders
Deleted empty section: Murders > Victims
Deleted empty section: Dates of rank
Deleted empty section: TV credits
Deleted empty section: List of discoveries
Deleted empty section: Disappearance > Timeline
Deleted empty section: Homicide suspicions and conspiracy theories > Opinion polls
Deleted empty section: Stage credits
Deleted empty section: Military career > Awards and decorations
Deleted empty section: Radio
Deleted empty section: Distinctions
Deleted empty section: Achievements
Deleted empty section: Medals and Decorations
Deleted empty section: Dates of rank
Deleted empty section: Timeline
Deleted empty section: Forced disappearance > Timeline of events
Deleted empty section: Racing record > Complete 12 Hours of Sebring results
Deleted empty section: Racing record > Complete 24 Hours of Daytona results
Deleted empty section: Racing record > Complete 24 Hours of Le Mans results
Deleted empty section: Racing record > Career highlights
Deleted empty section: Competition record
Deleted empty section: Timeline
Deleted empty section: Hostages count
Deleted empty section: Key events
Deleted empty section: Disappearance > Timeline
Deleted empty section: Later recognition > Types of Le Prince cine camera-projectors
Deleted empty section: Stage
Deleted empty section: Arms
Deleted empty section: SS and police ranks
Deleted empty section: Olympic results
Deleted empty section: Known members
Deleted empty section: Racing record > Indianapolis 500 results
Deleted empty section: Racing record > Complete Carrera Panamericana results
Deleted empty section: Racing record > Complete Mille Miglia results
Deleted empty section: Racing record > Complete 24 Hours of Spa
Deleted empty section: Racing record > Complete 12 Hours of Sebring results
Deleted empty section: Racing record > Complete 24 Hours of Le Mans results
Deleted empty section: Racing record > World Sportscar Championship results
Deleted empty section: Racing record > Career highlights
Deleted empty section: Sentences
Deleted empty section: Demographics > Racial and ethnic composition
Deleted empty section: Claims
Deleted empty section: Service history > Summary
Deleted empty section: Military service > List of aerial victories
Deleted empty section: Rugby Union career > International career > International appearances
Deleted empty section: Head coaching record > College football
Deleted empty section: Records purportedly related to Wallace Fard Muhammad
Deleted empty section: Head coaching record > College football
Deleted empty section: Records > Other accomplishments > 24 Hours of Le Mans results
Deleted empty section: NBA career statistics > Playoffs
Deleted empty section: NBA career statistics > Regular season

In [ ]:
error guard
with open(f"{SAVEFILE_DIR}cleaning_pages_db_4e.json", "w", encoding="utf-8") as f:
    json.dump(c4c_pages_db, f, ensure_ascii=False, indent=4)

### Image, Table, and Cleaning Text

In [ ]:
with open(f"{SAVEFILE_DIR}cleaning_pages_db_4e.json", "r", encoding="utf-8") as f:
    c4e_pages_db = json.load(f)
print("--- Progress Loaded from Checkpoint ---")

--- Progress Loaded from Checkpoint ---

In [ ]:
WAIT_RANGE = (1,3)

In [ ]:
start_index = 2892

In [ ]:
"images" in c4e_pages_db["Elfrieda Knaak"]

True

In [ ]:
error_page = []

In [ ]:
error_page

['Tracy Allard',
 'Michèle Audette',
 'Tanya Kappo',
 'Lesa Semmler',
 'Dawn Dumont']

In [ ]:
import requests
import json
import re
from bs4 import BeautifulSoup

def get_span_value(cell, attr):
    """Extracts the leading integer from a span attribute, handling malformed HTML."""
    val = cell.get(attr, "1")
    # Match only the digits at the beginning of the string
    match = re.match(r'^(\d+)', str(val).strip())
    return int(match.group(1)) if match else 1

def record_page_tables_as_json(title):
    headers = {'User-Agent': 'MysteryBotName (email@example.com)'}
    url = f"https://en.wikipedia.org/wiki/{title.replace(' ', '_')}"
    response = requests.get(url, headers=headers)
    soup = BeautifulSoup(response.content, 'html.parser')

    content = soup.find('div', class_='mw-parser-output')
    if not content: return []

    scraped_tables = []
    current_hierarchy = {2: "Introduction", 3: None, 4: None, 5: None, 6: None}

    for tag in content.find_all(['h2', 'h3', 'h4', 'h5', 'h6', 'table']):
        if tag.name in ['h2', 'h3', 'h4', 'h5', 'h6']:
            level = int(tag.name[1])
            current_hierarchy[level] = tag.get_text(strip=True).replace('[edit]', '')
            for i in range(level + 1, 7): current_hierarchy[i] = None

        elif tag.name == 'table' and 'wikitable' in tag.get('class', []):
            caption_tag = tag.find('caption')
            table_obj = {
                "section_hierarchy": [current_hierarchy[i] for i in range(2, 7) if current_hierarchy[i]],
                "caption": caption_tag.get_text(strip=True) if caption_tag else None,
                "rows": []
            }

            for tr in tag.find_all('tr'):
                row_cells = []
                for cell in tr.find_all(['td', 'th']):
                    row_cells.append({
                        "text": cell.get_text(strip=True),
                        "is_header": cell.name == 'th',
                        "rowspan": get_span_value(cell, 'rowspan'),
                        "colspan": get_span_value(cell, 'colspan')
                    })
                if row_cells:
                    table_obj["rows"].append(row_cells)

            scraped_tables.append(table_obj)

    return scraped_tables

In [ ]:
table = record_page_tables_as_json('Michèle Audette')

In [ ]:
for keys in error_page:
  value = c4e_pages_db[keys]
  table = record_page_tables_as_json(keys)
  imgs, error = get_img(keys)
  if error:
      crawl_errors[keys] = error
  value["table"] = table
  value["images"]= imgs
  count += 1
  if count > batch:
    count = 0
    time.sleep(random.uniform(*WAIT_RANGE))

In [ ]:

for keys, value in tqdm(c4e_pages_db.items()):
    if not "images" in value:
      print(keys)
      break

100%|██████████| 4926/4926 [00:00<00:00, 286860.69it/s]

In [ ]:
with open(f"{SAVEFILE_DIR}cleaning_pages_db_4f.json", "w", encoding="utf-8") as f:
    json.dump(c4e_pages_db, f, ensure_ascii=False, indent=4)

In [ ]:
with open(f"{SAVEFILE_DIR}cleaning_pages_db_4f.json", "r", encoding="utf-8") as f:
    c4f_pages_db = json.load(f)
print("--- Progress Loaded from Checkpoint ---")

--- Progress Loaded from Checkpoint ---

In [ ]:
import re

def clean_all_keys(data):
    """
    Recursively wanders through nested dictionaries and lists to clean strings.
    """
    if isinstance(data, dict):
        return {k: clean_all_keys(v) if not k.lower() in ["website"] else v for k, v in data.items()}
    elif isinstance(data, list):
        return [clean_all_keys(item) for item in data]
    elif isinstance(data, str):
        return transform_text(data)
    else:
        return data

def clean_wikipedia_text(data):
    if isinstance(data, dict):
        # Only clean 'text', 'caption', and 'section_hierarchy'
        # Do NOT clean fields like 'src', 'url', or 'is_header'
        return {
            k: clean_wikipedia_text(v) if k.lower() in ['text', 'caption', 'section_hierarchy'] else v
            for k, v in data.items()
        }
    elif isinstance(data, list):
        return [clean_wikipedia_text(item) for item in data]
    elif isinstance(data, str):
        return transform_text(data)
    return data

def transform_text(text):
    # Remove citations and [edit] tags
    text = re.sub(r'\[\d+\]|\[[a-zA-Z]+\s*\d*\]|\[edit\]', '', text)

    # SAFER Phonetic removal: Look for IPA characters specifically
    # or ensure we aren't stripping a URL (check if it starts with http)
    if not text.startswith('http'):
        text = re.sub(r'\/[^\/]{2,}\/', '', text) # Minimum 2 chars inside slashes

    # Replace weird spaces but KEEP single newlines in tables
    text = text.replace('\xa0', ' ')

    # Collapse multiple horizontal spaces, but preserve single newlines
    text = re.sub(r'[ \t]+', ' ', text)

    return text.strip()

# --- Example for testing ---
wiki_data = {
    "title": "Python (programming language)",
    "content": ["Python was conceived in the late 1980s [1].", "It is used in AI /ˌaɪˈiː/.\xa0[2]"]
}

cleaned_data = clean_all_keys(wiki_data)
print(cleaned_data)

{'title': 'Python (programming language)', 'content': ['Python was conceived in the late 1980s .', 'It is used in AI .']}

In [ ]:
for keys,value in c4f_pages_db.items():
  o_last_update_text = value['last_update_text']
  value['last_update_text'] = transform_text(o_last_update_text)

  o_summary = value['summary']
  value['summary'] = transform_text(o_summary)

  o_infobox = value['infobox']
  value['infobox'] = clean_all_keys(o_infobox)

  o_section_tree = value['sections_tree']
  value['sections_tree'] = clean_all_keys(o_section_tree)

  o_table = value['table']
  value['table'] = clean_wikipedia_text(o_table)

  o_images = value['images']
  value['images'] = clean_wikipedia_text(o_images)

In [ ]:
c4f_pages_db["Christiana Mall"]

{'origin_title': 'Category:Unsolved crimes in the United States',
 'url': 'https://en.wikipedia.org/wiki/Christiana_Mall',
 'last_update_text': 'This page was last edited on 9 May 2026, at 14:36(UTC).',
 'summary': "Christiana Mall is a shopping mall located in Christiana, Delaware between the cities of Newark and Wilmington. The one-level, enclosed super-regional mall is situated at the intersection of Interstate 95 (exit 4A) and Delaware Route 1/Delaware Route 7 (DE 1 exit 164) near the center of the Northeast megalopolis.\nChristiana Mall has three anchor stores - Macy's, JCPenney, and Target - along with Barnes & Noble as a junior anchor and Cabela's and Cinemark Theatres as outparcels. The mall contains 179 shops, and is owned and managed by GGP, a subsidiary of Brookfield Properties. It has 1,267,241 square feet (117,731 m2) of gross leasable area. Christiana Mall is the largest shopping mall in the state of Delaware. The Christiana Mall is located nearly 40 miles (64 km) southwest of Center City, Philadelphia. Due to the lack of sales tax in Delaware, the mall attracts numerous shoppers from neighboring states.",
 'infobox': {'Location': 'Christiana, Delaware, United States',
  'Coordinates': '39°40′43″N75°39′10″W\ufeff 39.67861; -75.65278',
  'Address': '132 Christiana MallNewark, DE19702',
  'Opened': 'October 12, 1978; 47 years ago(1978-10-12)',
  'Developer': 'The Rubin Organization and New Castle Associates',
  'Management': 'GGP',
  'Owner': 'GGP',
  'Stores': '179',
  'Anchor tenants': '5',
  'Floor area': '1,267,241 square feet (117,731 m2)',
  'Floors': "1 (2 in Barnes & Noble, former Forever 21, JCPenney, H&M, Macy's, and former Nordstrom)",
  'Parking': 'Parking lotwith 6,300 spaces',
  'Public transit': 'DART First Statebus: 5, 15, 33, 51, 55, 64, 301, 305 at theChristiana Mall Park & Ride',
  'Website': 'christianamall.com'},
 'sections_tree': [{'title': 'Location',
   'content': ['The Christiana Mall is located in an unincorporated area of northern New Castle County, Delaware near the community of Christiana between the Delaware cities of Wilmington and Newark and the larger cities of Philadelphia and Baltimore. The mall is situated southeast of an interchange between Interstate 95 and Delaware Route 1/Delaware Route 7. Access to the mall is from exit 164 of DE 1, which connects to Mall Road, the ring road around the mall. Exit 4A of I-95 provides access to southbound DE 1 and Mall Road. The trade area surrounding Christiana Mall has a population of 680,804.\nChristiana Mall is served by DART First State bus routes 5, 15, 33, 51, 55, and 64 providing local bus service to Wilmington, Newark, and other points in New Castle County along with inter-county bus service along Route 301 to Dover and seasonal service along Route 305 to Lewes. All buses serving the Christiana Mall stop at the Christiana Mall Park & Ride near the former Nordstrom while routes 5, 15, and 51 also serve the bus stop near Target.']},
  {'title': 'Description',
   'content': ['Christiana Mall contains 1,267,241 square feet (117,731 m2) of retail space and has 182 stores. The mall is anchored by JCPenney, Macy\'s and Target, with Barnes & Noble serving as a junior anchor and Cabela\'s and Cinemark Theatres serving as outparcels. The mall has smaller retailers including Apple Store, Lululemon Athletica, Barnes & Noble, and Urban Outfitters. Christiana Mall has various dining options including a food court and restaurants such as P.F. Chang\'s and The Cheesecake Factory.\nThe Christiana Mall is a popular destination for shoppers in the Delaware Valley area centered around Philadelphia while also attracting visitors from the New York, Baltimore, and Washington, D.C. areas looking for tax-free shopping. The mall attracts over 20 million visitors annually. Christiana Mall is one of the top producing malls in the United States. The Apple Store at the Christiana Mall claims to sell more iPhones than any other location in the chain. The Christiana Mall has an appraised value of over $1 billion.\nBasketball player Charles Barkley\'s daughter, Christiana, was named after the mall. In a 2021 podcast, he explained, "...I just liked the mall."']},
  {'title': 'Incidents',
   'content': ['',
    [{'title': '2023 shooting',
      'content': ["Around 6:45 p.m. on April 8, 2023, an unnamed 18-year old was attacked by three suspects near the food court inside Christiana Mall. They began to beat the victim, and two of the victim's friends began to fight back. One of the three suspects then pulled a handgun from his waistband, shooting the targeted victim, his 16-year old friend, and another 18-year old bystander. The targeted victim and his friend were injured critically. Five others were injured in the chaos following the attack. All three attackers escaped before authorities arrived.\nA manhunt soon initiated for the three suspects, with authorities releasing a short video of the three suspects walking before the attack was initiated. There were no arrests until 11 days later, when one of the three suspects, an unnamed 17-year old surrendered himself to the police. He is held in the Division of Youth Rehabilitative Services in Wilmington on a $15,000 bail. If tried as an adult, he faces up to 6 years in prison."]}]]}],
 'categories': ['Category:1978 establishments in the United States',
  'Category:All Wikipedia articles written in American English',
  'Category:Articles with short description',
  'Category:Brookfield Properties',
  'Category:Buildings and structures in New Castle County, Delaware',
  'Category:Commons category link from Wikidata',
  'Category:Coordinates on Wikidata',
  'Category:Pages using gadget WikiMiniAtlas',
  'Category:Pages using the Kartographer extension',
  'Category:Shopping malls developed by The Rubin Organization',
  'Category:Shopping malls established in 1978',
  'Category:Shopping malls in Delaware',
  'Category:Short description is different from Wikidata',
  'Category:Tourist attractions in New Castle County, Delaware',
  'Category:Use American English from February 2025',
  'Category:Use mdy dates from April 2025'],
 'SE_Category': 'murder',
 'SE_Location': 'United States',
 'Full Location': 'Christiana, Delaware, United States',
 'table': [],
 'images': [{'url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Christiana_Mall_food_court_entrance.jpg/250px-Christiana_Mall_food_court_entrance.jpg',
   'caption': 'Entrance to the food court, 2018'},
  {'url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Christiana_Mall_from_JCPenney.jpeg/250px-Christiana_Mall_from_JCPenney.jpeg',
   'caption': 'Christiana Mall from JCPenney'},
  {'url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Christianamall1.jpg/250px-Christianamall1.jpg',
   'caption': "Wanamaker's/Lord & Taylor (now Target) wing, prior to renovations"},
  {'url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Christiana_Mall_between_Macy%27s_and_JCPenney.jpg/250px-Christiana_Mall_between_Macy%27s_and_JCPenney.jpg',
   'caption': "Christiana Mall between Macy's and JCPenney"},
  {'url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Christiana_Mall_between_Macy%27s_and_Target.jpg/250px-Christiana_Mall_between_Macy%27s_and_Target.jpg',
   'caption': "Christiana Mall between Macy's and Target"}]}

In [ ]:
with open(f"{SAVEFILE_DIR}cleaning_pages_db_4g.json", "w", encoding="utf-8") as f:
    json.dump(c4f_pages_db, f, ensure_ascii=False, indent=4)

## Flatten

In [12]:
SAVEFILE_DIR = "/content/drive/MyDrive/Mystery Search Engine/"
with open(f"{SAVEFILE_DIR}cleaning_pages_db_4e.json", "r", encoding="utf-8") as f:
    c4g_pages_db = json.load(f)
print("--- Progress Loaded from Checkpoint ---")

--- Progress Loaded from Checkpoint ---

In [13]:
elastic_docs = []

In [14]:
def restructure_page(title, data):

  page_metadata = {
    "last_update": data.get("last_update_text"),
    "full_location": data.get("Full Location"),
    "category": data.get("SE_Category"), # Use Keyword type in ES for filtering
    "location": data.get("SE_Location")   # Use Keyword type in ES for filtering
  }

  # 1. Prepare global data
  summary = data.get("summary", "")
  infobox_raw = data.get("infobox", {})
  # Flatten infobox to string: "Key1: Value1. Key2: Value2."
  infobox_str = ". ".join([f"{k}: {v}" for k, v in infobox_raw.items()])

  # Collect all image URLs for the page to include in the "Lead" doc
  image_urls = [img.get("url") for img in data.get("images", [])]

  # 2. Create the "LEAD" Document (Summary + Infobox)
  lead_doc = {
      "page_title": title,
      "section_title": "Summary",
      "breadcrumb": [title],
      "content": summary,
      "infobox": infobox_str,
      "tables": [], # Summary usually doesn't have tables
      "images": image_urls,
      "is_lead": True,
      **page_metadata
  }
  elastic_docs.append(lead_doc)

  # 3. Pre-process Tables for quick lookup
  # We've mapped them by their hierarchy joined as a string
  table_map = {}
  for table in data.get("table", []):
      # Join hierarchy list into a string key for matching
      path_key = " > ".join(table.get("section_hierarchy", []))
      path_key = title + " > "+path_key
      table_map.setdefault(path_key, []).append({
          "caption": table.get("caption"),
          "rows": table.get("rows")
      })
  #print(table_map)
  # 4. Recursively process the Section Tree
  def walk_tree(sections, parent_breadcrumb):
      #print(f"{sections} - {parent_breadcrumb}")
      for section in sections:
          current_title = section.get("title", "")
          current_breadcrumb = parent_breadcrumb + [current_title]
          breadcrumb_str = " > ".join(current_breadcrumb)
          #print(breadcrumb_str)

          section_text = ""
          subsections = []

          # Handle the "content" field (can be list of text or nested dict)
          raw_content = section.get("content", [])
          if isinstance(raw_content, list):
              for item in raw_content:
                  if isinstance(item, str):
                      section_text += item + " "
                  elif isinstance(item, dict):
                      subsections.append(item)
                  elif isinstance(item, list):
                    for subitem in item:
                      if isinstance(subitem, str):
                          section_text += subitem + " "
                      elif isinstance(subitem, dict):
                          subsections.append(subitem)
          elif isinstance(raw_content, dict):
              # If content itself is a dict, it's a subsection
              subsections.append(raw_content)

          # If this section has text or tables, create a document
          relevant_tables = table_map.get(breadcrumb_str, [])

          if section_text.strip() or relevant_tables:
              elastic_docs.append({
                  "page_title": title,
                  "section_title": current_title,
                  "breadcrumb": current_breadcrumb,
                  "content": section_text.strip(),
                  "infobox": None, # Only lead doc gets infobox
                  "tables": relevant_tables,
                  "images": [], # Subsections usually don't need all images
                  "is_lead": False,
                  **page_metadata
              })

          # Recursively go deeper
          if subsections:
              walk_tree(subsections, current_breadcrumb)

  # Start the recursion for the page
  walk_tree(data.get("sections_tree", []), [title])

In [15]:
elastic_docs = []
title = "Joseph Barboza"
data = c4g_pages_db[title]
restructure_page(title, data)
for i in elastic_docs:
  print(i['section_title'])

Summary
Early life
Professional boxing career
Escape from prison
Entry into organized crime
Turning government witness
False testimony against rivals
Death

In [16]:
len(elastic_docs)

8

In [17]:
elastic_docs

[{'page_title': 'Joseph Barboza',
  'section_title': 'Summary',
  'breadcrumb': ['Joseph Barboza'],
  'content': 'Joseph Barboza Jr. (; September 20, 1932 – February 11, 1976), nicknamed "the Animal", was an American mobster and notorious mob hitman for the Patriarca crime family of New England during the 1960s. A prominent enforcer and contract killer in Boston\'s underworld, Barboza became a Federal Bureau of Investigation (FBI) informant in 1967 and later entered the Witness Protection Program. He was a star witness in the trial of six men convicted in the 1965 murder of Edward Deegan; four of the accused were sentenced to death and another two were sentenced to life imprisonment. It later emerged that Barboza had helped frame the six defendants in a case of wrongful conviction for the Deegan killing, which was allegedly actually committed by Barboza and Vincent Flemmi. He was shot dead in San Francisco in 1976 after his whereabouts became known to Patriarca underboss Gennaro Angiulo.',
  'infobox': 'Born: Joseph Barboza Jr.(1932-09-20)September 20, 1932New Bedford, Massachusetts, U.S.. Died: February 11, 1976(1976-02-11)(aged\xa043)San Francisco, California, U.S.. Cause\xa0of death: Murder bygunshot wounds. Resting place: South Dartmouth Cemetery,Dartmouth, Massachusetts, U.S.. Other\xa0names: "The Animal""The Baron""The Wild Thing""TheJoe ValachiofNew England""Joseph Donati""Joseph Barboza Baron""Joseph Bentley". Occupation: Mobster. Children: 2. Allegiance: Patriarca crime family. Conviction: Murder (1971). Criminal penalty: 5 years\' imprisonment. Nickname: The Baron. Weight: Light heavyweight. Total\xa0fights: 11. Wins: 8. Losses: 3',
  'tables': [],
  'images': [],
  'is_lead': True,
  'last_update': 'This page was last edited on 7 April 2026, at 21:08(UTC).',
  'full_location': '-',
  'category': 'murder',
  'location': '-'},
 {'page_title': 'Joseph Barboza',
  'section_title': 'Early life',
  'breadcrumb': ['Joseph Barboza', 'Early life'],
  'content': 'Barboza was born on September 20, 1932, in New Bedford, Massachusetts, to Portuguese emigrants from Valpaços in the Alto Trás-os-Montes, Joseph Barboza Sr. (born José Barbosa), a middle-weight boxer, and Palmeda Camille, who was a seamstress. His father was a Los Angeles-based prizefighter who competed in only two professional boxing matches; his debut bout was against Pete Frisco on January 27, 1933, and his second match was against Carlos Chipres on April 27, 1933. Barboza had two brothers; Donald and Anthony Barboza and a sister, Anne Houghton.\nAlthough Barboza had less than an eighth-grade education and was barely literate, he was fluent in Portuguese, Italian and Spanish. He was married to a Jewish woman and fathered a daughter in 1965 and also a son and lived in Chelsea, Massachusetts, while employed by the Patriarca crime family.',
  'infobox': None,
  'tables': [],
  'images': [],
  'is_lead': False,
  'last_update': 'This page was last edited on 7 April 2026, at 21:08(UTC).',
  'full_location': '-',
  'category': 'murder',
  'location': '-'},
 {'page_title': 'Joseph Barboza',
  'section_title': 'Professional boxing career',
  'breadcrumb': ['Joseph Barboza', 'Professional boxing career'],
  'content': 'Barboza was a stocky, muscular man with a thick neck and an angular, watermelon-shaped skull. He would pursue a career as a professional light heavyweight boxer and member of the United States Boxing Association, using the name of "the Baron". His first boxing match on April 18, 1949, against Rocky Lucero in El Paso, Texas, and his last fight on September 23, 1961, against Don Bale in Boston. He fought with an orthodox stance. His boxing record shows Joseph as winning eight out of the eleven matches, with five of them ending in knock outs. He was classified as an out-fighter who was known for having very powerful punches. He was a sparring partner of Patriarca crime family associate, Americo Sacramone, future Massachusetts Auditor Joe DeNucci, Edward G. Connors and Anthony Veranis. He later worked as a longshoreman and as a clerk in a fruit store but always returned to crime.',
  'infobox': None,
  'tables': [],
  'images': [],
  'is_lead': False,
  'last_update': 'This page was last edited on 7 April 2026, at 21:08(UTC).',
  'full_location': '-',
  'category': 'murder',
  'location': '-'},
 {'page_title': 'Joseph Barboza',
  'section_title': 'Escape from prison',
  'breadcrumb': ['Joseph Barboza', 'Criminal career', 'Escape from prison'],
  'content': "Barboza became involved in criminal activity, including robberies and assaults, as a teenager. He was first sent to prison at the age of 18 in 1950 to the Massachusetts Correctional Institution - Concord for five years. Barboza would later lead a wild prison break in the summer of 1953, which would become the largest in the prison's seventy-five-year history. Joe and six other fellow inmates had guzzled contraband whiskey and pilfered amphetamine tablets, overpowered four prison guards and raced away in two separate cars. During their furlough of freedom they beat random people in the street, cruised the bars in Boston's Scollay Square, wandered to the neighborhoods of Lynn and Revere, and were finally apprehended at a subway station in East Boston. The escape party had barely lasted twenty-four hours. That November, while awaiting trial for his prison break, Barboza slugged a prison guard in the cafeteria for no reason. Three months later, he tossed a table at a guard's chest when he entered his cell.",
  'infobox': None,
  'tables': [],
  'images': [],
  'is_lead': False,
  'last_update': 'This page was last edited on 7 April 2026, at 21:08(UTC).',
  'full_location': '-',
  'category': 'murder',
  'location': '-'},
 {'page_title': 'Joseph Barboza',
  'section_title': 'Entry into organized crime',
  'breadcrumb': ['Joseph Barboza',
   'Criminal career',
   'Entry into organized crime'],
  'content': 'Barboza may have first been exposed to figures of Boston organized crime while incarcerated at Walpole. Paroled in 1958, he became a recognized figure in East Boston\'s organized crime circles and was a regular at a bar on the corner of Bennington Street and Brook Street, which became known among local criminals as "Barboza\'s Corner". His crew of small-time burglars and thieves consisted of Joseph W. Amico, Patrick Fabiano, James Kearns, Arthur Bratsos, Thomas DePrisco, father and son team Joseph and Ronald Dermody, Carlton Eaton, Edward Goss and Nicholas Femia. The crew was officially supervised for the Patriarca crime family by Stephen "The Rifleman" Flemmi. He was never officially inducted into the Patriarca crime family because of his non-Italian ancestry, but within eight years during the escalation of gangland warfare, he earned a reputation as one of Boston\'s most prolific contract killers and sidewalk soldiers. Due to his dark complexion and Portuguese heritage, Barboza was referred to as "the nigger" by his Italian associates. According to Patriarca associate-turned-government witness Vincent Teresa, Barboza "hated Negroes" and killed at least two victims solely due to their race. In 1964, Barboza legally changed his surname to "Baron".\nIt was widely believed in law official circles that Barboza had performed contract killings for Raymond L. S. Patriarca. By January 1966, Barboza was considered a powerful crime figure in the Boston underworld. For disturbing the peace one night, he slugged a Metropolitan District Commission Police Officer, Joe MacLean, and received a six-month sentence.\nA few notorious victims on his murder roster included Edward McLaughlin and both Cornelius Hughes and Stevie Hughes, killed between 1965 and 1966. Barboza aligned himself with the Winter Hill Gang in part because James "Buddy" McLean was an ally of Vincent Flemmi, who Barboza trusted along with his brother Stephen Flemmi. As early as 1965, Federal Bureau of Investigation (FBI) agent H. Paul Rico, was using that trust to drive Barboza into becoming an informant. Barboza drove a 1965 Oldsmobile Cutlass which was referred to by law enforcement as "the James Bond car" because it had a sophisticated alarm system and a device for making thick black smoke come out of the tailpipe.',
  'infobox': None,
  'tables': [],
  'images': [],
  'is_lead': False,
  'last_update': 'This page was last edited on 7 April 2026, at 21:08(UTC).',
  'full_location': '-',
  'category': 'murder',
  'location': '-'},
 {'page_title': 'Joseph Barboza',
  'section_title': 'Turning government witness',
  'breadcrumb': ['Joseph Barboza',
   'Criminal career',
   'Turning government witness'],
  'content': 'By 1966, he had a very turbulent position in the Boston underworld. He had been shot at while standing outside his home in Chelsea. The local authorities believed there had been other unreported attempts. Brimming with reckless power, he was not abiding to the traditional rules of La Cosa Nostra. One night he went into a nightclub that was paying Gennaro Angiulo for protection and demanded that the owner make payments to him as well. By mid-1966, the unrelenting attention from the law Barboza received from the authorities only made his standing in organized crime more tenuous.\nIn October 1966, he came to terms with his falling-out with the organized crime element after he and three local hoodlums were arrested on weapons charges while cruising the Combat Zone in Boston. His accomplices were released on bail, but Barboza had his bail set at $100,000 (nearly one million dollars in 2025 money), which he could not afford. Nobody from the Patriarca crime family came down to post his bail and he heard that it was the Mafia family who tipped off the cops.\nTwo of his associates, Bratsos and DePrisco, went to raise Barboza\'s bail. Five weeks later, after raising $59,000 the pair were murdered in the Nite Lite Cafe by soldiers serving under Ralph "Ralphie Chong" Lamattina, who served in the crew of Ilario Zannino. After relieving them of their bail money, they stuffed their bodies in the back seat of Bratsos\' car and dumped it in South Boston, hoping to throw blame onto the Irish gangs. However, a mob associate named Joseph Lanzi tipped the cops about the murder. On April 18, 1967, he was murdered by Jerry Angiulo\'s enforcers Carmen Gagliardi, Frank Otero and Ben DeChristoforo.\nThe FBI began diligent efforts to turn Barboza into an informant. In December, Joe Amico was murdered. The following month, after a ten-day trial, Barboza was sentenced to a five-year term at Walpole on the weapons charges. In the summer of 1967, Steve Flemmi met with Joseph and informed him that Gennaro Angiulo and his brothers had plans to murder him. In June 1967, Barboza turned FBI informant while imprisoned for murder, and eventually testified against Raymond Patriarca before becoming one of the first informants to enter the Witness Protection Program. The government told Barboza his wife and children would not be protected unless he agreed to testify. The government also promised to set him up in his own restaurant — and plastic surgery to change his appearance and further protect Barboza and his family — but it did not fulfill either of these promises.\nBarboza went on to testify against Raymond Patriarca and many high-ranking members and associates of the New England family. On June 20, Patriarca and Henry Tameleo were indicted for conspiracy to murder in the 1966 killing of Providence bookmaker Willie Marfeo. On August 9, Gennaro Angiulo was accused of participating in the murder of Rocco DiSeglio. Finally in October, six men were charged with the March 1965 murder of Edward "Teddy" Deegan, who had been marked for death for several burglaries which he had committed with Stephen Flemmi, in Chelsea. Shortly after the indictment of Raymond Patriarca, which drew front-page stories about Barboza as a turncoat, Barboza wrote to the Boston Herald: "All I want to be is left alone." The La Cosa Nostra was willing to pay Barboza $25,000 to quit talking. He showed some interest in the deal raising the price to $50,000 which was agreed upon but later turned down after consulting his lawyer.\nAngiulo was later found not guilty. Despite efforts by reporters to coax jurors to explain their deliberations, none did. Twenty years later, however, jury foreman Kenneth Matthews said none of the sixteen jurors had found Barboza believable, stating "He didn\'t help the state at all. He wasn\'t reliable. He was nothing as a witness".\nOn January 30, 1968, a bomb was planted in the car of Barboza\'s attorney, John E. Fitzgerald, future Rapid City, South Dakota Judge for the 7th Circuit, resulting in Fitzgerald losing his right leg below the knee. After that Barboza was moved around frequently from Thacher Island to Fort Devens and even to the Junior Officers\' quarters located in Fort Knox, Kentucky. Barboza owned a German Shepherd dog and while at Fort Knox he would walk his dog with future corrupt FBI agent John Morris who was a member of the military police at the time. In May 1968, the Deegan trial began. After 50 days of testimony and deliberations, the jury returned a guilty verdict. Found guilty and sentenced to death were Peter Limone, Louis Greco, Henry Tameleo and Ronald Cassesso. Sentenced to life in prison were Joseph Salvati and Wilfred Roy French.\nBarboza was given a one-year prison term, including time served. He was paroled in March 1969, under the name of "Joseph Bentley", and relocated to Santa Rosa, California where he enrolled in a culinary arts school. In summer 1970, Barboza murdered Clay Wilson. According to the FBI, this was the 26th murder by Barboza. In 1971, he pleaded guilty to a second-degree murder charge and was sentenced to five years at Folsom Prison. In prison Barboza wrote poems about the American Mafia, "Boston Gang War", "The Mafia Double Crosses", "A Cat\'s Lives" and "The Gang War".',
  'infobox': None,
  'tables': [],
  'images': [],
  'is_lead': False,
  'last_update': 'This page was last edited on 7 April 2026, at 21:08(UTC).',
  'full_location': '-',
  'category': 'murder',
  'location': '-'},
 {'page_title': 'Joseph Barboza',
  'section_title': 'False testimony against rivals',
  'breadcrumb': ['Joseph Barboza',
   'Criminal career',
   'Turning government witness',
   'False testimony against rivals'],
  'content': 'While working for the FBI, Agent H. Paul Rico helped to frame Joseph Salvati, Peter Limone, Louis Greco as well as his former mob superior, Henry Tameleo for the murder of Edward Deegan.\nOut of the six people convicted for the murder, only Ronald "Ronnie the Pig" Cassesso and Wilfred Roy French were actually involved and present in the alley where the murder took place. FBI agent Paul Rico had offered French and Cassesso leniency if they would corroborate Barboza\'s false testimony. Both French and Cassesso refused the offer and when French was threatened with the death penalty he responded by telling Rico to "warm up the electric chair". Cassesso died in prison 30 years later. French was finally freed 34 years later.\nWinter Hill enforcer John Martorano became a government witness in 1999 after learning that both Stephen Flemmi and James "Whitey" Bulger were FBI informants and had been delivering information about the Mafia and the Winter Hill Gang to them. In his plea agreement, he told the Drug Enforcement Administration (DEA) agent that Barboza had admitted to lying about the men convicted of killing Teddy Deegan.\nMartorano also revealed that Vincent Flemmi had admitted to murdering Deegan.\nTameleo and Greco died in prison after serving almost 30 years, and Salvati and Limone were finally released in 1997 and 2001, respectively. The families of Greco, Tameleo, Salvati and Limone filed lawsuits totaling in excess of one billion dollars filed against the Federal government. In July 2007, U.S. District Judge Nancy Gertner in Boston found the bureau helped convict the four men and the U.S. Government was ordered to pay $100 million in damages to the four defendants.',
  'infobox': None,
  'tables': [],
  'images': [],
  'is_lead': False,
  'last_update': 'This page was last edited on 7 April 2026, at 21:08(UTC).',
  'full_location': '-',
  'category': 'murder',
  'location': '-'},
 {'page_title': 'Joseph Barboza',
  'section_title': 'Death',
  'breadcrumb': ['Joseph Barboza', 'Death'],
  'content': 'Barboza was released on October 30, 1975 and moved into a $250-a-month apartment as "Joseph Donati". He took the last name from twin brothers Richard and Robert Donati. After he was befriended by small-time South Boston hoodlum James Chalmas, Gennaro Angiulo found out where Barboza was. On February 11, 1976, Barboza left Chalmas\' San Francisco apartment; as he was walking to his car, he was hit by four shotgun blasts at close range. Although he was armed with a Colt .38, Barboza never had a chance to draw it.\nBarboza\'s attorney F. Lee Bailey said about his death "With all due respect to my former client, I don\'t think society has suffered a great loss".\nIlario Zannino, chief enforcer of Gennaro Angiulo, was later overheard on a hidden bug saying that it was J. R. Russo who had assassinated Barboza. In the conversation, Zannino described Russo as "a genius with a carbine".\nBarboza is buried in South Dartmouth Cemetery in Dartmouth, Massachusetts.',
  'infobox': None,
  'tables': [],
  'images': [],
  'is_lead': False,
  'last_update': 'This page was last edited on 7 April 2026, at 21:08(UTC).',
  'full_location': '-',
  'category': 'murder',
  'location': '-'}]

In [18]:
elastic_docs = []
for title, data in c4g_pages_db.items():
  restructure_page(title, data)

In [19]:
elastic_docs[402]

{'page_title': 'Battle of Mucojo',
 'section_title': 'Battle',
 'breadcrumb': ['Battle of Mucojo', 'Battle'],
 'content': "On 22 April 2021, militants took and occupied the town of Mucojo and Pangane with the Mozambican military retaking the towns.  The village had been sieged by Mozambican and Rwandan troops since May 2021\nOn 28 August, militants of an unknown group raided and re-occupied the town of Mucojo.  Reports came that the town and a nearby village were captured, with the Mozambique military confirming the claim.  The militants were identified as anti-Islamic as they beheaded an Islamic imam.  The militants continued to kill civilians and behead fisherman.  Members of ISIL and Al-Shabaab, attacked Mucojo and killed most of the anti-Islamic militants in Mucojo and the nearby town of Quiterajo.  The town's mayor was later killed by the Islamist militants with him being beheaded.  The Mozambique army later retook the village, but it was recaptured by the Islamist militants when Al-Shabaab members retreated from Tanzania to Mucojo.  Militants later burned the village down, with 164 houses destroyed.\nOn 9 September, militants raided and occupied Oluma, a village near Mucojo.  The island of Vamize was also occupied by militants, off the shore of Mucojo.\nOn 30 September and throughout 8 October, militants had fully occupied all of the villages nearby Mucojo.  On 26 October, militants in Mucojo started an offensive into southern Tanzania.  On 29 October, Mozambican and Rwandan forces captured all of Mucojo, ending the occupation.\nBy 2022, unrest continued in Mucojo, with incidents of looting being reported.\n\n\n== References ==",
 'infobox': None,
 'tables': [],
 'images': [],
 'is_lead': False,
 'last_update': 'This page was last edited on 10 April 2026, at 23:33(UTC).',
 'full_location': 'Mucojo,Macomia,Cabo Delgado,Mozambique',
 'category': 'wanted',
 'location': 'Mozambique'}

In [20]:
import json

def save_to_jsonl(docs, filename):
    with open(filename, 'w', encoding='utf-8') as f:
        for doc in docs:
            f.write(json.dumps(doc, ensure_ascii=False) + '\n')

save_to_jsonl(elastic_docs, f'{SAVEFILE_DIR}flat_wiki_1.jsonl')

### ???